### ISSUE TITLE
HashGet throws a System.ExecutionEngineException with Stackify Prefix installed

### ISSUE THREAD

**Issue by Tankatronic** [StackExchange/StackExchange.Redis#448] opened 2016-07-13 19:48 UTC
We are encountering this exception pretty regularly when using Redis in a Sitefinity web project. This exception occured both in 1.0.488 and 1.1.603, using Redis on Windows 2.8 and 3.2. This is a 64 bit system and have been replicated on the same project on multiple machines in our environment.

This error so far has only occured immediately after restarting the website in IIS or republishing it. Sitefinity runs through a lot of configuration\setup on the initial start up of the site and pages are not yet viewable, but immediately after it completes and it tries to load a page that is using Redis it throws the exception maybe 80% of the time. Our controller for the page is making a simple hashget request to Redis. We have another website project (not using sitefinity) that uses Redis extensively that has never encountered this error.

Although the exception is thrown in StackExchange.Redis.dll, I know that it could just be a symptom of a bigger problem. Sitefinity includes a lot of libraries in its project and it runs a lot of setup during the initial start of the web site.

**Comment by orck-adrouin** [comment] 2016-07-13 19:54
Can you include the call stack?

**Comment by Tankatronic** [comment] 2016-07-13 20:12
The call stack property is null when I am debugging. I downloaded the source code (v1.0.488) and compiled with the debug configuration and was able to see where the exception was being thrown. Here's a screen shot that shows the call stack in the call stack window.

![capture](https://cloud.githubusercontent.com/assets/4115700/16818195/29aa5404-490c-11e6-821a-7c80f0c745a3.PNG)

**Comment by Tankatronic** [comment] 2016-07-14 21:19
Is it possible that this issue is arising because of our development environment? Maybe Visual Studio, or the debug\unoptimized libraries are causing this to occur. We have not yet hit this exception on a production server that has been running Redis for the past week. 

This error has popped up in other projects as well not involving Sitefinity, so we can probably rule that out. It seems to occur most often right after I rebuild the solution.

**Comment by dmarlow** [comment] 2016-07-22 17:10
After adding the StackExchange.Redis.StrongName, I'm seeing it now as well. I've never seen this exception before. Also usually happens after I rebuild my solution as well.

**Comment by Tankatronic** [comment] 2016-08-03 20:56
@dmarlow We were able to resolve this issue ourselves. A couple of us had installed a tool called Prefix by Stackify, which is a profiler that installs a couple modules in IIS and monitors the w3wp process (monitors requests, db calls including Redis, and logs all exceptions even if they are caught). When debugging I initially had tried just turning off the profiler service but still got the error. However, after a complete  uninstall of Prefix and removing the two IIS modules we have not seen the Fatal Execution Engine Exception issue pop up again. 

It is a shame though, Prefix was a handy tool and I'd like to be able to use it again. Is anyone else able to reproduce this issue by installing Prefix and using Redis in a web application?

**Comment by dmarlow** [comment] 2016-08-03 21:13
@Tankatronic thanks for the information. I too use Prefix. I'll let them know of the issue and point back to this thread.

**Comment by dotnetjt** [comment] 2016-08-03 21:51
Hey guys - Jason, CTO of Stackify here. Please do send over the details to support@stackify.com and we will look into it.

**Comment by Tankatronic** [comment] 2016-08-03 21:58
@dotnetjt I submitted a request as well about a hour ago. Thanks!

**Comment by Tankatronic** [comment] 2016-08-04 13:44
I'll run some more tests this morning without Prefix, with Prefix installed, and with Prefix installed and the service stopped and let you know the results.

**Comment by Tankatronic** [comment] 2016-08-04 14:45
Alright, I did confirm that if you disable the profiler _properly_ (from the windows tray app) that the exception does not occur. I was stopping it from the Windows Service because I forgot about the tray icon. It was not until I reinstalled and was prompted to enable through the tray Icon that I realized I probably made a mistake. 

I was able to recreate the exception by creating a new MVC project in visual studio. I added the StackExchange.Redis nuget package and created the following class:

```
using StackExchange.Redis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TestProj
{
    public class RedisCache
    {
        private static System.Lazy<ConnectionMultiplexer> lazyRedis = new System.Lazy<ConnectionMultiplexer>(
            () => { return ConnectionMultiplexer.Connect("localhost,abortConnect=false,connectRetry=3,allowAdmin=true,"); });

        private IDatabase redisDb;

        private static ConnectionMultiplexer redis
        {
            get
            {
                return lazyRedis.Value;
            }
        }

        public RedisCache()
        {
            redisDb = redis.GetDatabase();
        }

        public string HashGet(string key, string field)
        {
            return redisDb.HashGet(key, field);
        }

        public void HashSet(string key, string field, string value)
        {
            var entry = new HashEntry(field, value);
            redisDb.HashSet(key, new HashEntry[] { entry });
        }

        public RedisValue[] HashMGet(string key, RedisValue[] fields)
        {
            return redisDb.HashGet(key, fields);
        }

    }
}
```

Then inside the HomeController class, I modified Index() to this:

```
public ActionResult Index()
{
    RedisCache cache = new RedisCache();            
    cache.HashSet("key", "field", "value");
    cache.HashGet("key", "field");
    return View();
}
```

I created the website in IIS and pointed it to the development directory and just reloaded the main page after rebuilding. I would encounter the issue somewhat often, maybe the longest streak I would go would be 5 or so reloads, but I encountered it multiple times. I never encountered the issue with the profiler disabled.

**Comment by NickCraver** [comment] 2016-08-11 10:57
@Tankatronic I'm not sure what we can do here, should we close this out? It seems like a move to an issue on @dotnetjt may be more productive? Let me know, just trying to catch up on an insane amount of GitHub email here.

**Comment by dotnetjt** [comment] 2016-08-11 13:33
@NickCraver yeah, Nick, sorry. It's all in my scope right now. For some reason our profiler is causing an access violation. I'm working with these guys to resolve it; can't reproduce even with the solution @Tankatronic provided, so going to do some remote debugging today with @dmarlow

**Comment by dotnetjt** [comment] 2016-08-12 18:32
Quick update. Issue has been reproduced and I am working on a fix. If you've never had the chance, working with the internals of the CLR is _loads_ of fun.

**Comment by mgravell** [comment] 2016-08-13 23:37
Is that in the same way that root canal surgery is loads of fun?

**Comment by Tankatronic** [comment] 2016-08-13 23:43
@dotnetjt That's exciting that you were able to reproduce it. If you need anything else from me let me know, I am still out of office but I am able to remote in if you need any additional information. Please keep us updated!

**Comment by moxplod** [comment] 2016-08-24 23:32
@dotnetjt  any updates on this issue

**Comment by dotnetjt** [comment] 2016-08-24 23:35
Yes, it has been resolved to the best of our knowledge in the latest release that went out today, and can be downloaded at prefix.io

**Comment by moxplod** [comment] 2016-08-24 23:51
Thanks - will try it out!

**Comment by NickCraver** [comment] 2016-11-20 19:25
Closing this out to cleanup, @dotnetjt thanks again for running with this and getting a fix out!

**Closed by NickCraver** 2016-11-20 19:25 UTC

**Comment by SorenA** [comment] 2017-02-16 10:24
Still happens for me with the newest version of Prefix.

**Comment by tig66208** [comment] 2017-02-16 15:42
@SorenA this actually just popped up on my radar again with our paid product, Retrace. I have a fix being tested there with some clients and hope to incorporate into Prefix in the next week or so. If I get a release candidate ready, would you be willing to reproduce / validate for me?

**Comment by SorenA** [comment] 2017-02-17 07:08
@tig66208 Yes, definitely.

**Comment by SorenA** [comment] 2017-03-01 09:52
@tig66208 Hi again, have there been any progress?

**Comment by tig66208** [comment] 2017-03-01 14:26
There has been - it's really the *same* issue manifesting in a slightly different way. We have a build we are working on that should rectify it, but I don't yet have timing on it. Our main priority is getting the fix out for our commercial product, which is ready, just scheduling the release of it.

**Comment by SorenA** [comment] 2017-03-02 06:59
That sounds good. I can fully understand Retrace taking precedence, looking forward to a fix. I'm still available for testing if you need me.

**Comment by dmarlow** [comment] 2019-02-06 18:47
This thread is probably not the right place. If there's a better place, please point me in the direction where this can continue to be tracked.

I'm still seeing the issue. I have servers with the Stackify profiler enabled on it and have several dumps with the same exception and stack trace.
