### ISSUE TITLE
Random connectivity exception.

### ISSUE THREAD

**Issue by Davidsual** [StackExchange/StackExchange.Redis#441] opened 2016-07-07 09:52 UTC
Hi

I am using StackExchange.Redis version: 1.0.316.0

I am currently experiencing the below issue:

```
Redis Connection Failed:
Endpoint: Unspecified/MYSERVER:6379
Failure type: SocketFailure
Connection type: Subscription
Exception is: Messages:
SocketFailure on MYSERVER:6379/Subscription, origin: CheckForStaleConnection, input-buffer: 0, outstanding: 1, last-read: 61s ago, last-write: 1s ago, unanswered-write: 1s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 1s ago, last-mbeat: 0s ago, global: 0s ago, mgr: RecordConnectionFailed_ReportFailure, err: never
```

I cannot find a pattern for replicating this issue, I know that randomly appear in my log.

I am added more log in order to identify the behaviour that is causing that.

Do you have any Idea?

is it happen to anyone else?

Thank you,

Davide Trotta

**Comment by Davidsual** [comment] 2016-07-07 09:54
Hi 

I am using StackExchange.Redis version: 1.0.316.0

I am currently experiencing the below issue:

Redis Connection Failed:
Endpoint: Unspecified/MYSERVER:6379
Failure type: SocketFailure
Connection type: Subscription
Exception is: Messages:
SocketFailure on MYSERVER:6379/Subscription, origin: CheckForStaleConnection, input-buffer: 0, outstanding: 1, last-read: 61s ago, last-write: 1s ago, unanswered-write: 1s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 1s ago, last-mbeat: 0s ago, global: 0s ago, mgr: RecordConnectionFailed_ReportFailure, err: never

I cannot find a pattern for replicating this issue, I know that randomly appear in my log.

I am added more log in order to identify the behaviour that is causing that.

Do you have any Idea?

is it happen to anyone else?

Thank you,

Davide Trotta

**Comment by lonegunmanb** [comment] 2016-07-12 11:06
Our version is 1.1.603 and we've encountered the very same exception:
StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: GET 3CB346F2-33D2-4287-B1E1-1D27D4C5B168 ---> StackExchange.Redis.RedisConnectionException: SocketFailure on baseredis.dc.beyondh.com:6379/Interactive, origin: CheckForStaleConnection, input-buffer: 0, outstanding: 2, last-read: 1s ago, last-write: 0s ago, unanswered-write: 1s ago, keep-alive: 60s, pending: 0, state: ConnectedEstablished, in: 0, ar: 0, last-heartbeat: 0s ago, last-mbeat: 0s ago, global: 0s ago, mgr: RecordConnectionFailed_ReportFailure, err: never
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 1965
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in C:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1449
   at NextPms.Logic.Cache.Redis.RedisCacheClient.TryGet(String key, String& value) in c:\BuildAgent\work\2ed8b2f04ece707d\NextPms.Logic\Cache\Redis\RedisCacheClient.cs:line 1201

I've learned that SocketFailure was thrown in CheckForStaleConnection when response timeout, but in which cases will cause this? A slow network? Or not enough IOCP threads? Please advice, thanks!

**Comment by Davidsual** [comment] 2016-07-12 11:20
I am trying to concentrate as well on connectivity/network issues.. but honestly so far I have not found the cause of these issues.

**Comment by lonegunmanb** [comment] 2016-07-14 04:03
In my case, we've found the root case, because there were too many connections on our redis server and server's CPU was sky high, so that the server could not respond in time.

But hence we've found another strange problem. Our app connect to redis server via haproxy, when the proxy restart, the driver'll going mad, it created thousands of sockets and threads, then cause very high CPU.

I've created a  sample trying to reproduct the problem but I failed. Still trying to find out the root cause.

**Comment by lonegunmanb** [comment] 2016-07-14 06:28
The reason of connections' leak's been found.
In this issue: https://github.com/StackExchange/StackExchange.Redis/issues/68

**Comment by lonegunmanb** [comment] 2016-07-14 06:47
The reason of connections' leak's been found.
In this issue: https://github.com/StackExchange/StackExchange.Redis/issues/68
@mgravell suggested that we should "check IsConnected *before* executing, and taking
appropriate steps at the call-site", and then, in this issue:https://github.com/StackExchange/StackExchange.Redis/issues/248
@debbiswal suggested that when we detected a connection's IsConnected is false, we can kill old connection and reConnect a new ConnectionMultiplexer. So I've modified my code:
private ConnectionMultiplexer GetConnectedMultiplexer()
        {
            if (MultiplexerDisconnected(_multiplexer))
            {
                lock (ConnectionsDict.GetOrAdd(_multiplexer.Configuration, _ => new object()))
                {
                    if (MultiplexerDisconnected(_multiplexer))
                    {
                        if (_multiplexer != null)
                        {
                            _multiplexer.Dispose();
                        }
                        _multiplexer = ConnectionMultiplexer.Connect(_multiplexer.Configuration);
                    }
                }
            }

            return _multiplexer;
        }

And we have a daemon task that loop query redis every 50ms, when the physical connection's broken, the multiplexer'll be reconnect and shortly disposed by other query task, then reconnect again. It's the root cause of our connections' leak.

**Comment by NickCraver** [comment] 2016-11-20 19:32
Closing this out (as we have several duplicates) so we can take a look on the latest library versions - since conditions have changed.

For anyone on this thread, please take a look at the latest version (currently 1.1.608) which has several improvements for timeouts overall. We're working on a more long-term solution for connection error handling in general via Pipelines. I'm just helping out here, @mgravell is kicking ass on the code this round.

**Closed by NickCraver** 2016-11-20 19:32 UTC
