### ISSUE TITLE
System.IO.FileNotFoundException at StackExchange.Redis.PhysicalConnection.BeginConnectAsync 

### ISSUE THREAD

**Issue by zhangruiskyline** [StackExchange/StackExchange.Redis#1046] opened 2019-01-23 19:42 UTC
Hi 

When I am using Azure functions I have observed the following error

System.IO.FileNotFoundException at StackExchange.Redis.PhysicalConnection.BeginConnectAsync

[{"parsedStack":[{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Threading.Tasks.Task.ThrowIfExceptional","level":0,"line":0},{"assembly":"mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","method":"System.Threading.Tasks.Task.Wait","level":1,"line":0},{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46","method":"StackExchange.Redis.ConnectionMultiplexer.ConnectImpl","level":2,"line":0},{"assembly":"IDmapping, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","method":"IDmapping.EventhubIDSync.get_RedisConnection","level":3,"line":0}],"outerId":"0","message":"One or more errors occurred.","type":"System.AggregateException","id":"54116930"},{"parsedStack":[{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46","method":"StackExchange.Redis.PhysicalConnection.BeginConnectAsync","level":0,"line":0},{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46","method":"StackExchange.Redis.PhysicalBridge.GetConnection","level":1,"line":0},{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46","method":"StackExchange.Redis.ServerEndPoint.CreateBridge","level":2,"line":0},{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46","method":"StackExchange.Redis.ServerEndPoint.GetBridge","level":3,"line":0},{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46","method":"StackExchange.Redis.ConnectionMultiplexer.ActivateAllServers","level":4,"line":0},{"assembly":"StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46","method":"StackExchange.Redis.ConnectionMultiplexer+<ReconfigureAsync>d__151.MoveNext","level":5,"line":0}],"outerId":"54116930","message":"Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.","type":"System.IO.FileNotFoundException","id":"19342748"}]
--

**Comment by zhangruiskyline** [comment] 2019-01-23 20:02
and if we switch back to 1.2.6 version I do not see this problem

**Comment by fizch** [comment] 2019-01-23 20:03
I am seeing that error a lot since moving to standard/core projects. That is typically caused by the file either not being in your bin folder or being the incorrect version. Make sure that all of your dependencies get packaged up for deployment.

**Comment by zhangruiskyline** [comment] 2019-01-23 21:47
which file could be missing? I switched back to stackexchange.redis 1.2.6 and it works perfectly

One thing I also noticed that is for redis 2.0+, if we have multiple instances(in my application multiple Azure functions) creating connection to same redis, had issue of inbalanced traffic/connection as I noticed some instanace could process much longer than others, while in 1.2.6 we do not have such. is threading model changed in 2.0?

**Comment by fizch** [comment] 2019-01-23 22:16
> Could not load file or assembly 'System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file 

That is the exception message. Do you see System.Threading.Tasks.Extensions.dll in your bin/lib folder?

**Comment by zhangruiskyline** [comment] 2019-01-23 23:04
Thanks, is this package only needed for redis 2.0+ lib, not 1.2.6? I did check and not be able to find it. however, in 1.2.6 I do not find it neither. so do we need to install it explcitly https://www.nuget.org/packages/System.Threading.Tasks.Extensions/?

**Comment by fizch** [comment] 2019-01-23 23:19
> is this package only needed for redis 2.0+ lib, not 1.2.6?

I do not know the answer to that question. It is possible that they added a dependency for it between releases. 

Yes, you can download it as a NuGet package. Using the new project file layout should automatically add that in the deployment package.

**Comment by zhangruiskyline** [comment] 2019-01-23 23:21
Thanks @fizch , BTW, did you have experience on 2.0+ redis , do you still need to tune the thread pool setup?

**Comment by zhangruiskyline** [comment] 2019-01-23 23:40
Thanks, I added the corresponding nuget and another exception happen seeing not finding other pkg, so roll back to 1.2.6

regarding timeout, I mean if we access 
https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Timeouts.md , where we need to manually adjust thread setup in order to prevent TO

**Comment by NickCraver** [comment] 2019-03-02 14:26
In this setup, are you using `packages.config` or `<PackageReference />` for loading your NuGet packages? The former (the old way) has a lot of rough edges and general issues with .NET Core projects, we've found. The new (`<PackageReference />`) way is much, much cleaner and all around better, though.

**Comment by NickCraver** [comment] 2020-03-14 17:54
Closing due to inactivity. If others are hitting binding redirect issues I recommend reading my best attempt to explaining the causes, background, and resolution options in https://nickcraver.com/blog/2020/02/11/binding-redirects/

**Closed by NickCraver** 2020-03-14 17:54 UTC
