### ISSUE TITLE
RedisKey.ToString() fails on Mono 4.0.3 / DNX 4.5.1 (1.0.0-beta6)

### ISSUE THREAD

**Issue by groberts314** [StackExchange/StackExchange.Redis#262] opened 2015-08-14 16:59 UTC
Looks like there might be a failure in `RedisKey.ToString()`:
```
System.InvalidProgramException: Invalid IL code in StackExchange.Redis.RedisKey:
ToString (): IL_0006: brfalse.s IL_0018

**Comment by mgravell** [comment] 2015-08-14 18:43
Well that's odd... I don't remember doing anything unusual there. Will
check when near a PC.

**Comment by NickCraver** [comment] 2015-10-11 21:49
@groberts314 are you still seeing this on the current beta? There were a few IL issues I'm aware of fixed in beta7 and 8 - curious if this was covered by those.

**Comment by LukeWinikates** [comment] 2016-01-18 23:14
I'm seeing this on OSX with Mono 4.2.1 using dnx 1.0.0-rc1-update1. ` ((RedisKey)"foo").ToString();` is enough to reproduce it. 

I was able to work around it-- the caller of `ToString` was Moq, and I replaced the actual string with `It.IsAny<RedisKey>()` and I don't see the error anymore.

**Comment by NickCraver** [comment] 2016-01-25 14:11
@LukeWinikates thanks for the update - I'm going to close this issue out. Not because we don't care! But it looks like we've seen this before and need to dig - merging with #152.

**Closed by NickCraver** 2016-01-25 14:11 UTC
