### ISSUE TITLE
Redis connections causing IIS App Pool to become unresponsive

### ISSUE THREAD

**Issue by MomentumPete** [StackExchange/StackExchange.Redis#266] opened 2015-08-20 11:07 UTC
Hi, we are using the Stack Exchange.Redis client against the Microsoft Port of Redis and we are experiencing an issue that seems to show over time when under load. The pattern we have seen is that during the day as our load reaches a steak level things work well, until about 3 hours into the day. At that point we start to see a gradual then sudden slowdown ( within 5 to 10 minutes) ending with things locking up. Initially, we thought this has to do with Redis and began to recycle redis to get around the issue. Additionally, we turned off replication and db snapshotting to attempt to help the situation.

We then took a different approach to clearing the issue. We began to perform App pool recycling to the pool that is hosting the client that calls to Redis. This seemed to be effective. Additional, since then we have turned replication on again, and are splitting the read load across the two boxes.

We have also done some stand alone testing, with two version of our read client. We have a console application that goes to redis and requests back our 850 keys continuously. 

We have a second version of the same code, with the difference being that the client call to redis is hosted in a IIS Hosted Web Service.

The console application seems to not fail, while the version of the same code hosted in IIS seems to get overwhelmed fairly quickly. The app pool becomes unresponsive and requires restarting. 

Additionally, we performed the same IIS based test, but commented our the actual read from Redis ( insatiate the client and dispose, with no read call and we were successful.

This is test is not exactly the same scenario as it has a higher volume, but does seem to get to the same result. We are setting up a test that is closer to reality and incorporates a load over time. 

That said as this is seriously affecting our production environment, I was wondering if there where any thoughts or ideas over this issue. 

Below is a copy of our client code. Thanks in advance for the assistance. This is a great product and we appreciate the effort in making and maintain it.

Pete

```C#
using System;
using System.IO;
using System.Text;
using Newtonsoft.Json;
using StackExchange.Redis;
using System.Configuration;
using System.IO.Compression;
using Microsoft.Practices.EnterpriseLibrary.Logging;
using Microsoft.Practices.EnterpriseLibrary.ExceptionHandling;

namespace CachingCommon.Managers
{
    public class StackRedisManager : IDisposable
    {
        IDatabase client = null;
        ConnectionMultiplexer multiplexer;
        string connectionStr = ConfigurationManager.AppSettings["RedisConnectionString"];
        bool isCacheZipEnabled = bool.Parse(ConfigurationManager.AppSettings["IsCacheZipEnabled"]);

        /// <summary>
        /// Gets the client.
        /// </summary>
        /// <value>
        /// The client.
        /// </value>
        IDatabase Client 
        {
            get 
            {
                if (multiplexer == null || !multiplexer.IsConnected)
                {
                    if (multiplexer != null)
                    {
                        multiplexer.Close(false);
                        multiplexer.Dispose();
                        multiplexer = null;
                    }

                    multiplexer = ConnectionMultiplexer.Connect(connectionStr);
                    multiplexer.ConnectionFailed += multiplexer_ConnectionFailed;
                    multiplexer.ErrorMessage += multiplexer_ErrorMessage;
                    multiplexer.InternalError += multiplexer_InternalError;
                }

                client = multiplexer.GetDatabase();

                return client;
            }
        }

        /// <summary>
        /// Initializes the <see cref="StackRedisManager"/> class.
        /// </summary>
        public StackRedisManager()
        {
            //multiplexer = ConnectionMultiplexer.Connect(connectionStr);
            //client = multiplexer.GetDatabase();

            //multiplexer.ConnectionFailed += multiplexer_ConnectionFailed;
            //multiplexer.ErrorMessage += multiplexer_ErrorMessage;
            //multiplexer.InternalError += multiplexer_InternalError;
        }

        /// <summary>
        /// Gets the specified cache.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="key">The key.</param>
        /// <returns></returns>
        public T Get<T>(string key)
        {
            var result = default(T);

            try
            {
                var jsonData = Client.StringGet(key);
                if (jsonData.HasValue)
                {
                    result = JsonConvert.DeserializeObject<T>(jsonData);
                }
            }
            catch (Exception ex)
            {
                lock (Locks.LockForLogging)
                {
                    Logger.Write(string.Format("Error in Get from cache this key: {0}", key), "Cache Logging");
                    ExceptionPolicy.HandleException(ex, "Cache Exception Policy");
                }
            }

            return result;
        }

        /// <summary>
        /// Gets from zip.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="key">The key.</param>
        /// <returns></returns>
        public T GetFromZip<T>(string key)
        {
            var result = default(T);

            try
            {
                var jsonData = Client.StringGet(key);
                if (jsonData.HasValue)
                {
                    var data = (isCacheZipEnabled) ? DecompressString(jsonData) : jsonData.ToString();
                    result = JsonConvert.DeserializeObject<T>(data);
                }
            }
            catch (Exception ex)
            {
                lock (Locks.LockForLogging)
                {
                    Logger.Write(string.Format("Error in GetFromZip this key: {0}", key), "Cache Logging");
                    ExceptionPolicy.HandleException(ex, "Cache Exception Policy");
                }
            }

            return result;
        }

        /// <summary>
        /// Sets the specified cache.
        /// </summary>
        /// <param name="key">The key.</param>
        /// <param name="value">The value.</param>
        public void Set(string key, object value)
        {
            try
            {
                var jsonList = JsonConvert.SerializeObject(value);
                Client.StringSet(key, jsonList);
            }
            catch(Exception ex)
            {
                lock (Locks.LockForLogging)
                {
                    Logger.Write(string.Format("Error in Set to cache this key: {0}", key), "Cache Logging");
                    ExceptionPolicy.HandleException(ex, "Cache Exception Policy");
                }
            }
        }

        /// <summary>
        /// Sets to zip.
        /// </summary>
        /// <param name="key">The key.</param>
        /// <param name="value">The value.</param>
        public void SetToZip(string key, object value)
        {
            try
            {
                var jsonData = JsonConvert.SerializeObject(value);
                var data = (isCacheZipEnabled) ? CompressString(jsonData): jsonData;

                Client.StringSet(key, data);
            }
            catch (Exception ex)
            {
                lock (Locks.LockForLogging)
                {
                    Logger.Write(string.Format("Error in SetToZip this key: {0}", key), "Cache Logging");
                    ExceptionPolicy.HandleException(ex, "Cache Exception Policy");
                }
            }
        }

        /// <summary>
        /// Deletes the specified key.
        /// </summary>
        /// <param name="key">The key.</param>
        public void Del(string key)
        {
            try
            {
                Client.KeyDelete(key);
            }
            catch (Exception ex)
            {
                lock (Locks.LockForLogging)
                {
                    Logger.Write(string.Format("Error deleting from cache this key: {0}", key), "Cache Logging");
                    ExceptionPolicy.HandleException(ex, "Cache Exception Policy");
                }
            }
        }

        /// <summary>
        /// Performs application-defined tasks associated with freeing, releasing, or resetting unmanaged resources.
        /// </summary>
        public void Dispose()
        {
            if (client != null && client.Multiplexer != null)
            {
                client.Multiplexer.Close(true);
                client.Multiplexer.Dispose();
                client = null;
            }
        }

        /// <summary>
        /// Compresses the string.
        /// </summary>
        /// <param name="text">The text.</param>
        /// <returns></returns>
        string CompressString(string text)
        {
            var result = string.Empty;

            try
            {
                byte[] buffer = Encoding.UTF8.GetBytes(text);
                var memoryStream = new MemoryStream();
                using (var gZipStream = new GZipStream(memoryStream, CompressionMode.Compress, true))
                {
                    gZipStream.Write(buffer, 0, buffer.Length);
                }

                memoryStream.Position = 0;

                var compressedData = new byte[memoryStream.Length];
                memoryStream.Read(compressedData, 0, compressedData.Length);

                var gZipBuffer = new byte[compressedData.Length + 4];
                Buffer.BlockCopy(compressedData, 0, gZipBuffer, 4, compressedData.Length);
                Buffer.BlockCopy(BitConverter.GetBytes(buffer.Length), 0, gZipBuffer, 0, 4);
                result = Convert.ToBase64String(gZipBuffer);
            }
            catch(Exception ex)
            {
                lock (Locks.LockForLogging)
                {
                    ExceptionPolicy.HandleException(ex, "Cache Exception Policy");
                }
            }

            return result;
        }

        /// <summary>
        /// Decompresses the string.
        /// </summary>
        /// <param name="compressedText">The compressed text.</param>
        /// <returns></returns>
        string DecompressString(string compressedText)
        {
            var result = string.Empty;

            try
            {
                byte[] gZipBuffer = Convert.FromBase64String(compressedText);
                using (var memoryStream = new MemoryStream())
                {
                    int dataLength = BitConverter.ToInt32(gZipBuffer, 0);
                    memoryStream.Write(gZipBuffer, 4, gZipBuffer.Length - 4);

                    var buffer = new byte[dataLength];

                    memoryStream.Position = 0;
                    using (var gZipStream = new GZipStream(memoryStream, CompressionMode.Decompress))
                    {
                        gZipStream.Read(buffer, 0, buffer.Length);
                    }

                    result = Encoding.UTF8.GetString(buffer);
                }
            }
            catch(Exception ex)
            {
                lock (Locks.LockForLogging)
                {
                    ExceptionPolicy.HandleException(ex, "Cache Exception Policy");
                }
            }

            return result;
        }

        /// <summary>
        /// Handles the InternalError event of the multiplexer control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="InternalErrorEventArgs"/> instance containing the event data.</param>
        void multiplexer_InternalError(object sender, InternalErrorEventArgs e)
        {
            var exc = e.Exception;
        }

        /// <summary>
        /// Handles the ErrorMessage event of the multiplexer control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="RedisErrorEventArgs"/> instance containing the event data.</param>
        void multiplexer_ErrorMessage(object sender, RedisErrorEventArgs e)
        {
            var mssg = e.Message;
        }

        /// <summary>
        /// Handles the ConnectionFailed event of the multiplexer control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="ConnectionFailedEventArgs"/> instance containing the event data.</param>
        void multiplexer_ConnectionFailed(object sender, ConnectionFailedEventArgs e)
        {
            var ex = e.Exception;

            multiplexer = ConnectionMultiplexer.Connect(connectionStr);
            client = multiplexer.GetDatabase();
        }
    }
}
```

**Comment by sgreer** [comment] 2015-08-20 20:19
I'd like to report that I suspect I encountered a similar issue with our product using the 1.0.481 version.  We use the RedisScaleoutConfiguration for our SignalR backplace, and on Monday, as a large load of requests began triggering SignalR events across 4 servers, our application became unresponsive.  One of the few changes made between releases was to update from 1.0.450 to 1.0.481.  

While I cannot at this point definitively state that StackExchange.Redis was the cause of this, this issue report makes me suspect that it may have been.  I have moved back to 1.0.450 on our production servers and will do more load testing over the weekend and next week to see if I can pinpoint the issue.

**Comment by MomentumPete** [comment] 2015-08-20 20:42
Update: The console application began to fail also, just after a longer period of time. We added a forced garbage collection every X number of cycles, and the process seems to be holding up. We are doing a longer term but with an occasional GC collect the application seems to go without crashing the application pool. Please advise if their is a better approach to this.

Thanks

Pete

**Comment by MomentumPete** [comment] 2015-08-28 19:30
Update: After additional testing and isolation of the client code to its own application pool we find that the code fails after time and under load. We tried forcing GC and recycling the application pool every 2500 transaction and we still failed. The GC and app pool changes seemed to extend the time to failure, but we still saw the app pool freeze. At the app pool level it seemed to show steady growth on the app pool Garbage Collection handles until the it failed. This behavior is not seen when running as a windows service or in  a command line application. This only happens when hosted in an IIS application pool.

**Comment by kylestittleburg** [comment] 2015-08-31 13:46
@MomentumPete Are you able to share your test code that exercises `StackRedisManager`?

**Comment by negospo** [comment] 2016-01-04 12:48
did you get any solution for this problem?

**Comment by MomentumPete** [comment] 2016-01-04 13:33
Yes. We abandoned the StackExchange client and moved to the ServiceStack client. They provided a evaluation version that I was able to perform a side by side test using the same code. The ServiceStack based client has now been in production for 3 months without issue.

**Comment by mgravell** [comment] 2016-01-04 22:21
I'm curious what the life cycle on your connection is when this happens -
how often are you creating new multiplexers? Because: we don't see this
(and we use IIS extensively)

**Comment by negospo** [comment] 2016-01-04 22:50
I had this same problem, with less than 10k calls iis fought. I tried in every way using the ServiceStack, CloudStructures and Stackexchange. Finally managed to solve the problem using the BookSleeve. Besides being faster it does not catch the connection sockets.

**Comment by mgravell** [comment] 2016-01-04 22:55
Booksleeve is the fore-runner to SE.Redis. again: can you describe your
life-cycle on connections? We do many millions of ops without issue.
Whatever it is: is is situational - would love to understand the situation

**Comment by negospo** [comment] 2016-01-05 13:50
Our application is a niche social network. We have a web API responsible for all data traffic. We use Redis to save all the "hot data". Basically all our GETS are made in Redis. While SETS go to SQLServer (historical data) and Redis.
The problem is that after some time the API stopped responding. We found that some of the Redis Client for .Net left open socket connections by the number of IIS threads explode. Basically WebAPI receives the request, opens the connection to the Redis, returns the data, closes the connection with Redis and returns JSON. Each new request to WebAPI is created a new connection with Redis.

**Comment by negospo** [comment] 2016-01-05 13:58
Our goal is to support 10k calls per second. Apparently it is possible doubling that goal

**Comment by nmehlei** [comment] 2016-01-05 14:13
This is not how this library is supposed to be used. StackExchange.Redis is a multiplexer and as such it is not a good idea to open a new connection to redis for every request as the connection is meant to be shared across requests.

**Comment by negospo** [comment] 2016-01-05 14:33
nmehlei é verdade. me equivoquei. Temos um Getway que controla a conexão com o Redis. Sempre que uma conexão tiver aberta ele usa ela. Se estiver fechada ou fechando ele cria uma nova conexão. Estamos usando o BookSleeve. Vocês conhecem algum OHM Client para .Net?

**Comment by negospo** [comment] 2016-01-05 14:33
miley's true. I was wrong. We have a gateway that controls the connection to the Redis. Whenever a connection is opened it uses it. If it is closed or closing it creates a new connection. We are using the BookSleeve. Do you know any OHM Client for .Net?

**Comment by SeeSharpist** [comment] 2016-03-08 19:12
In my experience, our exhaustion was caused by newing up ISubscribers on every publish call for Pub/Subing. Since ConnectionMultiplexer is heavy and does a lot under the hood, you definitely want to reuse it as much as possible, but ISubscriber is supposed to be a cheap call so we were creating a new one on every publish. However, it only took about an hour before the app crashed. 

I ended up implementing a Singleton pattern on the ISubscriber like I did on the multiplexer, and now it's been running continuously in production for about 2 months with no problems.

We don't use the database functionality of redis, but I would try reusing the IDatabase obj (Client) you have instead of getting a new one each time you call Client. Worth a shot at least.

**Comment by mgravell** [comment] 2016-03-09 11:06
That's ... odd; the ISubscriber from GetSubscriber() *is* a cheap object -
all it is is a shell object that wraps the multiplexer and your async-state
object (if one); all the methods essentially just create a message and pass
it down into the multiplexer. In the "creating a new one on every publish"
scenario, the actual object (RedisSubscriber) should be short lived and
almost certainly gen-0 collected.

So: I don't dispute you saw what you saw, but there is no reason that
calling GetSubscriber() vs caching a shared ISubscriber should cause any
problem here.

Creating a multiplexer per publish: yes, that would be absolutely brutal.

**Comment by SeeSharpist** [comment] 2016-04-13 00:16
@mgravell I thought the exact same. We're planning on expanding our pub/sub use so Ill be looking further into what else we might be doing to exacerbate this issue. Thanks for confirming my thought that this wasn't our root issue.

**Comment by Symfony2** [comment] 2016-08-02 03:24
Hello we also met this issue in our production server. We re using StackExchange.Redis 1.0.488 with CacheManager.StackExchange.Redis 080. We turned it  off since it happen(redis caching system)

So my question is this issue is fixed?

**Comment by dasjaga** [comment] 2016-08-04 05:53
hi everyone, we are using Redis as a windows service and we are facing the same issue like , its not fetching data from redis . Anyone could please list the possibilities of this.

**Comment by dasjaga** [comment] 2016-08-04 06:01
We have scenarios like, per second we are feeding to master and per second we are reading from slave. After some days its not reading , as we are getting zero value for our real time report

**Comment by Symfony2** [comment] 2016-08-04 06:07
dasjaga
What is the version of lib?

**Comment by dasjaga** [comment] 2016-08-04 06:09
stackExchange.Redis version 1.0.316.0

**Comment by Symfony2** [comment] 2016-08-04 06:11
Try to use 1.1.603.0 it seems stable in our environment

**Comment by NickCraver** [comment] 2016-11-20 21:06
Closing this out due to no activity - if it's still an issue on the latest version, please ping and I'll reopen.

**Closed by NickCraver** 2016-11-20 21:06 UTC

**Comment by Sourabh721992** [comment] 2017-07-21 06:52
Hi,

We are using Stack Exchange redis to cache the data into redis. Below is the code sample:

public class CacheLayer
{
public static string serverHost = System.Configuration.ConfigurationManager
.AppSettings["cacheMasterIp"].ToString();
public static int serverPort = Int32.Parse(System.Configuration.ConfigurationManager
.AppSettings["cacheMasterPort"].ToString());
public static Boolean isCacheEnabled = System.Configuration.ConfigurationManager
.AppSettings["CacheEnabled"].ToString().Equals("true") ?
true : false;

    public const int TimeOutType1 = 2;
    public const int TimeOutType2 = 5;

    public class CacheConnection
    {
        private static Lazy<ConnectionMultiplexer> lazyConnection = new Lazy<ConnectionMultiplexer>(() =>
        {
            var options = new ConfigurationOptions
            {
                EndPoints = { { serverHost, serverPort } },
                ConnectTimeout = 10000,
                SyncTimeout = 10000,
                AbortOnConnectFail = false
            };

            if (isCacheEnabled)
                return ConnectionMultiplexer.Connect(options);
            else
                return null;

        }, System.Threading.LazyThreadSafetyMode.PublicationOnly);

        public static ConnectionMultiplexer Connection
        {
            get
            {
                return lazyConnection.Value;
            }
        }
    }

    internal static void SaveCacheData(string strkey,  string grpId)
    {
        if (string.IsNullOrEmpty(strkey) == true)
            return;

        if (string.IsNullOrEmpty(grpId) == true)
            return;
            
        //Check if group exists in hash set. If not, add it in hash set
        StackExchange.Redis.IDatabase redis = 
                CacheConnection.Connection.GetDatabase(1);

        {
            try
            {
                if (redis != null && redis.KeyExists(strkey)
                        && Convert.ToInt32(redis.HashGet(strkey, grpId + "_Usrs").ToString()) > 0)
                {
                    Console.WriteLine("New user added to group " + grpId);
                    redis.HashIncrement(strkey, grpId+"_Usrs", 1);
                    return;
                }
                        
                else
                {
                    Console.WriteLine("New group created. Group Name: " + grpId);
                    redis.HashSetAsync(strkey, new[]
                                        {new HashEntry(grpId+ "_Id", grpId ),
                                        new HashEntry(grpId + "_CrtnDate",
                                            System.DateTime.Now.ToString
                                            ("yyyy/MM/dd HH:mm:ss")),
                                        new HashEntry(grpId+ "_Usrs", 1)});

                }
                    
            }
            catch (Exception ex)
            {
            }
        }
    }

    internal static List<string> GetCacheData(string strkey)
    {
        try
        {
            List<string> lstGroupIds = new List<string>();
            if (string.IsNullOrEmpty(strkey) == true)
                return null;

            StackExchange.Redis.IDatabase redis =
                CacheConnection.Connection.GetDatabase(1);

            if (redis != null && redis.KeyExists(strkey))
            {
                var result = redis.HashGetAll(strkey);

                //Fetching GroupId(s) from result
                foreach (var res in result)
                {
                    if (Convert.ToString(res.Name).Contains("Id"))
                        lstGroupIds.Add(res.Value);
                }

                return lstGroupIds;
            }
            else
                return null;
        }

        catch (Exception ex)
        {
            return null;
        }
    }
Will it have any drastic effects on the app pool because I have noticed that requests are consuming a lot of time. Any help will be appreciated.
