### ISSUE TITLE
TakeLock and TakeLockAsync fails to keep exclusive lock for the duration set with expiry TimeSpan

### ISSUE THREAD

**Issue by RavindraSolanki** [StackExchange/StackExchange.Redis#415] opened 2016-06-03 16:22 UTC
I'm not able to take an exclusive lock (LockTake / LockTakeAsync) for the duration set with expiry TimeSpan.

Example:

```c#
var hasLock = redisDatabase.LockTake("myKey", "aValue", TimeSpan.FromMilliseconds(1000));
var hasLockConcurrent = redisDatabase.LockTake("myKey", "aValue", TimeSpan.FromMilliseconds(1000));

// both hasLock  and hasLockConcurrent are true when hasLockConcurrent  was supposed to be false
```

It seems that when an expiry TimeSpan is set and not equals to TimeSpan.MaxValue it calls "RedisDatabase.GetStringSetMessage(RedisKey, RedisValue, TimeSpan?, When, CommandFlags)" and creates in a message with "RedisCommand.SET" when I would expect command "RedisCommand.SETNX".

To workaround this issue and successfully take an exclusive lock I did the following:

```c#
try
{
    var trans = redisDatabase.CreateTransaction();
    trans.AddCondition(Condition.KeyNotExists("myKey"));
    var acquireLockTask = trans.LockTakeAsync("myKey", "aValue", TimeSpan.MaxValue).ConfigureAwait(false);
    var setExpiryTimeTask = trans.KeyExpireAsync("myKey", TimeSpan.FromMilliseconds(1000)).ConfigureAwait(false);
    trans.Execute();

    var hasLock = await acquireLockTask;
    var hasSucceedToSetExpiryTime = await setExpiryTimeTask;
}
catch (TaskCanceledException)
{
    // LockTakeAsync has failed to take lock
}
```

**Comment by Evertras** [comment] 2017-05-08 20:58
We could not reproduce this on our end.  Is this still open?

**Comment by NickCraver** [comment] 2017-09-02 01:49
No new info or repro here either - closing out to cleanup.

**Closed by NickCraver** 2017-09-02 01:49 UTC
Labels: area:commands, bug
