### ISSUE TITLE
Connection slow when one node down

### ISSUE THREAD

**Issue by chunhualiu** [StackExchange/StackExchange.Redis#1656] opened 2020-12-30 11:24 UTC
Reproduce steps:
1. Install 3 nodes master/slave/slave with sentinel on every node.
```
10.10.2.51 slave
10.10.2.52 slave
10.10.2.53 master
```
2. Now kill redis and redis-sentinel on slave 10.10.2.52
3. The connection becomes slow now.

To make it more obvious, add two iptables rules on slave 10.10.2.52
```
iptables -I INPUT -p tcp --dport 6379 -j DROP
iptables -I INPUT -p tcp --dport 26379 -j DROP
```

The test code is very simple. On my env, it times out after 22 seconds.

```
        static void Main(string[] args)
        {
            Console.WriteLine(DateTime.Now.ToLongTimeString());
            string connectionString = "10.10.2.51,10.10.2.52,10.10.2.53,password=secret0,serviceName=redis-cluster,allowAdmin=true,connectTimeout=30000";
            var conn = ConnectionMultiplexer.Connect(connectionString);
            var db = conn.GetDatabase();

            db.StringSet("now", DateTime.Now.ToLongTimeString());

            var value = db.StringGet("now");
            Console.WriteLine(value);
        }
```

Expected behavior:
Since master and one slave are alive, connect should return without any delay.

**Comment by Victor-Tseng** [comment] 2021-01-04 03:16
May I know which version of the client library you are using?

**Comment by chunhualiu** [comment] 2021-01-04 05:15
> May I know which version of the client library you are using?

2.2.4

**Comment by NickCraver** [comment] 2021-06-26 14:58
The library is behaving as intended here - we cannot tell without connecting (or exhausting the specified timeout, which is _increased_ to 30 seconds here) what the scenario is. What if there's another master? We can't tell. We need to view everything we've been told to connect to in order to see where commands should go. If you want to give up on nodes and connect fast, lower the connect timeout accordingly, that's totally in your control by-design :)

Closing this one out to cleanup.

**Closed by NickCraver** 2021-06-26 14:58 UTC
