### ISSUE TITLE
Could not load file or assembly System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0

### ISSUE THREAD

**Issue by lefig** [StackExchange/StackExchange.Redis#1128] opened 2019-04-19 17:13 UTC
Hi all,

I have been bashing my head trying to get a fix for a tricky binding error that get thrown when attempting to connect. Incorrect versions of dependent assemblies are being loaded into the process and the problem has been mentioned previously at #1126.

I have used dependency walker and other tools to confirm the correct dependent dlls that should be loaded but for some reason the .net loader resolves these incorrectly.

I have also updated the app.config to redirect to the correct dll version but to no avail and now I am really stuck.

Any help would be most welcome!

Fig

**Comment by Gimcrack** [comment] 2019-04-25 22:40
I was having the same issue. It turned out that my install project had been bundling a newer version of a dependency (`ServiceStack.Text`) than what I had specified through NuGet. Deleting the offending versions of the package from my .nuget store fixed the issue.

**Comment by lefig** [comment] 2019-04-27 08:52
Thanks so much for the feedback. I will investigate this further too. Its so annoying!

**Comment by DaisyDave** [comment] 2019-05-04 16:08
I am having the same issue, to compound the problem this id my first experimentation with Redis. I have cleared everything from my nuget cache. It seems to work with a dotnetcore 2.2 console application. However any windows desktop application throws this exception. I have tried VS2017 (.net 4.7 and 4.6.2 applications) also VS2019 (.net 4.7.2).

VS2017 downloaded the source and the exception is being thrown on line 948 of CreateMultiplexer.cs:

`var task = muxer.ReconfigureAsync(true, false, logProxy, null, "connect");`

I am specifying a password my connection code is:

`ConfigurationOptions cfg = new ConfigurationOptions()
{
    EndPoints =
    {
        { "raspberrypi3", 6379 }
    },
    Password = "******"
};` 
`ConnectionMultiplexer connection = ConnectionMultiplexer.Connect(cfg);`

I'm not sure where to go from here.

**Comment by lefig** [comment] 2019-05-04 19:40
Snap. I am truly stuck.
I have investigated all the dependencies using tools like dependency walker and made sure they are correct. But the problem seems to be with the .net loader and reflection and triggered on that line you mention. 
Its perplexing...

**Comment by NickCraver** [comment] 2019-05-04 19:44
Things to try:
- Reference the `System.Runtime.CompilerServices.Unsafe` library directly as a `<PackageReference>` (so VS alerts it needs a binding and offers a one-click fix...sometimes it won't realize this transitively).
- If using `app.config`, remove all binding redirects and add a `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` property up top

This is a load errors and I really really really wish they had a wiki page explaining how to fix this because it can plague any library anyway if you step on one of the magical landmines.

**Comment by lefig** [comment] 2019-05-05 09:07
Thanks Nick. I really appreciate your help. This sounds like an outstanding suggestion. Must be worth a try!

**Comment by grisharav** [comment] 2019-05-12 20:35
Did anyone manage to resolve this? We are having the same issue and suggested things to try had no effect.

**Comment by lefig** [comment] 2019-05-14 20:24
No unfortunately. We are on 4.6 but tried 4.7.1 to no effect. I noticed that even if you force the correct dlls to load into process that the framework loader still throws the exception on the line mentioned above. This is seriously not funny now:)

**Comment by mgravell** [comment] 2019-05-14 20:56
Please see #1130, which includes the binding redirect and a workaround using 4.6-preview (the bug in Unsafe is fixed in 4.6, but it isn't released yet)

**Comment by DaisyDave** [comment] 2019-05-15 22:34
Thanks Mark that solved my issue. I installed System.Runtime.CompilerServices.Unsafe version 4.6.0-preview6.19259.10 from NuGet into my .NET Framework v4.6.1 project and that fixed that project.

**Comment by BCalpe** [comment] 2019-05-26 19:46
Hi

I'm getting the same error:
Could not load file or assembly System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0.
I'm building a .NET Framework 4.6.1 Class Library project that need to be uploaded to inRiver.

I tried adding the line to my csproj file but it didn't help
`<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.6.0-preview6.19259.10" />`

Do I need to remove the Reference to the older System.Runtime.CompilerServices.Unsafe ?
Any other step I may need to do before adding the above line to my csproj file?

Thanks

**Comment by lefig** [comment] 2019-05-27 22:10
> Thanks Mark that solved my issue. I installed System.Runtime.CompilerServices.Unsafe version 4.6.0-preview6.19259.10 from NuGet into my .NET Framework v4.6.1 project and that fixed that project.

Likewise, thank you Mark for all your help and patience. I'll give it a good try and will cross my fingers.

**Comment by BCalpe** [comment] 2019-05-28 07:29
After installing Stackexchange.Redis I have upgraded it to System.Runtime.CompilerServices.Unsafe version 4.6.0-preview6.19259.10.   After deploying to inRiver I still get the same error.

Do I need to change something else?

**Comment by lefig** [comment] 2019-05-29 19:07
Have you checked what dll/assembly is actually being loaded into memory? Using VS debug tools you can check the path and assembly version number.

**Comment by BCalpe** [comment] 2019-05-30 21:04
I solved it by downgrading to 4.5.1 and that helped. Unfortunately no other solution helped.

**Comment by kasilioglu** [comment] 2019-05-31 07:31
Not so sure to write to this issue but it seems related.
I upgraded to latest version and yes i got same problem with this assembly version.
Plus;
I also got an other error with System.Net.Http and required to add binding redirection.
To ensure its not me;  i just created a MVC+WebApi  solution in VS2017  and .Net version  4.6.1 and it fails at Web api help page complaining
**System.Net.Http.HttpMethod System.Web.Http.Description.ApiDescription.get_HttpMethod()**

Following bindingRedirection fixes;
 <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="B03F5F7F11D50A3A" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0"/>
      </dependentAssembly>

**Comment by hvbnet** [comment] 2019-06-02 04:40
I using .Net 4.7.2 and have same issue, It work fine in development mode but when publish have same issue. Unfortunately no other solution helped.

**Comment by lefig** [comment] 2019-06-04 22:58
There is a bug in VS concerning publish not actually "publishing" all dependencies for .net Core apps. I am not sure about .net Framework though. I hit that problem and found that some dependencies were actually missing from the release folder.

**Comment by yury-kozlov** [comment] 2019-06-13 14:30
Adding this redirect helped to solve the issue in asp.net web application project:
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.4.1" newVersion="4.0.4.1" />

**Comment by lefig** [comment] 2019-06-13 20:11
Much appreciated. Other users too who may encounter this bizarre problem will be able to try various potential fixes.

**Comment by hvbnet** [comment] 2019-06-16 05:05
> Adding this redirect helped to solve the issue in asp.net web application project:
> 
> ```
>         <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
>         <bindingRedirect oldVersion="0.0.0.0-4.0.4.1" newVersion="4.0.4.1" />
> ```

I already do it but Does not work this solution for me

**Comment by lefig** [comment] 2019-06-27 17:27
You may wish to try a long shot. If you still can't figure out where the old version is coming from, you can use the fuslogvw.exe application that ships with Visual Studio to get more information about the binding failures. Microsoft has information about this tool here. Note that you'll have to enable logging by setting the HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Fusion\EnableLog registry key to 1.

Just a thought mind

**Comment by katlimruiz** [comment] 2019-11-07 04:40
> Adding this redirect helped to solve the issue in asp.net web application project:
> 
> ```
>         <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" />
>         <bindingRedirect oldVersion="0.0.0.0-4.0.4.1" newVersion="4.0.4.1" />
> ```

This one worked for me even if the file in my bin folder said 4.6.26919.2

**Comment by lefig** [comment] 2019-11-08 21:24
Thanks for sharing

**Comment by JacksonHong** [comment] 2019-11-26 19:49
We ran into this issue after upgrading our service to .NET 4.7.2 and StackExchange.Redis NuGet to 2.0.601. After installing System.Runtime.CompilerService.Unsafe NuGet 4.6 this problem is resolved.

Our csproj file also has the following config.

`<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>`

**Comment by alnkrk** [comment] 2020-02-05 00:15
Using .Net 4..7.2 in a .Net web app with Redis windows service - I had same issue afer amending Redis "ConnectionMultiplexer.Connect" connection string to include 'password=...'.  

Solved by updating System.Runtime.CompilerService.Unsafe via VS NuGet Package Manager to "latest stable 4.7.0", which showed property version in VS as 4.0.6.0.  

Upgrading that way added the following to the web configs - 

      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0" />
      </dependentAssembly>

**Comment by Tridy** [comment] 2020-03-04 15:57
Got stuck as well:

.NET 4.7.2

reference:
```
<PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="4.7.0" />
<PackageReference Include="StackExchange.Redis" Version="2.0.601" />
```

redirect:
```
<dependentAssembly>
    <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
    <bindingRedirect oldVersion="0.0.0.0-4.7.0.0" newVersion="4.7.0.0" />
</dependentAssembly>
```

when running:
`ConnectionMultiplexer.Connect(...)`

I get the exception:
```
System.AggregateException
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.7.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Inner Exception 2:
FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```
The inner exception 1 says that it cannot even find 4.7.0.0 which I have a reference to.
The inner exception 2 says it needs 4.0.4.1 that I am trying to redirect from 4.7.0.0

Any ideas?
Thanks!

**Comment by lefig** [comment] 2020-03-08 11:31
How frustrating.

It could be worth taking a step back and looking at modules loaded into the address space. Check their names and paths. Then go to disk and check file properties for version info.

Then look at your csproj file as mentioned above. 

Check version numbers. 

See also if you get trace debug output on assembly loading as this may provide some clues..

**Comment by mgravell** [comment] 2020-03-09 07:25
We're using net472 @Tridy , so I know it *can* work! The assembly binding we have is:

``` xml
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0"/>
      </dependentAssembly>
```

**Comment by NickCraver** [comment] 2020-03-14 12:24
For anyone else hitting this, these issues prompted me to write up a more complete story on why this happens and what the options for a fix are. I hope this helps anyone hitting this issue resolve it: https://nickcraver.com/blog/2020/02/11/binding-redirects/

**Closed** 2020-03-14 15:58 UTC

**Comment by VenkateshamAitha** [comment] 2020-03-31 02:22
Hey Nick,
i followed your link https://nickcraver.com/blog/2020/02/11/binding-redirects/ 
i am using .NET Framework and i tried all the solutions mentioned in above document but getting below error.
**Error:
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)**

my app.config:
<dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0" />
      </dependentAssembly>

**Comment by VenkateshamAitha** [comment] 2020-03-31 02:23
my app.config:
<dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0" />
      </dependentAssembly>

**Comment by itsho** [comment] 2020-05-07 09:42
@VenkateshamAitha can you try with the latest version of `System.Runtime.CompilerServices.Unsafe` - 4.7.1

**Comment by Dlovan-B-M** [comment] 2020-08-11 08:39
still have problem with .net framework 4.6.1 , and System.Runtime.CompilerServices.Unsafe version 4.7.1

**Comment by aspnerd** [comment] 2020-08-13 22:52
I'm having this issue now in the latest version of vs and 4.8

**Comment by mgravell** [comment] 2020-08-13 23:17
Yes, "Unsafe" is one of a known group of libraries with a binding redirect
problem. You can usually fix it by adding manual assembly binding redirects
(Nick has a great post on this here:
https://nickcraver.com/blog/2020/02/11/binding-redirects/), but honestly:
if you want this to go away - move to .NET Core.

I did nerd-snipe David Kean with these issues a while back, and he had an
interest in improving things, but I don't know the state of that. I'll ping
him again.

Marc

**Comment by aspnerd** [comment] 2020-08-13 23:22
@mgravell I'm trying to move to core, but I can't have this break on me now!

**Comment by mgravell** [comment] 2020-08-14 12:53
@aspnerd emphasis: the problem here isn't one of our creation - it is a problem in the build tools, where it fails to automatically generate the correct assembly binding redirects. The relevant MS folks are aware of this, and they have hinted that they might fix it, but: the problem is in the MS build tools, not our library - so we can't fix it. The workaround for now is to manually add the correct assembly binding redirect, which Nick's blog post tells you how to do.

**Comment by MrTuyen** [comment] 2021-01-13 02:14
I was just down grade the version in Nutget packge then boom it works

**Comment by nikhat5311** [comment] 2022-10-08 11:25
<dependentAssembly>
				<assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
			</dependentAssembly>

**Comment by QuraishiSaif** [comment] 2022-10-08 11:28
<dependentAssembly>
				<assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
			</dependentAssembly>

**Comment by Anton-codeWORLD** [comment] 2023-07-24 14:58
Thank you very much, it helped a lot👍

**Comment by Ava205** [comment] 2025-01-31 03:32
@mgravell https://stackdev.space/questions/collaborative-session-held-between-two-hosting-servers

**Comment by mgravell** [comment] 2025-01-31 09:59
@Ava205  I've deleted your comment because it doesn't relate to this issue, and doesn't seem to relate to SE.Redis; please don't do that
