### ISSUE TITLE
Inconsistent StringGet behavior with Azure Premium Cluster

### ISSUE THREAD

**Issue by ktrojnfm** [StackExchange/StackExchange.Redis#1062] opened 2019-02-19 01:18 UTC
We have an app we are looking to move to Azure Redis and in our testing with our Premium cluster, we are seeing inconsistent behavior from the StringGet() method.

If I open a connection and attempt a StringGet() on a key, it may or may not return. If it doesn't return, I get an error indicating the key has moved.  

Key has MOVED from Endpoint 10.13.104.140:15007 and hashslot 12862
 but CommandFlags.NoRedirect was specified - redirect not followed for GET prod:
26709311. IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=0,Free=2047,Min
=2,Max=2047), Local-CPU: n/a

Closing an reopening the connection may result in the same error or may result in the key being successfully retrieved.  The client appears to be ignoring the cluster and only connecting to one node.

The code being used has been reduced to a very simple example that's experiencing this problem consistently. In case it's relevant, we are using .Net 4.6.1

Note that the code explicitly passes CommandFlags.None - originally, nothing was passed, but I changed it to None in an effort to see if that made any difference.

            var options = ConfigurationOptions.Parse(
                "{hostname}:6380,password={password},ssl=True,abortConnect=False,syncTimeout=10000,connectTimeout=60000");

            var mux = ConnectionMultiplexer.Connect(options);

foreach (var key in keys)
            {
                var timer = new Stopwatch();
                var msg = string.Empty;

                timer.Start();

                try
                {
                    var flags = CommandFlags.None;

                    var db = mux.GetDatabase(0);
                    var val = db.StringGet(key, flags);
                }
                catch (Exception e)
                {
                    msg = e.Message;
                }

                timer.Stop();

                Console.WriteLine(key + " " + msg + " " + timer.ElapsedMilliseconds);
            }

**Comment by mgravell** [comment] 2019-02-19 09:01
This is very curious; to explain what is happening, as you would expect, it only does this if the `CommandFlags.NoRedirect` flag is set; if *you* didn't add it, then *the library* must have; there are two scenarios I'm aware of where we do this:

- we add that when using transactions (`MULTI`/`EXEC`); transactions need to stay on one server
- we add that when we're *re-sending* something because it has *already* reported `MOVED` once

The fact that you're using `StringGet` (rather than `StringGetAsync`) tells me that this can't be the first scenario, as we don't expose synchronous calls inside transactions. So, it sounds to *me* like the cluster has forwarded you twice. I don't know why this would be. I wonder whether this is something specific to Azure Premium, but it isn't something that we *expect* to see, as the cluster key map at the server is expected to be correct (even if the library hasn't refreshed yet), so the *server* shouldn't usually be issuing `MOVED` or `ASK` to another incorrect server.

I'll double-check against our own azure test nodes here (although since our azure cluster node is provided by Microsoft, I don't know the specific tier/etc to know if it is identical).

Does this happen consistently? or is it only happening periodically / against a specific set of nodes? Does it happen on a dev/test cluster, for example? Obviously it would be easier for me to investigate with direct access to the specific cluster to test against, but I **actively do not want** access to anyone's production tier servers. If it is happening on a burnable dev/test cluster, then we might have more options there.

**Comment by ktrojnfm** [comment] 2019-02-19 11:36
I'm able to recreate this issue every time I issue commands against this cluster. It's our production cluster, so I cannot grant you access to it, but if you have things you'd like me to try in the code, I'm happy to do so.

**Comment by mgravell** [comment] 2019-02-19 13:11
> It's our production cluster, so I cannot grant you access to it,

as per above, I would have rejected it even if offered (see "I **actively do not want** access to anyone's production tier); if you have redis-cli access (which you possibly don't as it would require the non-TLS port to be open), you could tri:

```
redis-cli -h 10.13.104.140 -p 15007
get prod:26709311
```

(or whatever the actual key is) and see what happens; if you're careful, you can also do this via a telnet client (and possibly ssh, which might avoid the TLS issue), with the advantage that it *won't* follow the redirects, which is what we want to see. For example, if I issue the above, I'd expect to see:

```
-MOVED {...}
```

or

```
-ASK {...}
```

then I would follow the directions from the `MOVED`/`ASK`, and retry there - see what *that* server says.

**Comment by ktrojnfm** [comment] 2019-02-19 13:20
Azure provides a console that's relatively equivalent to redis-cli

> get prod:26709311
> (error) MOVED 12862 10.13.104.140:13007 (shard 3)

If I then switch to the referenced shard (3 for the above key) and reissue the command, I then get the expected data.

**Comment by mgravell** [comment] 2019-02-19 14:23
k; this is odd, then; it doesn't *look* like a double-MOVED; let me see if I can repro against our test cluster - something is definitely odd here

**Comment by ktrojnfm** [comment] 2019-02-19 18:46
Through some trial and error, I believe I've identified the source of the issue. It appears that Azure Redis wants ports in the 15000-15999 range open; once we opened those ports, it started working. Once I identified this, with knowledge of port numbers I eventually found a Microsoft document that identifies these ports.

While the error messages displayed are misleading, I'm confident we've identified the root cause of this issue.

**Comment by mgravell** [comment] 2019-02-19 21:01
Ok, that's useful - even if you've resolved the problem, we should improve
the error message in this scenario!

**Comment by NickCraver** [comment] 2021-05-23 13:53
@deepakverma Are these port ranged hard coded on the Azure side? If so, seems like we could make the error message more useful in getting to the cause quicker there, or at the least: we can add more generic help informing it may be a port issue.

**Comment by Sandeepgowda1981** [comment] 2022-03-30 09:06
"Key has MOVED from Endpoint Unspecified/test1-0001-001.test1.xhqxoc.cache.amazonaws.com:6379 and hashslot 3232 but CommandFlags.NoRedirect was specified - redirect not followed for EVAL. IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=32766,Min=2,Max=32767), Local-CPU: n/a"

We are facing the same issue in AWS when cluster mode & encryption is enabled. Is there any fix for this?

**Comment by NickCraver** [comment] 2023-02-09 16:04
@Sandeepgowda1981 apologies for the very long delay here - we have made adjustments in latest to handle this MOVED case better and re-evaluate cluster topology ASAP, that'll minimize there and get back in action ASAP.

Closing this to tidy up but happy to reopen if that leaves questions.

**Closed by NickCraver** 2023-02-09 16:04 UTC
Labels: 📃 documentation, ☁️ platform:Azure
