### ISSUE TITLE
Document Timeout error message details

### ISSUE THREAD

**Issue by Plasma** [StackExchange/StackExchange.Redis#895] opened 2018-07-24 06:38 UTC
Hello,

When receiving errors like this:

```Timeout performing DEL, inst: 1, mgr: Inactive, err: never, queue: 457, qu: 0, qs: 457, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0```

Its hard to understand what all the error codes are. Is it possible to document the meaning of qu, qs, qc, etc? I've not been able to find a complete list.

Thank you

**Comment by mgravell** [comment] 2018-07-24 07:05
Most of them disappear in 2.0, but: 457 items in the queue of sent items
awaiting replies (qs), *tons* of data on the inbound socket (in), and no
active reader (ar).

Basically, the reader failed to wake up. The code that relates to this has
changed completely in 2.0, and hopefully this problem should not be
possible.

**Comment by Plasma** [comment] 2018-07-24 11:17
Thanks Marc. I've looked through our timeout history and a large amount have a similar symptom, where ``in`` is non-zero (often ``65536``) and ``ar`` is zero. There are a few others, but will try this one first.

I'm prepared to add additional logging where necessary to be included with the next timeout exception I receive. See https://github.com/StackExchange/StackExchange.Redis/compare/master...Plasma:debug-timeout-errors?expand=1 (WIP)

I'm suspicious that the reader thread as you said has just died or got stuck, but it does recover some how. Can you think of anything else I should include in the next timeout message to help pin down a cause?

Thank you

**Comment by mgravell** [comment] 2018-07-24 12:20
The cause here is a library fail, so: mea culpa.

Note: if you're using a TLS (SSL) connection (usually: a cloud provider such as Azure), then note that "ar" doesn't apply, and it is correct for it to be zero, in which case this was probably a stolen thread.

I haven't identified the specific cause there, but I recognize it is a recurring problem, which is just one of the many motivating factors behind 2.0, which *completely overhauls* the network code. There is no more concept of "ar" - to be awake or asleep. And for the TLS code : we've overhauled the callback code, so you shouldn't be able to steal the thread. Actually, there's only one code path in 2.0, rather than 2 in 1.*

At this point, there's no reasonable way that we're going to identify and resolve this in 1.*, so - and I hope you don't mind here, but - I'm going to close this as "fixed in 2.0": https://github.com/StackExchange/StackExchange.Redis/issues/871

**Closed by mgravell** 2018-07-24 12:20 UTC

**Comment by Plasma** [comment] 2018-07-25 03:10
Hey Marc,

Understood. I'm looking forward to the new 2.0 release, but I'm also open, if you're keen, to work on adding some debug logic to try and track down this issue, just need a few pointers and I'll go from there and would be happy to report back any findings to merge back in.

And yes, we're actually using SSL Azure Redis.

Thank you,
Andrew

**Comment by NickCraver** [comment] 2018-07-25 10:36
@Plasma I'm not sure conveyed how much different v2 is. It's like debugging a fuel problem in an engine for next year's car model when the next model is an electric. There's no chance of a fix being merged in because the network code is *completely* rewritten. But 2.0 is close, we're in alpha on NuGet now and hunting down the last known protocol bug now. Hang on, we'll have goodies ready to go soon :)

**Comment by mgravell** [comment] 2018-07-25 11:04
> to work on adding some debug logic to try and track down this issue, just need a few pointers

this isn't a "few pointers" thing; it is a library bug that requires significant internal rework to fix; we've *done* that work: it is called 2.0 and, as Nick says, we're hoping to make it RTM very soon

**Comment by Plasma** [comment] 2018-07-25 23:56
No worries, thank you.
