### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException

### ISSUE THREAD

**Issue by Iamcerba** [StackExchange/StackExchange.Redis#760] opened 2017-12-21 14:06 UTC
I'm using **1.2.6** version of the package and often see the following exceptions in logs while connecting to **Azure RedisCaches**. Any ideas what may cause such errors?

> **StackExchange.Redis.RedisTimeoutException**: Timeout performing EXISTS controllers.usercontroller-getusersscroll-userIds=<guid>&userIds=<guid>&skip=0&take=2&status=Active, Inactive&orderBy=0&sortDirection=Desc:application/json; charset=utf-8:Bearer <token>, inst: 0, mgr: Inactive, err: never, queue: 1769, qu: 1769, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: <...>, serverEndpoint: Unspecified/<...>.redis.cache.windows.net:6380, keyHashSlot: 2692, IOCP: (Busy=0,Free=1000,Min=250,Max=1000), WORKER: (Busy=1,Free=32766,Min=250,Max=32767)

**Comment by vipwangtian** [comment] 2017-12-30 02:12
I had the same problem
StackExchange.Redis.RedisTimeoutException: Timeout performing EVAL, inst: 105, mgr: ExecuteSelect, err: never, queue: 28, qu: 2, qs: 26, qc: 0, wr: 1, wq: 1, in: 10, ar: 0, clientName: MANGOSQLSERVER, serverEndpoint: Unspecified/171.redis.517.cn:6381, keyHashSlot: 16346, IOCP: (Busy=0,Free=3200,Min=64,Max=3200), WORKER: (Busy=137,Free=3063,Min=512,Max=3200) (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by tocalai** [comment] 2018-03-02 10:07
I used version 1.2.6 also encountered the same issue:
StackExchange.Redis.RedisTimeoutException
Timeout performing RPUSH xxxx:xxxx:xxxx:ParentJob:9ec051d6-48fa-4a46-9ff1-e14f0c26ce0c:Site:1, inst: 303, mgr: ExecuteSelect, err: never, 
queue: 1, qu: 1, qs: 0, qc: 0, wr: 0, wq: 1, in: 0, ar: 0, 
clientName: xxxx-PC, serverEndpoint: Unspecified/localhost:6379, 
keyHashSlot: 4935, IOCP: (Busy=0,Free=1000,Min=100,Max=1000), WORKER: (Busy=2,Free=8189,Min=100,Max=8191) 
(Please take a look at this article for some common client-side issues that can cause timeouts:
 http://stackexchange.github.io/StackExchange.Redis/Timeouts)

Looks into the article for more help, seems that we do not hit the limit of Busy > Min scenario
The exception not happened every time, but usually occurred in amount of data(> 10000 records) under the multi-thread condition for access the Redis server.

Any suggestion for this?

**Comment by vitali-shcharbin-epam** [comment] 2018-03-29 15:21
Similar issue with 1.2.6 version, that happens from time to time:
```
StackExchange.Redis.RedisTimeoutException :
Timeout performing PUBLISH xxxxxxxxxxxxx, inst: 1, mgr: ExecuteSelect, err: never, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: XXXX, serverEndpoint: IP:6379,
IOCP: (Busy=1,Free=999,Min=6,Max=1000),
WORKER: (Busy=1,Free=32766,Min=6,Max=32767)
(Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
```

**Comment by jatarga** [comment] 2018-03-31 11:05
I also encounter same problem in .NET Core 2:

> Timeout performing HGETALL xxxxxxxx, inst: 1, queue: 6, qu: 0, qs: 6, qc: 0, wr: 0, wq: 0, in: 341, ar: 0, clientName: , serverEndpoint: Unspecified/localhost:6379, keyHashSlot: 11105 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)

**Comment by georgechr** [comment] 2018-04-05 08:12
Same issue, with version 1.2.6 this happens from time to time

**Comment by EminemJK** [comment] 2018-04-08 07:53
I also encounter same problem

**Comment by aronsimpletix** [comment] 2018-04-08 17:02
For the past 18 hrs I have been getting this error like too.
I am using 1.2.4
About to try 1.2.6 now

**Comment by JonCole** [comment] 2018-04-18 16:28
A RedisTimeoutException being thrown does not necessarily constitute a bug in StackExchange.Redis nor does it necessarily mean that there is a bug in the server either.  More often than not, it means that some computing limitation on the client or the server has been hit.  Any of the issues outlined in the following links cause timeouts and they are all things that the application developer has to fix (for example: by scaling the client or server to a more powerful VM):

  [Diagnosing Client Issues](https://gist.github.com/JonCole/db0e90bedeb3fc4823c2#file-diagnoserediserrors-clientside-md)
  [Diagnosing Server Issues](https://gist.github.com/JonCole/9225f783a40564c9879d#file-diagnoserediserrors-serverside-md)

**Comment by zsy619** [comment] 2018-04-25 14:02
StackExchange.Redis.RedisTimeoutException: Timeout performing GETBIT client:registered_accounts, inst: 35, queue: 1532, qu: 0, qs: 1532, qc: 0, wr: 0, wq: 0, in: 6474, ar: 0, clientName: , serverEndpoint: 192.168.1.8:6379, keyHashSlot: 2621 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
   at StackExchange.Redis.RedisDatabase.StringGetBit(RedisKey key, Int64 offset, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1675
   at TxSms.Redis.RedisHelper.BitGet(RedisKey key, Int64 offset) in D:\腾信集团\TxSms.Common\src\TxSms.Redis\RedisHelper.cs:line 943
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at TxSms.API.Services.SendMessage.<Execute>d__5.MoveNext() in D:\腾信集团\TxSms.MP\src\TxSms.API\Services\SendMessage.cs:line 145
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TxSms.API.Controllers.GroupMsgController.<Send>d__1.MoveNext() in D:\腾信集团\TxSms.MP\src\TxSms.API\Controllers\GroupMsgController.cs:line 53

**Comment by zousq19910623** [comment] 2018-05-18 09:10
so ,is this problem have been solved??

**Comment by eltiare** [comment] 2018-05-30 22:09
I get this error when I'm debugging. It's incredibly annoying and wastes a lot of time.

**Comment by JonCole** [comment] 2018-06-01 19:10
Not all timeouts are caused by a single root issue. In this thread (e.g. the first timeout posted originally), I would say that the real issue is the "qu: 1769" entry in the timeout error message.  This seems to indicate that the writer thread which takes requests and pushes them onto the network is dead.  The other timeout error messages posted by others on this issue are likely caused by some other issue.

I have seen very few customers run into this "writer thread broken" issue, but it does happen.  The workaround until the root cause is figured out would be to re-create the ConnectionMultiplexer object.

**Comment by eltiare** [comment] 2018-06-01 19:12
I think it's because the debugger suspends execution of everything until I continue on. If I'm studying the current state for a minute or so and then continue, the error happens. If it's only a few seconds it does not.

**Comment by JonCole** [comment] 2018-06-01 19:26
@eltiare, that is likely true for your specific case, but I don't think that is what this original issue was filed about.  For debugger case, your only option that I can think of is to use a longer timeout when debugging.

**Comment by NickCraver** [comment] 2018-06-01 22:15
We could possibly ignore all timeouts if `Debugger.IsAttached`, but...that has problems on the flip side of never seeing a timeout while debugging. I'm not sure that's a good way to go. To be fair, this happens for pretty much anything. For example, if you debug while a SQL query runs, you'll see the same timeout behavior.

**Comment by kierenj** [comment] 2018-06-02 07:39
We get this too - I agree with Nick on it though. We just increase the timeout to a lot higher on our dev configs

**Comment by NickCraver** [comment] 2018-06-03 00:00
Got some Twitter feedback here: let's add more text to the error message if `Debugger.IsAttached` at lest, to help people out. It's not awesome, but it's better than nothing.

**Comment by eltiare** [comment] 2018-06-03 15:06
Thanks for the tip to increase the timeout. Saved me a lot of hair pulling.

**Comment by glassmountains** [comment] 2018-06-05 15:16
I have the same problem, but I'm fairly new to programming. Where can I increase the timeout? I already had a lot of hair pulling. Thanks!

**Comment by JonCole** [comment] 2018-06-05 16:41
@glassmountains Take a look at [ConfigurationOptions.SyncTimeout](https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Configuration.md#configuration-options)

**Comment by trimbleAdam** [comment] 2018-06-14 20:42
I'm trying to make use of this lib within a .NET core 2.1 app, and the stack dump doesn't make ANY sense, as the app is running in a Debian container.

What is the business with this hard-coded c:\code\ fooery? Do I need to manually compile a package for the linux-x64 RID?

Any advice is greatly appreciated.

**Comment by mgravell** [comment] 2018-06-15 14:04
Path information in a pdb relates to the build machine, not the executing
machine. This is normal. What is the actual stack trace?

**Comment by mgravell** [comment] 2018-06-28 21:10
Closing; please see: https://github.com/StackExchange/StackExchange.Redis/issues/871

**Closed by mgravell** 2018-06-28 21:10 UTC
