### ISSUE TITLE
Memory leak, Performance and dependencies Issue on version 2

### ISSUE THREAD

**Issue by yoonyc83** [StackExchange/StackExchange.Redis#1078] opened 2019-03-06 00:02 UTC
Hi there,

Target of my project is .Net Framework 4.6.2.
When I try to update to StackExchange.Redis v2 from v1.2.6, there are 3 things that I want to solve.

1. Dependency
- Update brings dependent assemblies that related to .Net Core, so there's a redirect issue.
- But target for my project is just on .Net Framework 4.6.2 and I don't want to distribute these assemblies.

2. Memory leak
- After update I found memory leak happened.
- When rollback to older version, the problem was disappeared.

3. Performance
- After update same logic was twice slower.

I'd like to update v2 because v1.2.6 has async issues and I'm usually using async APIs (include transaction).

**Comment by mgravell** [comment] 2019-03-06 08:24
1. which dependencies, specifically? so I can evaluate
2. can I take a guess that the leak here was `RawResult[]`? if so: that's fixed next release via https://github.com/StackExchange/StackExchange.Redis/pull/1075
3.  comparing which versions? do you have an example? we're aware of some recent regressions, and the next release addresses a lot of these

**Comment by dme-development** [comment] 2019-04-01 05:33
@mgravell : very happy to see you found the RawResult[] issue. Do you have an estimate on when this will be released?

**Comment by mgravell** [comment] 2019-04-02 15:20
@dme-development the `RawResult[]` changes are in `2.0.571`, however: we're hoping to release an update imminently re a race condition that is causing timeouts in some scenarios, so I'd hold off until then - should be in the next day or two.

Re the performance problems (@yoonyc83) - it is possible that this is related to the scenario I've been looking at. Although we've also addressed a range of other performance issues in 571. Again, though: I'd hold off until next.

Because all of these things are now basically complete, I'm going to close this one down.

**Closed by mgravell** 2019-04-02 15:20 UTC
