### ISSUE TITLE
dotNet6 initial connection timeouts?

### ISSUE THREAD

**Issue by sabiland** [StackExchange/StackExchange.Redis#1905] opened 2021-11-10 07:20 UTC
Has anyone noticed any issues after upgrading app to dotNet6?

It seems that I get random initial connection timeouts after upgrading to dotNet6. And auto-reconnection never happens despite ConnectRetry = 20, and ReconnectRetryPolicy = linear 5000.

**Comment by TimLovellSmith** [comment] 2021-11-23 18:51
@sabiland I have heard anecdotally that StackExchange.Redis doesn't work on .Net 6 in a web app, and that downgrading to .Net 5 fixes it. I don't know the actual underlying issue. If you're having this issue, sharing more info on the repro environment (.Net version, SE.Redis version) might help someone address it.

**Comment by sabiland** [comment] 2021-11-24 08:04
Actually everything works perfectly OK on our `Net Core 6` (`DotNet6`) web app/api with latest StackExchangeRedis client `<PackageReference Include="StackExchange.Redis" Version="2.2.88" />` just that I **sometimes** see initial connection timeout. Very **rarely** and quite **randomly**.

**Comment by wojciechrak** [comment] 2021-12-02 06:52
I can confirm this, we are experiencing connection timeout issues after upgrading our app to .NET 6.

StackExchange.Redis 2.2.79
We have Sentinel config, as well as standalone Redis instance and issue is on both.
Happens every couple of minutes, and our app averages 150 requests/min

```
StackExchange.Redis.RedisTimeoutException: Timeout performing GET (5000ms), next: SETEX __OBSCURED__, inst: 45, qu: 0, qs: 9, aw: False, rs: ReadAsync, ws: Idle, in: 81, in-pipe: 0, out-pipe: 0, serverEndpoint: 10.43.3.25:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: my-client, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=7,Free=32760,Min=1,Max=32767), v: 2.2.79.4591 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2885
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 2432
   // obscured
Redis-Message: GET __OBSCURED__;
Redis-Message-Next: SETEX __OBSCURED__;
Redis-OpsSinceLastHeartbeat: 45;
Redis-Queue-Awaiting-Write: 0;
Redis-Queue-Awaiting-Response: 9;
Redis-Active-Writer: False;
Redis-Read-State: ReadAsync;
Redis-Write-State: Idle;
Redis-Inbound-Bytes: 81;
Redis-Inbound-Pipe-Bytes: 0;
Redis-Outbound-Pipe-Bytes: 0;
Redis-Server-Endpoint: 10.43.3.25:6379;
Redis-Multiplexer-Connects: 1/1/0;
Redis-Manager: 10 of 10 available;
Redis-Client-Name: my-client;
Redis-ThreadPool-IO-Completion: (Busy=0,Free=1000,Min=1,Max=1000);
Redis-ThreadPool-Workers: (Busy=7,Free=32760,Min=1,Max=32767);
Redis-Busy-Workers: 7;
Redis-Version: 2.2.79.4591;
redis-command: GET __OBSCURED__;
request-sent-status: Sent;
redis-server: 10.43.3.25:6379
```

**Comment by sabiland** [comment] 2021-12-02 07:11
I am must add this, that _if_ initial connection (app start/recycle) to Redis Sentinel(s) **succeeds**, then everything seems to be OK during app life duration.

**Comment by TimLovellSmith** [comment] 2021-12-02 17:31
>WORKER: (Busy=7,Free=32760,Min=1,Max=32767

You should increase the min worker threads. StackExchange.Redis doesn't work very well if you leave it at default minimums, _or if you ever exceed the minimum_, so pick a bigger number than you expect to ever need.

https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.setminthreads?view=net-6.0

**Comment by sabiland** [comment] 2021-12-03 09:44
Aaa, cool info. Will try this.

**Comment by NickCraver** [comment] 2021-12-12 15:32
> @sabiland I have heard anecdotally that StackExchange.Redis doesn't work on .Net 6 in a web app, and that downgrading to .Net 5 fixes it. I don't know the actual underlying issue. If you're having this issue, sharing more info on the repro environment (.Net version, SE.Redis version) might help someone address it.

FWIW, we found the source of this nasty rumor :) See https://github.com/dotnet/aspnetcore/issues/38715 for details.

On this issue, I wouldn't expect 7 busy to be a huge issue, but it may be taxed. @sabiland did changing threads make any difference here? We're seeing in tiny VM environments the default 10 threads for SocketManager may be not ideal and are considering changing the default to be the built-in threadpool with .NET 6.0+ environments. You could try what we're considering defaulting like this:
```cs
var config = ConfigurationOptions.Parse("localhost:6379");
config.SocketManager = SocketManager.ThreadPool;
var conn = ConnectionMultiplexer.Connect(config);
```
or inline:
```cs
var conn = ConnectionMultiplexer.Connect("localhost:6379", options => options.SocketManager = SocketManager.ThreadPool);
```

If threads didn't work, or you're willing to try this alternative for us to help make better decisions on defaults, I's appreciate it either way :)

**Comment by sabiland** [comment] 2022-01-14 09:55
After testing new values `minWorker = 20` and `minIOC = 20` for quite some time we haven't see any issues with connections (either on app start or otherwise) exclusively to Sentinels with our `DotNet6` web app! I am still not sure if this was the problem.

**Comment by NickCraver** [comment] 2022-02-20 23:07
Since the initial issue is resolved and the caching lib fix has been released, closing this out to cleanup.

**Closed by NickCraver** 2022-02-20 23:07 UTC
Labels: area:connection
