### ISSUE TITLE
Weird/Slow behavior on after connection to Redis is restored

### ISSUE THREAD

**Issue by pascalcmd** [StackExchange/StackExchange.Redis#1050] opened 2019-01-28 04:03 UTC
Hi Marc,

I am having a weird behavior about the re-subscribtion in case of connection issues to Redis.

My test is pretty simple, after connecting to Redis, I am subscribing to a channel. Then I publish some messages and I can see that those messages have been received on the subscriber and the publisher also returned me a value of 1 (for 1 subscriber).

Then I restart Redis and the ConnectionMultiplexer fires well the events ConnectionFailed and ConnectionRestored. Just after the connection is restored, I publish a message, but nothing is happening on the Subscriber's callback/action but my publisher still return a value of 1. After one minute or so, I publish another message and this time the Publisher return me a value of 2 and the Subscriber's callback/action is fire once only.

I had tried also with a simple ping just after ConnectionRestored and it failed.

I am using StackExchange.Redis V2.0.519.

Is there anything I am missing while calling ConnectionMultiplexer.Connect(ConnectionString)? The connection string is straight forward without any options

**Comment by NickCraver** [comment] 2020-03-14 18:10
Some glitches were fixed between 2.0.519 and 2.0.601, but some additional ones are in progress for 2.1.x. Overall, this is a duplicate of #1110 which is affected by #1120 (which should be fixed by #1374). Closing this just to combine issues down but a fix is on the way!

**Closed by NickCraver** 2020-03-14 18:10 UTC
