### ISSUE TITLE
.NET 4.0 version in Nuget can not be compiled

### ISSUE THREAD

**Issue by JeffreySu** [StackExchange/StackExchange.Redis#371] opened 2016-03-12 08:11 UTC
error:
# (Chinese)

严重性   代码  说明  项目  文件  行
警告      未能解析主引用“StackExchange.Redis, Version=1.0.316.0, Culture=neutral, processorArchitecture=MSIL”，因为它对框架程序集“System.Runtime, Version=2.6.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”有间接依赖关系，而在当前目标框架中未能解析该程序集。“.NETFramework,Version=v4.0”。若要解决此问题，请移除引用“StackExchange.Redis, Version=1.0.316.0, Culture=neutral, processorArchitecture=MSIL”，或将应用程序的目标重新指向包含“System.Runtime, Version=2.6.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”的框架版本。 Senparc.Weixin.Cache.Redis  
警告      未能解析主引用“StackExchange.Redis, Version=1.0.316.0, Culture=neutral, processorArchitecture=MSIL”，因为它对框架程序集“System.Threading.Tasks, Version=2.6.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”有间接依赖关系，而在当前目标框架中未能解析该程序集。“.NETFramework,Version=v4.0”。若要解决此问题，请移除引用“StackExchange.Redis, Version=1.0.316.0, Culture=neutral, processorArchitecture=MSIL”，或将应用程序的目标重新指向包含“System.Threading.Tasks, Version=2.6.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a”的框架版本。 Senparc.Weixin.Cache.Redis      
# (Transtlated)

Warning failed to parse the main reference "StackExchange. Redis, Version = 1.0.316.0, Culture = neutral, processorArchitecture = MSIL", because it is the framework assemblies "System. The Runtime, Version = 2.6.10.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a" indirect dependencies, and in the frame of the current target failed to resolve the assembly.". NETFramework, Version = v4.0 ".To solve this problem, please remove the reference "StackExchange. Redis, Version = 1.0.316.0, Culture = neutral, processorArchitecture = MSIL", or the goal of the application to include "System. The Runtime, Version = 2.6.10.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a" framework Version.Senparc. Weixin. Cache. Redis
Warning failed to parse the main reference "StackExchange. Redis, Version = 1.0.316.0, Culture = neutral, processorArchitecture = MSIL", because it is the framework assemblies "System. The Threading. Tasks, Version = 2.6.10.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a" indirect dependencies, and in the frame of the current target failed to resolve the assembly.". NETFramework, Version = v4.0 ".To solve this problem, please remove the reference "StackExchange. Redis, Version = 1.0.316.0, Culture = neutral, processorArchitecture = MSIL", or the goal of the application to include "System. The Threading. Tasks, Version = 2.6.10.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a" framework Version.Senparc. Weixin. Cache. Redis

**Comment by JeffreySu** [comment] 2016-03-12 08:11
The project is .NET 4.0

**Comment by mgravell** [comment] 2016-03-12 09:54
What compiler / IDE are you using in this example? (So I can try to
reproduce it)

**Comment by shzy2012** [comment] 2016-03-30 03:45
解决方法：  https://github.com/StackExchange/StackExchange.Redis/issues/66   
需要换成StackExchange.Redis -Version 1.0.488

**Comment by JeffreySu** [comment] 2016-09-28 15:41
VS 2015, default complier.

**Comment by mgravell** [comment] 2016-09-28 18:43
Have you tried with 605? If so: what exactly do you see? It should just
work...

**Comment by NickCraver** [comment] 2016-11-20 23:25
Closing this out since I have other reports of this working correctly since the recent ref fixes.

**Closed by NickCraver** 2016-11-20 23:25 UTC
Labels: needs-info
