### ISSUE TITLE
IServer.Time();

### ISSUE THREAD

**Issue by Tzott** [StackExchange/StackExchange.Redis#1058] opened 2019-02-12 03:24 UTC
The return time of the time command to the current server is 8 hours different from the server time.

**Comment by Tzott** [comment] 2019-02-12 03:31
It's like a time zone problem.

**Comment by mgravell** [comment] 2019-02-12 07:48
Dammit, that's annoying and problematic. There are times when it is hugely
inconvenient to develop in a GMT area - timezone problems can whizz past
you! I'll see what I can find out.

**Comment by mgravell** [comment] 2019-02-13 08:35
Can you check your server settings? We've spoken to antirez, who has confirmed that the time reported is UTC; our code treats it as UTC. Is it possible that either your server or client has their time incorrect? i.e. instead of being in the correct timezone, they've been set in the wrong time with a UTC shift?

**Comment by mgravell** [comment] 2019-02-13 08:37
Perhaps also: can you provide an example that shows the time being reported incorrectly? It *is* possible that you just need a `.ToLocalTime()` here!

**Comment by Tzott** [comment] 2019-02-14 07:29
My sercer time zone configuration is UTC+8.

The `IServer.Time().Kind` is `DateTimeKind.Utc`.  

But we used to use local time, as `DateTime.Now.Kind` is `Local`.

That's why I always thought there was an eight-hour gap in time at first.

As you said, I just need to use `.ToLocalTime()`, I'll get the right time.

**Comment by mgravell** [comment] 2019-02-14 08:27
so: what I'll do is convert this into a documentation issue, to make it clear in the intellisense that the time reported is in UTC, and to call `ToLocalTime()` if the caller wants local time. I think that's the best thing to do here.

**Comment by Tzott** [comment] 2019-02-14 09:36
I also think so.

**Comment by MZar2019** [comment] 2019-09-24 23:48
Using StackExchange.Redis 2.0.601, IServer.Time() and IServer.TimeAsync both return the Utc time from the server, however, the DateTime.Kind for TimeAsync() is **_Local, which is incorrect_**, while DateTime.Kind for Time() is Utc, which is correct.

**Comment by mgravell** [comment] 2019-09-24 23:56
They both use the exact same processor; the code here is:

``` c#

        public DateTime Time(CommandFlags flags = CommandFlags.None)
        {
            var msg = Message.Create(-1, flags, RedisCommand.TIME);
            return ExecuteSync(msg, ResultProcessor.DateTime);
        }

        public Task<DateTime> TimeAsync(CommandFlags flags = CommandFlags.None)
        {
            var msg = Message.Create(-1, flags, RedisCommand.TIME);
            return ExecuteAsync(msg, ResultProcessor.DateTime);
        }
```

do you have a repro that demonstrates this difference?

**Comment by MZar2019** [comment] 2019-09-25 00:25
@mgravell 
My mistake. I can see now that the .Kind was actually being set to Local because of math inside a property where the value was being stored. 
Indeed, both .Time and .TimeAsync return Utc.
Sorry.

**Comment by NickCraver** [comment] 2020-03-15 15:17
Looks like we're good here - closing to tidy up!

**Closed by NickCraver** 2020-03-15 15:17 UTC
Labels: documentation, up-for-grabs
