### ISSUE TITLE
ConnectionMultiplexer.Connect takes too long if one of the nodes is down.

### ISSUE THREAD

**Issue by gautamdh** [StackExchange/StackExchange.Redis#140] opened 2014-12-22 11:17 UTC
When one of the Redis nodes, given in the config string/options, is down then the connection multiplexer takes more than 2 minutes to connect. It connects successfully to the nodes that are running but takes too long. However, when all nodes are running then the connect operation is completed very fast.
Also checked the connect method logs by passing the string writer but these logs also do not show the reason for the connect delay. The logs clearly show that the down node did not respond. But the wait on the down node is not justified.

**Comment by jbengtssondn** [comment] 2015-01-06 21:44
I am experience the same issue even for just a one node configuration so I am looking forward for this fix.  Right now I have to implement my own timeout around the Connect call as a workaround.

**Comment by mfelicio** [comment] 2015-01-27 17:45
This seems to be fixed on NuGet pkg 1.0.394. I've updated my pkg version and can't reproduce it anymore. Does anybody else confirm?

**Closed** 2015-03-16 10:46 UTC
