### ISSUE TITLE
Unable to connect redis on linux container in Docker Swarm

### ISSUE THREAD

**Issue by karthickj25** [StackExchange/StackExchange.Redis#1414] opened 2020-03-31 08:07 UTC
I am trying to connect redis using stackexchage client but facing weird issue. 
So i've created a simple console app for testing.

The same code works when i built the console app with .net core framework (self-contained )

I could not figure out the root cause. Can someone shed some light on this please.

**What works**

- Ping from windows container to redis
- telnet from windows container to redis
- redis-cli commands from windows container to redis 

**Console app built on** 
- .net framework 4.7.1
- client version tried 2.1.28 , 2.0.600, 1.2.6 

**Code** 

` 
  
          Console.WriteLine("starting.....");
           var sr = new System.IO.StringWriter();
          
            try
            {
                var connectionstring = "redis:6379,resolveDns=True,ConnectTimeout=5000,SyncTimeout=6000,abortConnect=False,allowAdmin=True";
                var config = ConfigurationOptions.Parse(connectionstring);
                config.CommandMap = CommandMap.Create(new HashSet<string> { "SUBSCRIBE" }, false);              
                var cache = ConnectionMultiplexer.Connect(config, sr);

                Console.WriteLine($"is connected { cache.IsConnected }");

                var db =cache.GetDatabase();
                
                //the error occurs here
                db.StringSet("foo", "bar");

                db.StringGet("foo");
            }
            catch (Exception)
            {
                Console.WriteLine(sr.ToString());
                throw;
            }

            Console.ReadLine();
            Console.ReadLine();
            Console.ReadLine();
            return;`

*App config*

     <?xml version="1.0" encoding="utf-8"?>
      <configuration>
          <startup> 
              <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1" />
          </startup>
        <runtime>
          <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
            <dependentAssembly>
              <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
              <bindingRedirect oldVersion="0.0.0.0-4.0.6.0" newVersion="4.0.6.0" />
            </dependentAssembly>
            <dependentAssembly>
              <assemblyIdentity name="System.Buffers" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
              <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
            </dependentAssembly>
            <dependentAssembly>
              <assemblyIdentity name="System.Memory" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
              <bindingRedirect oldVersion="0.0.0.0-4.0.1.1" newVersion="4.0.1.1" />
            </dependentAssembly>
            <dependentAssembly>
              <assemblyIdentity name="System.IO.Pipelines" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
              <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" />
            </dependentAssembly>
            <dependentAssembly>
              <assemblyIdentity name="System.IO.Compression" publicKeyToken="b77a5c561934e089" culture="neutral" />
              <bindingRedirect oldVersion="0.0.0.0-4.2.0.0" newVersion="4.2.0.0" />
            </dependentAssembly>
          </assemblyBinding>
        </runtime>
      </configuration>

**Docker swarm with two nodes** 
- linux (running redis - alpine image)
- Windows 2016 (running servercore 2016 lts aspnet image)

**Error  log**
`is connected False
redis:6379,syncTimeout=6000,allowAdmin=True,connectTimeout=5000,abortConnect=False,resolveDns=True,$SUBSCRIBE=

Using DNS to resolve 'redis'...
'redis' => 10.0.9.221
Connecting 10.0.9.221:6379/Interactive...
BeginConnect: 10.0.9.221:6379
1 unique nodes specified
Requesting tie-break from 10.0.9.221:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=2,Free=998,Min=2,Max=1000), WORKER: (Busy=2,Free=2045,Min=2,Max=2047)
Connected Interactive/10.0.9.221:6379
Server handshake
Setting client name: F295D97412DE
Auto-configure...
Sending critical tracer: Interactive/10.0.9.221:6379
Writing to Interactive/10.0.9.221:6379: ECHO
Flushing outbound buffer
Starting read
Not all tasks completed cleanly (from ReconfigureAsync#1602, timeout 5000ms), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
10.0.9.221:6379 did not respond
Waiting for tiebreakers...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
Not all tasks completed cleanly (from NominatePreferredMaster#1839, timeout 50ms), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
10.0.9.221:6379 failed to nominate (WaitingForActivation)
No masters detected
10.0.9.221:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: ConnectedEstablishing; sub: n/a; not in use: DidNotRespond
10.0.9.221:6379: int ops=8, qu=0, qs=5, qc=0, wr=0, socks=1; sub ops=0, qu=0, qs=0, qc=0, wr=0
Circular op-count snapshot; int: 0+8=8 (0.80 ops/s; spans 10s); sub:
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
connection failed: 10.0.9.221:6379 (Interactive, UnableToConnect): UnableToConnect (None, last-recv: 59) on 10.0.9.221:6379/Interactive, Flushed/ReadAsync, last: ECHO, origin: ResetNonConnected, outstanding: 5, last-read: 4s ago, last-write: 5s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.1.28.64774
retrying; attempts left: 2...
1 unique nodes specified
Requesting tie-break from 10.0.9.221:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
Not all tasks completed cleanly (from ReconfigureAsync#1602, timeout 5000ms), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
10.0.9.221:6379 did not respond
Waiting for tiebreakers...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
Not all tasks completed cleanly (from NominatePreferredMaster#1839, timeout 50ms), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
10.0.9.221:6379 failed to nominate (WaitingForActivation)
No masters detected
10.0.9.221:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: ConnectedEstablishing; sub: n/a; not in use: DidNotRespond
10.0.9.221:6379: int ops=16, qu=0, qs=5, qc=0, wr=0, socks=2; sub ops=0, qu=0, qs=0, qc=0, wr=0
Circular op-count snapshot; int: 0+16=16 (1.60 ops/s; spans 10s); sub:
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
resetting failing connections to retry...
retrying; attempts left: 1...
1 unique nodes specified
Requesting tie-break from 10.0.9.221:6379 > __Booksleeve_TieBreak...
Allowing endpoints 00:00:05 to respond...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=2,Free=2045,Min=2,Max=2047)
Not all tasks completed cleanly (from ReconfigureAsync#1602, timeout 5000ms), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
10.0.9.221:6379 did not respond
Waiting for tiebreakers...
Awaiting task completion, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
Not all tasks completed cleanly (from NominatePreferredMaster#1839, timeout 50ms), IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=1,Free=2046,Min=2,Max=2047)
10.0.9.221:6379 failed to nominate (WaitingForActivation)
No masters detected
10.0.9.221:6379: Standalone v2.0.0, master; keep-alive: 00:01:00; int: ConnectedEstablishing; sub: n/a; not in use: DidNotRespond
10.0.9.221:6379: int ops=24, qu=0, qs=5, qc=0, wr=0, socks=3; sub ops=0, qu=0, qs=0, qc=0, wr=0
Circular op-count snapshot; int: 0+24=24 (2.40 ops/s; spans 10s); sub:
Sync timeouts: 0; async timeouts: 0; fire and forget: 0; last heartbeat: -1s ago
Starting heartbeat...

Unhandled Exception: StackExchange.Redis.RedisConnectionException: No connection is active/available to service this operation: SET foo; UnableToConnect (None, last-recv: 59) on 10.0.9.221:6379/Interactive, Flushed/ReadAsync, last: ECHO, origin: ResetNonConnected, outstanding: 5, last-read: 4s ago, last-write: 5s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.1.28.64774, mc: 1/1/0, mgr: 10 of 10 available, clientName: F295D97412DE, IOCP: (Busy=0,Free=1000,Min=2,Max=1000), WORKER: (Busy=0,Free=2047,Min=2,Max=2047), v: 2.1.28.64774 ---> StackExchange.Redis.RedisConnectionException: UnableToConnect (None, last-recv: 59) on 10.0.9.221:6379/Interactive, Flushed/ReadAsync, last: ECHO, origin: ResetNonConnected, outstanding: 5, last-read: 4s ago, last-write: 5s ago, keep-alive: 60s, state: ConnectedEstablishing, mgr: 10 of 10 available, last-heartbeat: never, global: 5s ago, v: 2.1.28.64774
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.StringSet(RedisKey key, RedisValue value, Nullable`1 expiry, When when, CommandFlags flags)
   at Redis.mk1.Program.Main(String[] args) in C:\Users\karthick.chandran\source\repos\Redis.mk1\Redis.mk1\Program.cs:line 93
`

**Comment by NickCraver** [comment] 2020-11-14 13:56
Finding this from another issue - if you are hitting this exclusively in .NET Framework and that IP is correct on the resolution, you're probably hitting binding redirects. We've added detection for this which adds to logging in later versions, I'd recommend grabbing the latest off MyGet (we'll update NuGet soon) for some additional logging that's not out on NuGet quite yet.

For binding redirects, here's hopefully some helpful info around the cause: https://nickcraver.com/blog/2020/02/11/binding-redirects/

**Comment by karthickj25** [comment] 2020-11-18 05:18
Thanks!!. I will test with the latest nuget in next release, (early March 2021).  I've added the binding redirects its working since then with occasional  drops, but I guess its due to 2016 windows nodes.

**Comment by NickCraver** [comment] 2021-05-20 02:21
:+1: Awesome - closing out to cleanup!

**Closed by NickCraver** 2021-05-20 02:21 UTC
