### ISSUE TITLE
Timeout performing GET (5000ms) Client version 2.1.30.38891

### ISSUE THREAD

**Issue by sonct2** [StackExchange/StackExchange.Redis#1733] opened 2021-05-21 04:15 UTC
Hi there,

I am facing issue with GET command: 

`Timeout performing GET (5000ms), next: GET list_api, 
inst: 0, qu: 466, qs: 3071, aw: True, bw: RecordingTimeout, rs: ReadAsync, ws: Flushed, in: 5065958, in-pipe: 131072, out-pipe: 0, 
serverEndpoint: 192.168.1.10:6379, mc: 1/1/0, mgr: 7 of 10 available, 
clientName: 809cc2d3145a, IOCP: (Busy=0,Free=1000,Min=1000,Max=1000), 
WORKER: (Busy=1001,Free=31766,Min=1000,Max=32767), v: 2.1.30.38891 
(Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

I don't understand where the issue is? I am using redis sentinel and request was hitting at master node. I have checked master node but didn't see any issues with node resource and replication. The server resource was plenty, free a lot.

Could you guys advise please?

Thanks in advance!

**Comment by sonct2** [comment] 2021-05-22 11:49
Can you tell me what best practice for the worker thread is? Or where i can find document to resolve it?

Thanks in advance!

**Comment by NickCraver** [comment] 2021-05-22 12:28
@sonct2 Can you share some environment details? 1000+ threads is a _lot_ happening at once, without beefy hardware, that can easily be CPU starvation and it would not get to processing responses (or even sends potentially) before the timeout expires. It looks like you expect heavy load since the minimums are set at 1000 given these error messages. What are those threads doing? Are they active? Waiting on I/O? Other? If it's something like waiting on I/O, this is where `async`/`await` would be much more kind to system resources :)

If you can explain a bit about the workload and _why_ there are 1000 threads, may be able to advise a bit better.

**Comment by sonct2** [comment] 2021-05-24 08:00
My server has 16 cores, 28G Ram. Those threads are just run GET and SET to Redis to serve clients. And I have checked and I haven't seen any issues like cpu resource till now. The number 1000 was from our developer, they actually didn't know why it was 1000, they just increased the number of minimum to that to prevent timeout. 

Could you please advise?

Thanks in advance!

**Comment by TimLovellSmith** [comment] 2021-06-23 16:50
Closing, as its not a reproducible issue.

You should take a dump of your application or use debugger to see why you have 1000 busy threads. If they're all stuck doing redis operations, its likely because you're using the synchronous APIs instead of asynchronous, combined with some other slowdown in the system meaning that those calls can't complete quickly.

**Closed by TimLovellSmith** 2021-06-23 16:50 UTC
