### ISSUE TITLE
Working with sentinels: the master changes to another server

### ISSUE THREAD

**Issue by emi662002** [StackExchange/StackExchange.Redis#1584] opened 2020-10-13 09:19 UTC
Hi,

I'm using the ConnectionMultiplexer.SentinelConnect and this works as expected (given any sentinel server order in the connection string, I can retrieve a sentinel connection and then a master connection with GetSentinelMasterConnection.

I am storing this last connection multiplexer as documented (the multiplexer is designed to be reused).
The problem I'm currently experimenting is as follows:
I have 3 sentinels (host1, host2, host3), host1 is the master.
Everything works fine now (any combination of hosts in my connection string will work as the multiplexer always retrieves the right master)
When the master changes (for example, in a Kubernetes environment using redis-ha a pod is deleted, the another pod is chosen as master)
Then my multiplexer is not valid anymore. 

Is there a way to check if the connection multiplexer for the master is still the master?

**Comment by emi662002** [comment] 2020-10-13 12:35
> Hi,
> 
> I'm using the ConnectionMultiplexer.SentinelConnect and this works as expected (given any sentinel server order in the connection string, I can retrieve a sentinel connection and then a master connection with GetSentinelMasterConnection.
> 
> I am storing this last connection multiplexer as documented (the multiplexer is designed to be reused).
> The problem I'm currently experimenting is as follows:
> I have 3 sentinels (host1, host2, host3), host1 is the master.
> Everything works fine now (any combination of hosts in my connection string will work as the multiplexer always retrieves the right master)
> When the master changes (for example, in a Kubernetes environment using redis-ha a pod is deleted, the another pod is chosen as master)
> Then my multiplexer is not valid anymore.
> 
> Is there a way to check if the connection multiplexer for the master is still the master?

Couldn't find a nice way to do this but we can subscribe to an event instead of polling to check the connection. see https://github.com/StackExchange/StackExchange.Redis/issues/1582#issuecomment-707614401

**Comment by emi662002** [comment] 2020-10-15 08:48
this approach still doesn't work.

**Comment by NickCraver** [comment] 2022-01-05 12:59
@emi662002 Several Sentinel fixes went in since that issue was filed and comment you linked to - which version of the library are you on? Are you still having trouble in the latest version?

**Comment by NickCraver** [comment] 2022-02-20 23:14
If anyone's still hitting issues here, please try and latest release - it has a great number of Sentinel fixes along the way. Closing this issue out to tidy up.

**Closed by NickCraver** 2022-02-20 23:14 UTC
Labels: area:sentinel

**Comment by JorTurFer** [comment] 2022-03-10 08:37
Hi @NickCraver 
I can reproduce this exactly behavior using version `2.5.43`. 
Do you prefer that I open other issue?
