### ISSUE TITLE
Connection failures with v 2.2.88 

### ISSUE THREAD

**Issue by Jonesie** [StackExchange/StackExchange.Redis#1919] opened 2021-11-29 19:34 UTC
I updated to v 2.2.88.  Our staging environment is now reporting connection failures (see below).  Production has been running v 2.2.79 for a couple of months, 2.2.62 before that. I reverted our stage build to 62 and it seems stable again so far.

We are running .net 5.0.400 in a fargate container on AWS, accessing ElastiCache Redis.

No specific config other than the server name.  I should probably do some retry logic but we've never needed it before.

```
      _connection = new Lazy<ConnectionMultiplexer>(() =>
      { _logger.LogInformation($"RedisCache connecting to {_cacheSettings.Servers}");
        return ConnectionMultiplexer.Connect(_cacheSettings.Servers);
      });
```

Logs are :

```
StackExchange.Redis.RedisConnectionException: It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code. ConnectTimeout
   at StackExchange.Redis.ConnectionMultiplexer.ConnectImpl(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1186
   at StackExchange.Redis.ConnectionMultiplexer.Connect(ConfigurationOptions configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1061
   at StackExchange.Redis.ConnectionMultiplexer.Connect(String configuration, TextWriter log) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 1036
...
```

**Comment by alex-jitbit** [comment] 2021-12-05 15:23
I've had a similar issue. We were having these random connection timeouts during ASP.NET Core app recycles on IIS. Every 1 out of 2-4 connections was timing out. And if we use `abortConnect=false` - it just froze indefinitely. I thought this was a network issue, (our redis was in a different AWS subnet), but moving things into one region&subnet did not help.

We are using a `static` singleton `ConnectionMultiplexer` variable.

Strangely the workaround was to **not `Dispose` the connection on app shutdown.**

We used to have an event handler assigned to `AppDomain.CurrentDomain.ProcessExit` that ran a `Dispose` on the `ConnectionMultiplexer` object. Once we removed that code - the timeouts were gone. Hope that helps anyone who stumbles on a similar issue and helps Marc & Nick investigate.

**Comment by alex-jitbit** [comment] 2021-12-08 07:27
I deleted my previous comment since the workaround stopped working.

So in our case it appears that the initial connection timeouts always occur _during IIS recycles_ at busy times (but not at night when the load is lower).

My guess is after a recycle there's a huge queue of requests that need to be processed. Maybe this is caused by thread starvation and the delay .netcore spawns new threads with, what do you think @mgravell ? Can this be a problem? I will try to increase the `ThreadPool.SetMinThreads` and see if this helps.

Again, the timeout does not occur during Redis operation, just the initial connect. And setting `abortConnect=false` just results in the app freezing for 2-3 minutes.

**Comment by dehaaneric** [comment] 2021-12-08 08:08
FYI: the Azure-best-pratices (I know, some use AWS) have been updated. Dropping the Lazy implementation and replace it with a single thread Semaphore lock. See my question about why dropping the LazyList [here](https://github.com/Azure-Samples/azure-cache-redis-samples/issues/14). The interesting part:

>  Lazy<> uses a lock internally that can lead to contention under high load

**Comment by Jonesie** [comment] 2021-12-08 14:12
We are certainly not in a high load situation, and its only broked in 2.2.88 afaik.  However, I'll remove the Lazy<> and try again.

**Comment by alex-jitbit** [comment] 2021-12-15 14:52
I'm back with another workaround.

We were instantiating the `ConnectionMultiplexer` in a static constructor. Which, in a way, is similar to `Lazy` - it locks, and it runs when you first access the static variable.

**As soon as we moved the connection-creation to `Startup.cs` class, so it runs sooner, our connection timeouts were gone.**

**Comment by NickCraver** [comment] 2022-02-06 03:12
@Jonesie did this change work for you? It seems the common thread here is trying to connect/complete under contention, when requests are likely slamming the app exhausting threads now allowing that completion.

**Comment by Jonesie** [comment] 2022-02-07 01:04
I reverted to a previous version.  Don't have time for experiments.

**Comment by NickCraver** [comment] 2022-02-07 01:33
@Jonesie acknowledged, if unwilling to try a newer release I'll go ahead and close this out, not much we can help with even if there is something to fix here.

**Closed by NickCraver** 2022-02-07 01:33 UTC
Labels: needs-info
