### ISSUE TITLE
Fix below Thread Safety issues reported by Infer# 

### ISSUE THREAD

**Issue by IngawaAb-bh** [StackExchange/StackExchange.Redis#2489] opened 2023-06-23 10:45 UTC
#1
/_/src/StackExchange.Redis/LogProxy.cs:14: warning: Thread Safety Violation
  Read/Write race. Non-private method `LogProxy.ToString()` reads without synchronization from `this.StackExchange.Redis.LogProxy._log`. Potentially races with write in method `LogProxy.Dispose()`.
 Reporting because this access may occur on a background thread.

#2
/_/src/StackExchange.Redis/LogProxy.cs:30: warning: Thread Safety Violation
  Read/Write race. Non-private method `LogProxy.WriteLine()` reads without synchronization from `this.StackExchange.Redis.LogProxy._log`. Potentially races with write in method `LogProxy.Dispose()`.
 Reporting because this access may occur on a background thread.

#3
/_/src/StackExchange.Redis/LogProxy.cs:40: warning: Thread Safety Violation
  Read/Write race. Non-private method `LogProxy.WriteLine(...)` reads without synchronization from `this.StackExchange.Redis.LogProxy._log`. Potentially races with write in method `LogProxy.Dispose()`.
 Reporting because this access may occur on a background thread.

#4
/_/src/StackExchange.Redis/LogProxy.cs:50: warning: Thread Safety Violation
  Read/Write race. Non-private method `LogProxy.WriteLine(...)` reads without synchronization from `this.StackExchange.Redis.LogProxy._log`. Potentially races with write in method `LogProxy.Dispose()`.
 Reporting because this access may occur on a background thread.

#5
/_/src/StackExchange.Redis/LogProxy.cs:60: warning: Thread Safety Violation
  Read/Write race. Non-private method `LogProxy.Dispose()` reads without synchronization from `this.StackExchange.Redis.LogProxy._log`. Potentially races with write in method `LogProxy.Dispose()`.
 Reporting because this access may occur on a background thread.

#6
/_/src/StackExchange.Redis/RedisTransaction.cs:67: warning: Thread Safety Violation
  Read/Write race. Non-private method `RedisTransaction.ExecuteAsync(...)` indirectly reads without synchronization from `message.StackExchange.Redis.Message.<Flags>k__BackingField`. Potentially races with write in method `RedisTransaction.ExecuteAsync(...)`.
 Reporting because this access may occur on a background thread.

#7
/_/src/StackExchange.Redis/RedisTransaction.cs:74: warning: Thread Safety Violation
  Unprotected write. Non-private method `RedisTransaction.ExecuteAsync(...)` indirectly writes to field `message.StackExchange.Redis.Message.resultBox` outside of synchronization.
 Reporting because this access may occur on a background thread.

#8
/_/src/StackExchange.Redis/RedisTransaction.cs:79: warning: Thread Safety Violation
  Unprotected write. Non-private method `RedisTransaction.ExecuteAsync(...)` indirectly writes to field `message.StackExchange.Redis.Message.<Flags>k__BackingField` outside of synchronization.
 Reporting because this access may occur on a background thread.

**Comment by NickCraver** [comment] 2023-06-23 11:19
Duplicate of #2331.

**Closed by NickCraver** 2023-06-23 11:19 UTC
