### ISSUE TITLE
Redis and Redis.StrongName errors on VS for MAC

### ISSUE THREAD

**Issue by KevinBurton** [StackExchange/StackExchange.Redis#776] opened 2018-02-03 10:13 UTC
I am on Visual Studio for Mac Community and I cannot get rid of this error

```
Error CS0433: The type 'ConnectionMultiplexer' exists in both 'StackExchange.Redis.StrongName, Version=1.2.4.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46' and 'StackExchange.Redis, Version=1.2.6.0, Culture=neutral, PublicKeyToken=null
```
I was able to get rid of the error and successfully compile using 'dotnet build' but for some reason when I build with VS I get a bunch of error messages and it refuses to compile. For this project I have

```
 <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="StackExchange.Redis" Version="1.2.6" />
  </ItemGroup>
```

Ideas on how to get rid of this error so I can compile and run the application?

Thank you.

Kevin

**Comment by mgravell** [comment] 2018-02-03 10:37
So it sounds like you're referencing both. You need to not do that.
Reference either the strong-named version or the non-strong-named version.
Not both.

We should bite the bullet and merge the two in a "major" release.

**Comment by KevinBurton** [comment] 2018-02-03 15:05
I only have one “using” and that is StackExchange.Redis.

**Comment by mgravell** [comment] 2018-02-03 15:10
The problem is the package references, i.e. the NuGet dependencies. This is
on the csproj as "PackageReference" if you're using the new build system -
otherwise I want to say "packages.config"? Or: just use the IDE and look at
what packages you are referencing.

The "using" directives at the top of the file don't impact the package
references.

**Comment by KevinBurton** [comment] 2018-02-03 15:21
Here is the .csproj file. The funky conditional reference was to get 'dotnet build' to compile. I get the same error no matter how the .csproj reference is specified with VS on MAC:

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="MongoDB.Driver" Version="2.5.0" />
    <PackageReference Include="Neo4j.Driver" Version="1.5.2" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="StackExchange.Redis" Version="1.2.6" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>

**Comment by mgravell** [comment] 2018-02-03 15:26
Right; I'm guessing that the "aspnet core all" is importing the strong named version as part of the caching tier. So: try simply removing the StackExchange.Redis dependency. Or try changing it StackExchange.Redis.StrongName. It is the exact same code packaged slightly differently.

**Comment by KevinBurton** [comment] 2018-02-03 15:45
How do I know "aspnet core all" is importing the strong named version or that there is even any dependency on "StackExchange.Redis"? Thank you for your help. Removing it fixed the problem.

**Comment by mgravell** [comment] 2018-02-03 15:51
Good question - it is slightly hidden and indirect. The real import is from https://www.nuget.org/packages/Microsoft.Extensions.Caching.Redis/, which is part of this: https://www.nuget.org/packages/Microsoft.AspNetCore.All

Basically, expand the dependencies branch of each. There may be a better way of finding where a dependency comes from, but: that worked for me.

**Comment by erichummel** [comment] 2018-03-28 18:16
Removing StackExchange.Redis from NuGet and adding StackExchange.Redis.StrongName there fixed the problem for me (while leaving the `using StackExchange.Redis` untouched)

**Comment by NickCraver** [comment] 2018-05-27 19:47
Remedies above - and we're just going to strong name the base package and deprecate .StrongName in v2, so closing this out to cleanup.

**Closed by NickCraver** 2018-05-27 19:47 UTC

**Comment by KeithHenry** [comment] 2018-09-06 07:56
I don't think that remedy works, unless everyone upgrades from StrongName to 2 at once. I've raised #942 for ASP.NET Core.

**Comment by isdaniel** [comment] 2019-11-04 07:26
There is a solution could solve this problem.

We can try to use `Aliases` tag in `csproj` file.

```xml
    <Reference Include="StackExchange.Redis.StrongName, Version=1.2.6.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46, processorArchitecture=MSIL">
      <HintPath>..\..\packages\StackExchange.Redis.StrongName.1.2.6\lib\net46\StackExchange.Redis.StrongName.dll</HintPath>
      <Aliases>RedisStrongName</Aliases>
    </Reference>
```

if you want to use `RedisStrongName` you could extern the alias name like this.

```csharp
extern alias RedisStrongName;
using System;
using StackExchange.Redis;
using FirstBar = RedisStrongName::StackExchange.Redis;
```

https://stackoverflow.com/questions/286632/what-use-is-the-aliases-property-of-assembly-references-in-visual-studio-8

**Comment by ArjunVachhani** [comment] 2020-08-04 07:20
In our case one package is referencing `StackExchange.Redis` and another package is using `StackExchange.Redis.StrongName` package. I am using .Net Core and csproj file does not have any entry for `<Reference>` tag. any idea how to resolve this issue?
@mgravell @NickCraver

**Comment by mgravell** [comment] 2020-08-04 08:37
The short version would be: "don't do that"; pick one (preferably the now strong-named v2 package), and use that throughout.
