### ISSUE TITLE
UNLINK is not supported at ALI Cloud for redis 4.0!

### ISSUE THREAD

**Issue by brotherhorse** [StackExchange/StackExchange.Redis#1010] opened 2018-11-27 02:43 UTC
ALI Cloud Redis cluster 4.0 do not support UNLINK
Please set an options for Key.Delete cmd for use or not use UNLINK!
https://www.aliyun.com

**Comment by NickCraver** [comment] 2018-11-27 03:02
Duplicate of #1004 - see there for how to work around providers that don't support commands.

**Closed by NickCraver** 2018-11-27 03:02 UTC
