### ISSUE TITLE
Transaction commands mix

### ISSUE THREAD

**Issue by olizarevichroman** [StackExchange/StackExchange.Redis#2255] opened 2022-09-22 14:01 UTC
Hi

I've found weird issue when trying to concurrently execute 2 transactions, commands from both transactions are mixed sometimes, causing failing one of them

Here is the log from profiler. You can notice that 2 `WATCH` commands were sent one by one, watching set with `messenger:groups` key. After that client `60062` modifies set and executes transaction first and the second transaction for client `60060` fails. How it possible that commands are mixed?

```
1663854450.524597 [0 172.18.0.1:60062] "WATCH" "messenger:groups"
1663854450.524613 [0 172.18.0.1:60062] "SISMEMBER" "messenger:groups" "a6ee2750-e782-4e21-8ddb-8585062e896c"
1663854450.524624 [0 172.18.0.1:60060] "WATCH" "messenger:groups"
1663854450.524629 [0 172.18.0.1:60060] "SISMEMBER" "messenger:groups" "cfe933aa-ee8d-4029-af07-5b4b79e35061"
1663854450.529251 [0 172.18.0.1:60062] "MULTI"
1663854450.529274 [0 172.18.0.1:60062] "SADD" "messenger:groups" "a6ee2750-e782-4e21-8ddb-8585062e896c"
1663854450.529287 [0 172.18.0.1:60062] "HMSET" "messenger:groups:a6ee2750-e782-4e21-8ddb-8585062e896c" "created-at" "706200000" "name" "f7fd555e-2026-4e0b-8654-af81a8c132c0" "creator-id" "a4f83fb8-b1ea-4a35-bdc1-8274b1823004" "type" "group"
1663854450.529307 [0 172.18.0.1:60062] "SADD" "messenger:users:a4f83fb8-b1ea-4a35-bdc1-8274b1823004:chats" "a6ee2750-e782-4e21-8ddb-8585062e896c"
1663854450.529325 [0 172.18.0.1:60062] "SADD" "messenger:groups:a6ee2750-e782-4e21-8ddb-8585062e896c:members" "a4f83fb8-b1ea-4a35-bdc1-8274b1823004"
1663854450.529337 [0 172.18.0.1:60062] "HSET" "messenger:groups:a6ee2750-e782-4e21-8ddb-8585062e896c:members:a4f83fb8-b1ea-4a35-bdc1-8274b1823004" "joined-at" "706200000"
1663854450.529350 [0 172.18.0.1:60062] "EXEC"
1663854450.529498 [0 172.18.0.1:60060] "MULTI"
1663854450.529525 [0 172.18.0.1:60060] "EXEC"
```

Nuget package version : `2.6.66`

**Comment by hankovich** [comment] 2022-10-04 18:42
Hm, @mgravell @NickCraver is it ok?

I thought that a transaction could fail if and only if at least one of the conditions was not satisfied. And it something bad happened inside the transaction (i.e. if the `WATCH`ed key changed outside the transaction), the transaction will be automatically retried until either 1. it succeeds or 2. at least one of the conditions is not satisfied.

Am I right?

**Comment by mgravell** [comment] 2022-10-04 19:03
Sorry for missing this the first time. Re mixing of commands: this looks
like two competing connections - which is expected and normal at least
outside of the multi/exec. If a watched key is touched, the multi/exec
should be failed - and the Execute method should return false. We do *not*
retry in a loop, however. Maybe this is the confusion?

**Comment by olizarevichroman** [comment] 2022-10-04 19:22
Hi @mgravell 
I would say it's confusing, because in the documentation [here](https://stackexchange.github.io/StackExchange.Redis/Transactions) there are some sentences which seems to say that in `Redis` it works in this way, but in `StackExchange` it works in another way.

For example `This is further complicated by the fact that StackExchange.Redis uses a multiplexer approach. We can’t simply let concurrent callers issue WATCH / UNWATCH / MULTI / EXEC / DISCARD: it would all be jumbled together.` looks like "we don't emit WATCH/UNWATCH and etc concurrently".

Or `This is all done in a way that prevents the commands being mixed together with other callers. ` also says that "we don't even trying to make command concurrent".

So, probably it should be described without ambiguity.
And in this specific case can be described in the documentation, when we have multiple clients and transactions can fail even if all conditions were met.

**Comment by mgravell** [comment] 2022-10-04 19:30
Right; that documentation is talking about commands on a single connection.
We can't allow interleave there, as it would be impossible to coordinate.
The scenario here, though, is two competing connections - we can't
*prevent* anything there, except that which is prevented by the server,
i.e. a single connection inside a multi/exec block. Sorry if this is
confusing, but... it genuinely is complicated.

In reality, the best way to avoid this complexity these days is usually: to
use Lua for atomic related operations, via ScriptEvaluate etc. This is a
different programming model, but allows rich server-side operations inside
the atomic batch

**Comment by olizarevichroman** [comment] 2022-10-04 19:44
@mgravell thanks)
I would say it's not so complicated and sounds logical

**Comment by hankovich** [comment] 2022-10-04 20:02
Is there any way to reliably check a real cause of the transaction failure?

Because as I see condition may report `WasSatisfied == false` in case of failed `WATCH`. How can I understand was it condition failure or `WATCH` failure?

Will retrying failed transactions help to resolve concurrency issue? Do you know how other teams resolve concurrency problems? Are there any reliable solutions/libraries/examples?

Because I think there are a lot of users who use SE.Redis in replicated micro-service environments, so it might be some solutions (except Lua scripts).

Thanks in advance!

**Comment by mgravell** [comment] 2022-10-04 22:10
You can check the ConditionResult.WasSatisfied for each constraint, but:
that only tells you whether they were still OK after the WATCH and before
the MULTI; a conflict on the same key can still happen, which will result
in the entire MULTI block being abandoned. So: if you check all the
conditions and one is false: *that* is the problem; if all the conditions
reporting true, but the transaction reported false, then: a key conflict
presumably occurred. We cannot tell you which, because redis doesn't tell
us.

**Comment by mgravell** [comment] 2022-10-11 07:14
Note also that inside the multi/exec, there is only one connection, so
again: this looks like normal expected behaviour in a race scenario.

**Comment by NickCraver** [comment] 2022-10-26 01:02
Going to close this out to tidy up, but happy to re-open if there's a follow-up!

**Closed by NickCraver** 2022-10-26 01:02 UTC
