### ISSUE TITLE
Delete key timeouts

### ISSUE THREAD

**Issue by RPM1984** [StackExchange/StackExchange.Redis#480] opened 2016-09-12 07:02 UTC
I'm seeing lots of "Timeout performing DEL" errors in my logs, like this:

> Timeout performing DEL listing:2177738:summary:map, inst: 40, mgr: Inactive, err: never, queue: 1, qu: 0, qs: 1, qc: 0, wr: 0, wq: 0, in: 69, ar: 0, clientName: RD000D3AE00DD1, IOCP: (Busy=1,Free=999,Min=1,Max=1000), WORKER: (Busy=9,Free=32758,Min=1,Max=32767), Local-CPU: unavailable (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md) StackTrace: at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) at StackExchange.Redis.RedisDatabase.KeyDelete(RedisKey key, CommandFlags flags) at InceptionCache.Providers.RedisCacheProvider.RedisCacheProvider.Delete(String key) Error Context

What i'm running:
- Azure Redis Cache
- StackExchange.Redis 1.1.603

Can anyone tell me what those numbers in the logging means, to give me a clue where to look?

**Comment by gzpbx** [comment] 2016-09-13 15:21
#477 ,try 1.1.605

**Comment by RPM1984** [comment] 2016-09-13 21:17
Ok ill try updsring

**Comment by RPM1984** [comment] 2016-09-13 21:20
However, im only getting these errors _sometimes_, not all the time.

**Comment by RPM1984** [comment] 2016-09-20 23:47
@mgravell @NickCraver any tips on this? 

Here's a bunch of the stats from the timeouts when it happens:
```
inst: 2, queue: 1, qu: 1, qs: 0, qc: 0, wr: 0, wq: 1, in: 0, ar: 0, clientName: RD000D3AE00DD1, IOCP: (Busy=1,Free=999,Min=1,Max=1000), WORKER: (Busy=6,Free=32761,Min=1,Max=32767), Local-CPU: unavailable
inst: 16, queue: 2, qu: 1, qs: 1, qc: 0, wr: 0, wq: 1, in: 39613, ar: 0, clientName: RD000D3AE00DD1, IOCP: (Busy=1,Free=999,Min=1,Max=1000), WORKER: (Busy=6,Free=32761,Min=1,Max=32767), Local-CPU: unavailable
inst: 3, queue: 1, qu: 0, qs: 1, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, clientName: RD000D3AE00DD1, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=3,Free=32764,Min=1,Max=32767), Local-CPU: unavailable
inst: 3, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0, clientName: RD000D3AE00DD1, IOCP: (Busy=1,Free=999,Min=1,Max=1000), WORKER: (Busy=2,Free=32765,Min=1,Max=32767), Local-CPU: unavailable
inst: 2, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 65536, ar: 0, clientName: RD000D3AE00DD1, IOCP: (Busy=1,Free=999,Min=1,Max=1000), WORKER: (Busy=1,Free=32766,Min=1,Max=32767), Local-CPU: unavailable
inst: 1, queue: 2, qu: 2, qs: 0, qc: 0, wr: 0, wq: 1, in: 0, ar: 0, clientName: RD000D3AE00DD1, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=3,Free=32764,Min=1,Max=32767), Local-CPU: unavailable
```

Can you guys make some sense of this?

I don't see any network/cpu overload on the Redis server, although i _do_ see an influx of GET requests... but unless the server is overloaded this shouldn't matter?

**Comment by RPM1984** [comment] 2016-09-20 23:49
Also is there any page/resource that specifies what all those numbers mean?

**Comment by RPM1984** [comment] 2016-09-28 06:03
Since i'm not concerned with the response, i'm wondering if i should use `CommandFlags.FireAndForget`? Will that prevent these timeouts?

The main thing i don't get here is why is only the `Delete` method timing out... `DeleteAsync` never does, and other gets/sets don't either in the same time when `Delete` times out..

So if the server was overloaded i would expect _everything_ to time out?

**Comment by ankurmalhotra89** [comment] 2016-10-10 10:42
I am also getting the similar response

` 
{"Timeout performing GET rWorkerNode@001_jobs_Lock, inst: 1, queue: 6, qu: 0, qs: 6, qc: 0, wr: 0, wq: 0, in: 50, ar: 0, clientName: WS-machine, IOCP: (Busy=43,Free=957,Min=8,Max=1000), WORKER: (Busy=9,Free=32758,Min=8,Max=32767), Local-CPU: 87.34% (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)"}

   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisDatabase.StringGet(RedisKey key, CommandFlags flags)
   at Client.RunLockedOperation(String key, String lockedKey, Action`2 aSyncoperation, Action`1 syncOperation, Boolean isAsync)
   at Client.RunLockedOperationSync(String key, String lockedKey, Action`1 operation)
   at RNode.Update(Job newJob) in E:\_Work\EDM.Cluster.NET\EDM\EdmCluster\RNode\RNode.cs:line 287
   at Node.RunGraph(String Job) in E:\_Work\EDM.Cluster.NET\EDM\EdmCluster\RNode\RNode.cs:line 273
   at RunGraph(String partialGraph) in E:\_Work\EDM.Cluster.NET\EDM\EdmCluster\RNode\RNServiceWrapper.cs:line 38
   at SyncInvokeRunPartialGraph(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
`
and my machine.config looks like this

![image](https://cloud.githubusercontent.com/assets/6507285/19233560/e3116968-8f03-11e6-9f3c-f0ce172724e7.png)


Did anyone find a solution

**Comment by bargitta** [comment] 2017-02-28 09:26
For your IOCP theads, the busy one is more than the min. In this case, you will get timeout exception.
 IOCP: (Busy=43,Free=957,Min=8,Max=1000)

**Comment by NickCraver** [comment] 2018-06-09 12:50
For these issues, we added a bunch of timeout documentation here: https://stackexchange.github.io/StackExchange.Redis/Timeouts we'll also be trying to make the networking stack more resilient in v2, you can track progress in the [pipelines branch](https://github.com/StackExchange/StackExchange.Redis/tree/pipelines). I'm going to close this out since it's a duplicate of many and the landscape/error information has changed a lot (including causes resolved). If you're still hitting an issue and find this though (on the latest version of the library!), please open one so we can take a look.

**Closed by NickCraver** 2018-06-09 12:50 UTC
Labels: platform:Azure, timeout
