### ISSUE TITLE
Timeout issue AKS RedisCluster

### ISSUE THREAD

**Issue by scholtz** [StackExchange/StackExchange.Redis#1680] opened 2021-02-04 15:51 UTC
Hi, I am getting this type of timeouts:

StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=94KiB, 1808ms elapsed, timeout is 1000ms), command=HGET, next: HGET key1, inst: 0, qu: 0, qs: 1, aw: False, rs: DequeueResult, ws: Idle, in: 0, in-pipe: 129409, out-pipe: 0, serverEndpoint: 10.244.0.19:6379, mc: 1/1/0, mgr: 9 of 10 available, clientName: mass-covid-testing-api-ba-deployment-b57bc44ff-5vz56, PerfCounterHelperkeyHashSlot: 10824, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=2,Free=32765,Min=1,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 1004ms elapsed, timeout is 1000ms), command=SMEMBERS, next: SMEMBERS key2, inst: 0, qu: 0, qs: 1, aw: False, rs: ReadAsync, ws: Idle, in: 301, in-pipe: 0, out-pipe: 0, serverEndpoint: 10.244.0.18:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: mass-covid-testing-api-ba-deployment-b57bc44ff-dz2bx, PerfCounterHelperkeyHashSlot: 13915, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=3,Free=32764,Min=1,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)

Load is not very high.

Application .net5 runs in docker container in kubernetes. Redis-cluster runs in docker in kubernetes.

1) Why does it happen? 
2) How can I increase the timeout 1000 ms to 10 seconds?

**Comment by juniormayhe** [comment] 2021-02-05 12:22
We are also experiencing something similar, but with netcore 3.1 application in Kubernetes cluster. Intermittent timeouts happening for GET and HMSET. 

The message for StackExchange.Redis.RedisTimeoutException while using GET:

```
The timeout was reached before the message could be written to the output buffer, and it was not sent, command=GET, timeout: 50, outbound: 0KiB, inbound: 27KiB, inst: 128, qu: 0, qs: 0, aw: True, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: myprodserver.local:6379, mc: 1/1/0, mgr: 9 of 10 available, clientName: Routing_redis_cache, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=6,Free=32761,Min=1,Max=32767), v: 2.1.58.34321 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
```

The message for EXPIRE and HMSET:
```
Timeout awaiting response (outbound=1KiB, inbound=0KiB, 64ms elapsed, timeout is 50ms), command=EXPIRE, next: HMSET RoutingService_ExcludedSuppliersReport_628fd326-6999-4947-a8dd-9e1873ffc31b, inst: 0, qu: 0, qs: 8, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: wec21-prv-rds02.fflive.local:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: Routing_redis_cache, IOCP: (Busy=0,Free=1000,Min=1,Max=1000), WORKER: (Busy=5,Free=32762,Min=1,Max=32767), v: 2.1.58.34321 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)
```

We are using StackExchange.Redis 2.1.58, the latest is 2.2.4 as of now. I didn't check yet the release notes to see what are the changes in the latest version to decide if we must upgrade this package.

Maybe the issue could be more related to CPU overload, network issues, or cluster settings. I cannot affirm anything for now.

**Comment by scholtz** [comment] 2021-02-06 07:01
I am using this configuration:

```appsettings.json
..
  "Redis": {
    "AllowAdmin": false,
    "ConnectTimeout": 10000,
	"SyncTimeout": 10000,
	"AsyncTimeout": 10000,
	"KeepAlive": 30,
    "ConnectRetry": 3,
    "Database": 0,
	"Password":"..",
	"Hosts": [
      {
        "Host": "redis-redis-cluster.redis-cluster.svc.cluster.local",
        "Port": "6379"
      }
    ]
  },
...
```

Nuget: StackExchange.Redis.Extensions.AspNetCore: 6.3.6
Nuget: StackExchange.Redis.Extensions.Core: 6.3.6
Nuget: StackExchange.Redis.Extensions.Newtonsoft: 6.3.6

Redis cluster from bitnami helm: docker.io/bitnami/redis-cluster:6.0.10-debian-10-r1

**Comment by scholtz** [comment] 2021-02-07 16:40
I think my issues has gone after hardcoding ThreadPool settings

https://github.com/scholtz/covid-sk-api/commit/7a984ea9b68fc813ce96f7fe8be59b3fed92ed0f

```c#
ThreadPool.SetMinThreads(20, 20);
```

or it might be with this:
```
if (redisConfiguration.SyncTimeout < 10000) redisConfiguration.SyncTimeout = 10000;
```

**Comment by yuvallevy2** [comment] 2021-02-08 07:00
Hi @scholtz @juniormayhe can you give more details on how the client and server are connected? is there a service mesh in play? other components in between?

**Comment by Goolyio** [comment] 2021-02-08 15:41
> I think my issues has gone after hardcoding ThreadPool settings
> 
> [scholtz/covid-sk-api@7a984ea](https://github.com/scholtz/covid-sk-api/commit/7a984ea9b68fc813ce96f7fe8be59b3fed92ed0f)
> 
> ```cs
> ThreadPool.SetMinThreads(20, 20);
> ```
> 
> or it might be with this:
> 
> ```
> if (redisConfiguration.SyncTimeout < 10000) redisConfiguration.SyncTimeout = 10000;
> ```

@scholtz Setting the min threads to 20 also worked for me, was there a reason why you decided 20 was the number to use? The algo that .NET uses to set the min threads were setting them to 4 for me (docs on this https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.setminthreads?view=net-5.0#remarks).

**Comment by scholtz** [comment] 2021-02-08 16:40
@Goolyio .. not really.. i read somewhere to set it to (10,10) so i decided to do for production 20,20 as i expect thousands connections per second in whole aks .. i dont understand why this is not in base configuration and it fails with default settings.. or perhaps its a bug that when minimum threads is set to 1 it does not start the thread correctly?

**Comment by Goolyio** [comment] 2021-02-08 17:35
@scholtz I think if you try increasing the load so the number of threads needed goes over the min thread pool amount you will notice you get the same errors. [This blog post](https://bartlomiejmucha.com/en/blog/how-to-fix-a-redis-timeouts/) explains what the minimum thread pool number is used for quite well but here is a quote to give you the idea
> ThreadPool provides new threads on demand until it reaches a minimum. Then it will throttle the rate at which it injects new threads to one thread per 500 milliseconds. The StackExchange.Redis has dedicated internal pool of threads, and if it's failing to keep up, additional work will be offered to the global ThreadPool.

The blog post also explains why we are getting timeout errors because we are waiting for threads to be "created" under high bursts of trafic. That being said I don't know a lot about the inner workings of StackExchange.Redis, @yuvallevy2 does this seem like a valid conclusion to you? Please let me know if you need more info to decide 😊

**Comment by scholtz** [comment] 2021-02-21 13:54
I confirm that under higher load the error returned.. It is not that critical, but from time to time I get error 

One or more errors occurred. (Endpoint 10.244.0.46:6379 serving hashslot 5243 is not reachable at this point of time. Please check connectTimeout value. If it is low, try increasing it to give the ConnectionMultiplexer a chance to recover from the network disconnect. IOCP: (Busy=0,Free=1000,Min=20,Max=1000), WORKER: (Busy=40,Free=32727,Min=20,Max=32767), Local-CPU: n/a)

The problem for now was solved by increasing from 20 to 50

I do not need the reason why this is happening, but the solution.. Something is really wrong with this library..

@yuvallevy2 I am running redis cluster in AKS . In the same cluster i am running the application. I believe I have described my setup in first/second post.. redis-redis-cluster.redis-cluster.svc.cluster.local is the kubernetes service .. does it apply to your definition of service mesh?

**Comment by NickCraver** [comment] 2021-05-21 02:06
Trying to catch up here: what is the environment you're running in? 50ms is a very low timeout _maximum_ to have in any environment. If you're in a virtual environment which has noisy neighbors, etc. that's even more certain to trip timeouts.

The thread pool limits above set at 20: that's not the library, that's .NET itself. In a 50ms timeout situation if your workers are completely busy _and can't complete the request_, then we're stuck waiting in queue to be serviced. The thread pool only grows every 500ms, so it takes 10x a single timeout for a thread to even appear, it'll never naturally happen at that rate. If you expect spikes: more threads would be a configuration to case. Or alternative: see why you're using so many threads at once and see if some of that work should be `async`.

Overall: we're _reporting_ that something is taking over 50ms, due to the environment in almost all cases. If you want to disable that reporting: up the timeout. Or, change the conditions to prevent the timeout. Assuming it's a library issue for _saying_ this stall happens won't solve anything though: the issue is there, we're alerting on it _because we were told to at that threshold_. I hope that description helps.

**Comment by NickCraver** [comment] 2022-01-08 13:21
Closing out to cleanup.

**Closed by NickCraver** 2022-01-08 13:21 UTC
