### ISSUE TITLE
StackExchange.Redis with .Net4.0

### ISSUE THREAD

**Issue by huhm** [StackExchange/StackExchange.Redis#352] opened 2016-02-02 11:48 UTC
I used the install-package StackExchange.Redis command, and I update-package Microsoft.Bcl to 1.1.10.
I'm in VS 2013 targeting .Net 4.0 framework,When I compile this project ,it throws some Errors like:
"The type or namespace name 'StackExchange' could not be found (are you missing a using directive or an assembly reference?)"

**Comment by NickCraver** [comment] 2016-02-02 23:18
Which version of the package are you using? There were a few builds with bad dependencies on the Microsoft.Bcl bits.

**Comment by huhm** [comment] 2016-02-03 04:55
Microsoft.Bcl.1.1.10
Microsoft.Bcl.Async.1.0.168
Microsoft.Bcl.Build.1.0.21
StackExchange.Redis.1.0.488
The Nuget Command:
install-package StackExchange.Redis
update-package Microsoft.Bcl

**Comment by SFLWcry** [comment] 2016-03-01 01:01
I have the same problem 。need help!!!!!

**Comment by huhm** [comment] 2016-03-01 07:21
At last I switch to .NET Framework 4.5

**Comment by edpollitt** [comment] 2016-03-08 14:42
Try installing the Microsoft BCL Portability Pack nuget package

**Comment by NickCraver** [comment] 2016-03-18 10:43
@SFLWcry can you try using a more recent version where we know the dependencies should be resolved correctly? The most updated version is 1.1.572.

**Comment by JobaDiniz** [comment] 2016-03-31 01:08
I also cannot compile the project .net 4.0.
If I install the nuget in a brand new project, with nothing there, it works.
However, we have several projects and some of them have a dependency on some other libraries, which **have a dependency on BCL** *but in other versions*... so I guess the problem is that: different versions of *BCL*

Any solutions for this?

_related issue #371_

**Comment by NickCraver** [comment] 2016-11-20 21:00
This should be resolved in the latest builds, but note: we are also dropping .NET 4.0 support in the 2.x versions of StackExchange.Redis. Most of the enhancements will be async and dependent upon things that .NET 4.0 doesn't have. This won't prevent anyone from referencing a 1.x line for .NET 4.0 work though.

**Closed by NickCraver** 2016-11-20 21:00 UTC
