### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object. Object name: 'RD0003FF6F2022'

### ISSUE THREAD

**Issue by christiankohl-CV** [StackExchange/StackExchange.Redis#1498] opened 2020-06-12 05:44 UTC
We seem to be getting the following issue on occasion in an Azure environment

We are using a site hosted in Azure Web Apps with Azure REDIS
Version 2.0.601 of StackExchange.Redis

Getting the following error randomly - generally have to kill one of the web instances to "fix" it
Any ideas, is this fix in a new version?

Key was: GBHCVTWO-PC:CASHWEB:900:PCP-1033346:0606:1.00:636821095169080876 System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'RD0003FF6F2022'.
at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor1 processor, ServerEndPoint server) at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor1 processor, ServerEndPoint server)
at BusinessObjects.Caching.RedisCacheProvider.StringSet(String key, String value, Nullable`1 expiry)
at BusinessObjects.Caching.RedisCacheProvider.SetWithExpiry[T](String key, T value, TimeSpan expiration)

Exception: Cannot access a disposed object.
Object name: 'RD0003FF6F2022'.
Source: StackExchange.Redis
Stack Trace:
at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor1 processor, ServerEndPoint server) at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor1 processor, ServerEndPoint server)
at BusinessObjects.Caching.RedisCacheProvider.StringSet(String key, String value, Nullable1 expiry) at BusinessObjects.Caching.RedisCacheProvider.SetWithExpiry[T](String key, T value, TimeSpan expiration) Target Site: T ExecuteSyncImpl[T](StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor1[T], StackExchange.Redis.ServerEndPoint)

**Comment by NickCraver** [comment] 2020-06-13 00:09
Indeed some null refs were fixed from extreme races in newer versions - I recommend grabbing the latest: 2.1.55.

**Comment by rakker91** [comment] 2020-10-07 18:30
Christian,

We had a similar problem in AWS EKS caused by autoscaling and a shutdown race condition.  See https://github.com/StackExchange/StackExchange.Redis/issues/1579 for details.

If you've updated to a newer version and are still seeing this, you may want to look for a similar solution.

**Comment by christiankohl-CV** [comment] 2020-10-08 02:19
Thanks @rakker91, will look into it more. 

We have upgraded to 2.1.58 since but not been able to put into production yet. Will keep monitoring and keep your ticket in mind.

**Comment by GabeBigBoxVR** [comment] 2020-10-22 19:14
We recently upgraded to `2.1.58` and we're seeing this in a production environment as well.  We are using these a lot in async code. 

```
I 2020-10-22T18:53:29.393458456Z System.ObjectDisposedException: Cannot access a disposed object.
I 2020-10-22T18:53:29.393497391Z Object name: 'friends-service-production-6d5b888776-fmgrz'.
I 2020-10-22T18:53:29.393508327Z    at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor`1 processor, Object state, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2112
I 2020-10-22T18:53:29.393514859Z    at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.SetAsync(String key, Byte[] value, DistributedCacheEntryOptions options, CancellationToken token)
I 2020-10-22T18:53:29.393529606Z    at BigBoxVR.FriendsService.Services.PlayFabDataCacheService.SetPlayerDisconnectJobId(String requestedPlayFabId, String jobId) in /src/Services/PlayFabDataCacheService.cs:line 169
I 2020-10-22T18:53:29.393547740Z    at BigBoxVR.FriendsService.Services.FriendsListService.StartDisconnectCountdown(String userId) in /src/Services/FriendsListService.cs:line 342
I 2020-10-22T18:53:29.393554699Z    at BigBoxVR.FriendsService.WebSockets.FriendStreamHandler.OnDisconnected(WebSocket socket, String userId) in /src/WebSockets/FriendStreamHandler.cs:line 225
I 2020-10-22T18:53:29.393682492Z    at BigBoxVR.FriendsService.WebSockets.WebSocketManagerMiddleware.Receive(WebSocket socket, String userId, CancellationTokenSource receiveToken, Action`2 handleMessage) in /src/WebSockets/WebSocketManagerMiddleware.cs:line 97
I 2020-10-22T18:53:29.393695795Z    at BigBoxVR.FriendsService.WebSockets.WebSocketManagerMiddleware.Invoke(HttpContext context) in /src/WebSockets/WebSocketManagerMiddleware.cs:line 76
I 2020-10-22T18:53:29.393701422Z    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
I 2020-10-22T18:53:29.393706297Z    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
I 2020-10-22T18:53:29.393711393Z    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
I 2020-10-22T18:53:29.393716886Z    at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)
I 2020-10-22T18:53:29.393721762Z    at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)
I 2020-10-22T18:53:29.393726523Z    at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)
I 2020-10-22T18:53:29.393731743Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
E 2020-10-22T18:53:29.404279786Z Unhandled exception. System.ObjectDisposedException: Cannot access a disposed object.
E 2020-10-22T18:53:29.404334659Z Object name: 'friends-service-production-6d5b888776-fmgrz'.
E 2020-10-22T18:53:29.404341587Z    at StackExchange.Redis.ConnectionMultiplexer.ExecuteAsyncImpl[T](Message message, ResultProcessor`1 processor, Object state, ServerEndPoint server) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ConnectionMultiplexer.cs:line 2112
E 2020-10-22T18:53:29.404348838Z    at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGetAsync(IDatabase cache, String key, String[] members)
```

**Comment by prabhakarreddy1234** [comment] 2021-02-11 09:44
We are still experiencing this issue with `2.2.4`.

**Comment by davejitsu** [comment] 2021-05-19 14:52
Same issue with 2.2.4, Azure Redis, services in k8s and Asp.Net Core 3.1.

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'api-59cfdcfb57-wzdpx'.
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/ConnectionMultiplexer.cs:line 2817
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in /_/src/StackExchange.Redis/RedisBase.cs:line 54
   at StackExchange.Redis.RedisDatabase.HashGet(RedisKey key, RedisValue[] hashFields, CommandFlags flags) in /_/src/StackExchange.Redis/RedisDatabase.cs:line 321
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisExtensions.HashMemberGet(IDatabase cache, String key, String[] members)
   at Microsoft.Extensions.Caching.StackExchangeRedis.RedisCache.GetAndRefresh(String key, Boolean getData)
   at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetString(IDistributedCache cache, String key)

**Comment by NickCraver** [comment] 2021-05-20 01:16
Looking at the cause here, the issue is upstream of us. The `ConnectionMultiplexer` is being disposed of, but then called later as if it's in play - we're just erroring that this happened. We'd need to figure out how it's getting disposed and still later used in `Microsoft.Extensions.Caching.StackExchangeRedis`.

@deepakverma are you aware of this case elsewhere?

**Comment by luisjimenez6245** [comment] 2021-09-02 06:10
we are having the same issue here.
We are trying to connect to an AWS elastic cache and we are getting the same issue. Some of our transactions with redis works, and the others are throwing this exception 


`
at System.Net.Sockets.Socket.SendAsync(SocketAsyncEventArgs e, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.SendAsyncForNetworkStream(Socket socket, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.SendAsyncForNetworkStream(ReadOnlyMemory`1 buffer, SocketFlags socketFlags, CancellationToken cancellationToken)
at System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
Exception.InnerException.InnerException.InnerException.MessageUnable to write data to the transport connection: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'..
Exception.InnerException.InnerException.InnerException.SourceAssemblySystem.Net.Sockets
Exception.InnerException.InnerException.InnerException.StackTraceat System.Net.Sockets.NetworkStream.WriteAsync(ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
at System.Net.Security.SslStream.WriteSingleChunk[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
at Pipelines.Sockets.Unofficial.StreamConnection.AsyncStreamPipe.CopyFromWritePipeToStream() in C:\code\Pipelines.Sockets.Unofficial\src\Pipelines.Sockets.Unofficial\StreamConnection.AsyncStreamPipe.cs:line 149
at System.IO.Pipelines.PipeCompletion.ThrowLatchedException()
at System.IO.Pipelines.Pipe.GetFlushResult(FlushResult& result)
at System.IO.Pipelines.Pipe.PrepareFlush(CompletionData& completionData, ValueTask`1& result, CancellationToken cancellationToken)
at System.IO.Pipelines.Pipe.FlushAsync(CancellationToken cancellationToken)
at System.IO.Pipelines.Pipe.DefaultPipeWriter.FlushAsync(CancellationToken cancellationToken)
at StackExchange.Redis.PhysicalConnection.FlushAsync() in C:\projects\stackexchange-redis\src\StackExchange.Redis\PhysicalConnection.cs:line 288
at StackExchange.Redis.ServerEndPoint.HandshakeAsync(PhysicalConnection connection, TextWriter log) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ServerEndPoint.cs:line 802
at StackExchange.Redis.ServerEndPoint.OnEstablishingAsyncAwaited(PhysicalConnection connection, Task handshake) in C:\projects\stackexchange-redis\src\StackExchange.Redis\ServerEndPoint.cs:line 490
Exception.InnerException.InnerException.MessageSocketFailure (0-read, 0-sent) on
`

**Comment by NickCraver** [comment] 2021-09-07 12:24
For anyone hitting this, please add your details to the upstream lib so we can get a fix ASAP. This isn't something we can fix here (unless we're misunderstanding, always possible) - likely need a behavior tweak in the caching wrapper. Follow along and add info here please! https://github.com/dotnet/aspnetcore/issues/36092

**Comment by NickCraver** [comment] 2022-01-09 01:06
Since this is upstream - closing out to tidy up. We remain happy to assist the upstream authors on using a disposed connection here but hopefully the change isn't too complicated.

**Closed by NickCraver** 2022-01-09 01:06 UTC
