### ISSUE TITLE
Timed out requests stuck in _writtenAwaitingResponse

### ISSUE THREAD

**Issue by AndySverdlov** [StackExchange/StackExchange.Redis#1418] opened 2020-04-01 16:15 UTC
Framework netcoreapp3.1
Library version 2.0.601 (at the moment actually checked out source as of tag 2.0.601)

Hi, I have a problem and I could use some of help debugging it.
The problem we experience is that when an async request to Redis times out for whatever reason, all subsequent requests also throw RedisTimeoutException. This continues for an extended period of time (in production - until we restart a service, really).

I have ConnectionMultiplexer.WriteLog() shooting out status every thirty seconds. When we're stuck in "Everything returns a RedisTimeoutException" mode, "qs" counter is at a non-zero value, even if there are no pending requests, e.g.

> la-la-la.redis.cache.windows.net:6380: int ops=716, qu=0, qs=62, qc=0, wr=0, socks=1; sub ops=93, qu=0, qs=0, qc=0, wr=0, subs=1, socks=1

qs goes down, but very slowly, roughly by 4 a minute. When qs drops to zero, service starts performing fine again. From what I understand, qs is a counter indicating a number of pending messages in _writtenAwaitingResponse queue.

My assumption regarding what goes on is like below.

In https://github.com/StackExchange/StackExchange.Redis/blob/ef5af00d5febd0dd3e4daca397fae84737d44277/src/StackExchange.Redis/PhysicalConnection.cs#L618 message is not removed from _writtenAwaitingResponse queue.
However, when we send a new request and receive a response, we always try matching it to the first message in _writtenAwaitingResponse
https://github.com/StackExchange/StackExchange.Redis/blob/ef5af00d5febd0dd3e4daca397fae84737d44277/src/StackExchange.Redis/PhysicalConnection.cs#L1415
They obviously don't match - I've verified in debug mode that a freshly arriving result is matched to the oldest message in  _writtenAwaitingResponse. Thus we receive a RedisTimeoutException and our request gets stuck at the bottom of queue, among other unanswered requests.

To be frank, I'm a bit stuck at this point and unsure how to proceed since I'm not familiar enough with StackExchange.Redis code base. Could anybody help me out, please?

**Comment by mgravell** [comment] 2020-04-01 16:28
The reason that it isn't removed is that even if a specific command times out, responses on a single connection should still be expected in the same order in which they were received; ultimately, if we *sent* a request, then on the same socket: if we ever get replies, we're still expecting a response from the thing that timed out.

If messages are becoming disconnected, then there are two possibilities:

1. our code is broken in some way and we've dropped/misunderstood a response
2. the provider you're using (azure) has a proxy in the pipe between the client and the actual server, and some permutation of operations and timing is causing us to lose cohesion with the proxy - perhaps because it changed it's inner connection

I will ping the azure folks to see whether the second is a possibility.

However! What I *want* to do is push forward on the planned changes to overhaul how the entire connection backend works - moving from a full multiplexer  into a lease model (same API for callers, only changes internals for now); the lease model has several advantages here, including:

- it avoids problems with large payloads blocking multiple callers
- any broken socket only impacts a single caller
- in scenarios like the above where something times out, we simply doom that indvidual socket and write it off - no persistent state remains that can cause an ongoing problem except for the initial timeout
- no need for synchronization and queue complexity

The problem is getting the time to implement and test these things, especially during the current climate with reduced capacity and increased family requirements etc.

**Comment by AndySverdlov** [comment] 2020-04-01 19:22
Thanks for your quick reply Marc. This aligns well with what I see and makes perfect sense.

Regardless, we need to detect these kinds of situations and handle them gracefully in our application, as you can probably imagine. Is there anything you would suggest? We can potentially afford a few server errors as long as we can recover within a reasonable time. And I'd rather not rely on just increasing the asyncTimeout to a high enough value.

My understanding is that connection pooling may alleviate the problem, but I can't think of a criteria on which to drop a connection. Do you reckon dropping connection as soon as we get first RedisTimeoutException sounds reasonable enough?

**Comment by mgravell** [comment] 2020-04-01 19:58
It is probably overly aggressive to be honest, unless your timeout is
suitably high. Especially in cloud providers - sometimes things simply take
a while. That's the other advantage of us moving the core to be a pool:
even if we lose one connection, others should already be available and
ready to roll - contrast to the multiplexer that can have non-trivial spin
up cost.

**Comment by AndySverdlov** [comment] 2020-04-03 09:48
Just an update to that - the problem stopped being reproducible since yesterday. My local repro doesn't work anymore - even if I get RedisConnectionTimeouts with high qs count, it drops to zero pretty fast. Also errors in a deployed version of application are not causing cascade failure, even though we didn't deploy any code change. Not sure if kind folks from Azure tweaked something from their side, or if my repro is flawed.

**Comment by mgravell** [comment] 2020-04-03 10:19
interesting; I did ping some folks, but I haven't heard anything back yet; keep me informed! my curiosity is piqued

**Comment by NickCraver** [comment] 2022-01-08 15:32
Since this seems solved and a lot more enhancements have gone into more recent versions as well, closing this out to tidy up!

**Closed by NickCraver** 2022-01-08 15:32 UTC
