### ISSUE TITLE
Redis Pub/Sub subscriber to slave server

### ISSUE THREAD

**Issue by bp74** [StackExchange/StackExchange.Redis#321] opened 2015-12-16 10:21 UTC
Hello

I have an unusual use case where i want to do a subscription to a Redis slave server . A subscription to a slave server works fine but the Redis library does not allow it, and the reason is this line of code:

https://github.com/StackExchange/StackExchange.Redis/blob/master/StackExchange.Redis/StackExchange/Redis/RedisSubscriber.cs#L190

It basically overrules the CommandFlags passed to the method and uses DemandMaster. This makes sense if you want to publish messages, but if you only want to listen as a subscriber this is not necessary (i think). Would it be possible to just use the CommandFlags that are passed to the method? If i do this and by using PreferMaster it works perfectly fine because it also connects to a slave.

**Comment by mgravell** [comment] 2015-12-16 14:21
I suspect the problem there also ties into reconnect scenarios; it would be
necessary to track how each thing intends to connect - which is...
complicated, especially if you subscribe more than once to the same name.
It can probably be fixed, but it isn't (I don't think) quite as simple as
it appears on the surface.

On 16 December 2015 at 10:21, Bernhard <notifications@github.com> wrote:

> Hello
>
> I have an unusual use case where i want to do a subscription to a Redis
> slave server A subscription to a slave server works fine but the Redis
> library does not allow it, and the reason is this line of code:
>
>
> https://githubcom/StackExchange/StackExchangeRedis/blob/master/StackExchangeRedis/StackExchange/Redis/RedisSubscribercs#L190
>
> It basically overrules the CommandFlags passed to the method and uses
> DemandMaster This makes sense if you want to publish messages, but if you
> only want to listen as a subscriber this is not necessary (i think) Would
> it be possible to just use the CommandFlags that are passed to the method?
> If i do this and by using PreferMaster it works perfectly fine because it
> also connects to a slave
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/321>.
>



-- 
Regards,

Marc

**Comment by scottyearsley** [comment] 2016-01-23 00:52
Hi, I'm experiencing a similar issue - simply subscribing in a slave is not working. I'm looking to implement a distributed cache/pub-sub using your library (which works ace for everything else) but this is a show stopper, especially as it is working when testing it with ServiceStack.Redis. I'd much prefer to use your library because ServiceStack doesn't seem to support wildcard subscriptions (at least they don't work for me). I really hope you can help :)

**Comment by piccit** [comment] 2016-01-25 14:23
@mgravell is your concern only an issue if you have one client ending up subscribed to different servers? Would it be OK to have a "subscribeSlaveOnly" method that always uses DemandSlave? (puts the burden on the caller and also prevents a single client from subscribing to different servers unless that client specifically mixes and matches the subscribe calls).

**Comment by NKovner** [comment] 2017-07-13 18:53
I ran into this issue in 1.1.603, but it seems to be fixed in 1.2.4.

**Comment by NickCraver** [comment] 2018-09-05 10:44
Since we haven't seen additional interest in this, I'm going to close it out. We did look into it, but the issue is it's an entirely new undefined behavior mechanism that adds a lot of complexity.

As an example, if we have subscriptions to servers A, B, and C where A is master and B and C are slaves, what happens in a failover from A to B where B is now master and A and C are now slaves? Which subscriptions go where? Today, everything goes back to master because master is the only target (and that seems to work for most). When slaves enter, we've got a lot of meta problems that are complex to define and handle. It's important to keep stability and reliability very high, so complicating that code is a downside for sure.

Given the whole of the situation, I'm going to decline this feature unless there's a lot more interest to balance out the complication and work involved.

**Closed by NickCraver** 2018-09-05 10:44 UTC
Labels: area:connection, enhancement
