### ISSUE TITLE
Timeout when calling HashGetAllAsync then SetScan on .NET Core

### ISSUE THREAD

**Issue by innix** [StackExchange/StackExchange.Redis#434] opened 2016-06-28 11:43 UTC
StackExchange.Redis version:
1.1.604-alpha

Platform:
.NET Core 1.0 (Win10 x64)

Problem:
When calling `IDatabase.HashGetAllAsync` followed by `IDatabase.SetScan`, a TimeoutException is thrown.

Reproducible sample:

``` csharp
using System;
using System.Linq;
using System.Threading.Tasks;
using StackExchange.Redis;

public class Program
{
    public static void Main(string[] args)
    {
        Task.Run(RunAsync).Wait();
    }

    private static async Task RunAsync()
    {
        using (var conn = ConnectionMultiplexer.Connect("localhost:6379"))
        {
            var db = conn.GetDatabase();

            HashEntry[] hashEntries = await db.HashGetAllAsync("foo");
            RedisValue[] values = db.SetScan("bar").ToArray();

            Console.WriteLine(hashEntries.Length);
            Console.WriteLine(values.Length);
        }
    }
}
```

project.json:

``` json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        },
        "StackExchange.Redis": "1.1.604-alpha"
      },
      "imports": "dnxcore50"
    }
  }
}
```

To run the sample:

```
dotnet restore
dotnet run
```

Expected result:

```
0
0
```

Actual result:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Timeout performing SSCAN bar, inst: 1, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 22, ar: 0, clientName: LAPTOP (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)) ---> System.TimeoutException: Timeout performing SSCAN bar, inst: 1, queue: 2, qu: 0, qs: 2, qc: 0, wr: 0, wq: 0, in: 22, ar: 0, clientName: LAPTOP (Please take a look at this article for some common client-side issues that can cause timeouts: https://github.com/StackExchange/StackExchange.Redis/tree/master/Docs/Timeouts.md)
   at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)
   at StackExchange.Redis.RedisBase.CursorEnumerable`1.GetNextPageSync(IScanningCursor obj, Int64 cursor)
   at StackExchange.Redis.RedisBase.CursorEnumerable`1.CursorEnumerator.MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Program.<RunAsync>d__1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Program.Main(String[] args)
```

**Comment by niemyjski** [comment] 2016-07-13 03:34
I'm also seeing this. Any idea when a new build will be out?

**Comment by rossipedia** [comment] 2016-07-21 22:59
Possibly a duplicate of #401?

**Comment by NickCraver** [comment] 2016-11-20 20:39
Are you still seeing this on the latest 1.1.608 library? There was a decent change in 1.1.605 that @rossipedia alludes to above.

**Comment by niemyjski** [comment] 2016-11-21 11:58
@NickCraver I haven't tried on .net core in a while but I'm not seeing this on the full framework. When I get back to testing Foundatio on .NET Core I'll let you know if I continue to see this (might be some time).

**Comment by niemyjski** [comment] 2016-11-21 11:59
Could this be related to https://github.com/StackExchange/StackExchange.Redis/issues/450 ?

**Comment by NickCraver** [comment] 2017-02-07 00:26
Marking this as resolved to cleanup, @niemyjski  that one seems to be a bit more mixed in - will go through it on its own.

**Closed by NickCraver** 2017-02-07 00:26 UTC
Labels: needs-info
