### ISSUE TITLE
Unsubscribe Not Working in Redis Pub/Sub: Messages Received After Unsubscription

### ISSUE THREAD

**Issue by ronile21** [StackExchange/StackExchange.Redis#2809] opened 2024-10-24 12:35 UTC
I'm encountering unexpected behavior with Redis Pub/Sub using the subscribe, unsubscribe, and publish methods.
 I'm subscribing to a channel (key), publishing a message, and then attempting to unsubscribe. 
However, after unsubscribing and republishing, my callback function is still being invoked as if the subscriber is still active.

During an implementation of pubSub - I am using subscribe/unsubscribe/publish method, 
i doing on some call of subscribe and publish on stringSet. 

after then i doing unsubscribe - and call the stringSet and publish again - and i get the same action like it is subscribe.
there is no effect on the unsubscribe. 

the code testing: 

    // Arrange
    var key = "TestKey";
    
    ConnectionMultiplexer redisClient = ConnectionMultiplexer.Connect(....);
	byte[] serializedData = ... 

    // Act
    Action<string> callback = (msgKey) =>
    {
        Console.WriteLine($" msgKey {DateTime.Now}");
    };

    RedisValue messagePublish = JsonConvert.SerializeObject(new { Message = "Update", Key = key });

    await redisClient.GetSubscriber().SubscribeAsync(key, (key, message) => callback.Invoke(key!));

    
    await redisClient.GetDatabase().StringSetAsync(key, serializedData);
    await redisClient.GetSubscriber().PublishAsync(key, messagePublish);
    await Task.Delay(500);

    // not work on 
    //await redisClient.GetSubscriber().UnSubscribeAsync(key, callback);
    
    // not work on 
    redisClient.GetSubscriber().UnSubscribe(key, callback);
    
     await Task.Delay(500);

    await redisClient.GetDatabase().StringSetAsync(key, serializedData);
    await redisClient.GetSubscriber().PublishAsync(key, messagePublish);

     // Wait a moment to ensure no message is received
     await Task.Delay(500);

**Comment by mgravell** [comment] 2024-10-24 20:44
Well, that's weird. I'll need to look. Thanks for the example code, much appreciated.

**Comment by mgravell** [comment] 2024-10-25 14:48
I suspect the problem is here:

``` c#
Action<string> callback = (msgKey) =>
{
    Console.WriteLine($" msgKey {DateTime.Now}");
};
...
await redisClient.GetSubscriber().SubscribeAsync(key, (key, message) => callback.Invoke(key!));
...
redisClient.GetSubscriber().Unsubscribe(key, callback);
```

The thing you're subscribing is *not the thing you're unsubscribing*; and if we fix it up to look similar:

``` c#
redisClient.GetSubscriber().Unsubscribe(key, (key, message) => callback.Invoke(key!));
```

then we're *still* not getting an equivalent delegate - in this case, it is a different "target" but a different "method" - you can see this in a runnable example [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoIskgHloAYA+AAjAEMAbb4TsAGs2AXjYAKALYBnAOYBpGAE8AlKJbUA3tTa62tAJziAJACI2MhcraaAIpwwwAKgEtJMAHQA5CAHcAvqYqANzU/qFU1ABunFBsCKJsAGIQEOLigspoFjDS0pyyMGoi7Fy8/EIZyioh0bFsSokpaVVK2e55BUXqHDx8AoKtNRHUhuIAogCOODzS4gjZqrU0ZEYASjAAZjCweGAwUzPccwgeTrGFGItnFzAYw6OrE9Oz8x4AsncAFhAAJtefDA/X4PSJg2hIfR0RhkJhoZjsZriWgMZjw2GlPoVQTFTHlAbBIA==).

---

Try instead:

``` c#
Action<RedisChannel, RedisValue> callback = (key, message) =>
{
    Console.WriteLine($" {key} {DateTime.Now}");
};
```

and pass the *same* delegate (or at least: one with the same "target" and "method", which will count as equal) in both locations.

**Comment by mgravell** [comment] 2024-10-25 14:49
I'm going to go ahead assume that this is indeed the cause - repro locally agrees with this; so: closing

If I'm wrong, we can reopen.

**Closed by mgravell** 2024-10-25 14:49 UTC
Labels: 🪲 bug, ⚙️ area:pub/sub
