### ISSUE TITLE
Subscriptions not working on Mono

### ISSUE THREAD

**Issue by jli416** [StackExchange/StackExchange.Redis#274] opened 2015-09-03 22:16 UTC
Has anyone had success/issues with subscriptions on Mono?  I'm running a c# console app in Mono on Ubuntu using a StackExchange.Redis.dll built on the Ubuntu machine with monobuild.bash.

It doesn't give any errors, but no new messages are received.  Testing with redis-cli on the same box shows that messages are being broadcast and able to be received by this machine.

Exact same code running on Windows works.  Curiously, I'm able to publish messages from the Mono application, and all subscribers receive it except the Mono application.

**Comment by jli416** [comment] 2015-09-03 22:27
Found the problem.  RedisChannel.ToString() throws an exception for some reason in Mono. Workaround is to cast RedisChannel to string instead.

**Comment by NickCraver** [comment] 2016-01-26 03:06
I believe this is also a dupe of #152, closing and merging.

**Closed by NickCraver** 2016-01-26 03:06 UTC
