### ISSUE TITLE
Memory usage when using NRediSearch & StackExchange.Redis 2.0.513

### ISSUE THREAD

**Issue by dme-development** [StackExchange/StackExchange.Redis#1003] opened 2018-11-14 15:27 UTC
We are testing NRediSearch & StackExchange.Redis 2.0.513. When performing searches with NRediSearch which return +-2000 objects (Redis hashsets), we see the memory usage of our dotnet core app increasing rapidly. With each search the memory usage gets higher and higher, easilly reaching 2GB mem usage after a few searches. After a while the memory usages drops little by little.

Is this normal behaviour? I'm assuming you keep the searchresults in memory and clean it after a while?

I don't want to panic, but this behaviour seems worrying to me when this is going to be used in a production environment.

**Comment by NickCraver** [comment] 2018-11-14 15:58
Is this on .NET Core or full framework? For .NET Core: you're not crazy, efficient and equal allocations across the heaps causes some behavior we don't want either, you can track the issue here: https://github.com/aspnet/AspNetCore/issues/3409

**Comment by dme-development** [comment] 2018-11-15 08:17
Yes, it's on .NET Core. 

Do you know if there's any workaround possible for now? I read some things about changing GC config or forcing the GC to run manually? The latter (GC.Collect()) doesn't seem to be doing anything usefull to the memory usage.

**Comment by grisharav** [comment] 2018-12-04 20:19
We are having a similar issue. After upgrading to the 2.0.519 version of the client, our .net core app experienced extremely high RAM usage (over 30 GB). Is there any guidelines we can currently follow to prevent this?

**Comment by mgravell** [comment] 2018-12-06 10:38
@grisharav  can I assume that you're not talking about NRediSearch here? also: is upgrading to 2.0.519 the *only* change you've made? obviously I don't have visibility of your memory - have you done any investigation to see what is holding the memory? Finally: is this running server GC on a higher-core machine? because: yes, that's a known pain point related to .NET Core generally, not specifically this library - please clarify so we can offer guidance

**Comment by grisharav** [comment] 2018-12-06 12:21
Thanks @mgravell, answers below.
- No, we are not using NRediSearch, just the StackExchange.Redis client.
- We saw briefly that we have tens of thousands of 8K buffers which are held by StackExchange.Redis.RawResult[][]
- We are indeed running on a high core machine with a server GC, would appreciate any guidance on the subject.

**Comment by mgravell** [comment] 2018-12-06 12:30
It is very interesting to me that it is `RawResult[][]` - I'll take a look to see whether we should/could make sure we clear the buffers before recycling them

re high-core server GC: yeah, that's an unrelated gotcha; https://blogs.msdn.microsoft.com/maoni/2018/11/16/running-with-server-gc-in-a-small-container-scenario-part-0/ - we've found that switching to desktop GC in some scenarios is far preferable for our memory usage

**Comment by mgravell** [comment] 2018-12-06 12:31
note that these things can interplay: the buffers for `RawResult` here are all pooled/reused, and the pool is weak-referenced, i.e. collectable. So: the *fundamental* problem here is probably: GC not wanting to collect, despite these things *being* collectable

**Comment by grisharav** [comment] 2018-12-06 12:54
Thanks, we will give a try to desktop GC, I will update here next week probably.

**Comment by grisharav** [comment] 2018-12-17 07:39
Hi, sorry for the late response.
So the desktop GC didn't help. I have recorded the .net allocations (sampling) with Perfview, here are the results:
![image](https://user-images.githubusercontent.com/4532463/50072911-8871b980-01df-11e9-9ddc-c66b34580c2f.png)

I'm now working on downgrading the package to 1.2.6 version, will update on the status there. Any additional info I can provide?

**Comment by grisharav** [comment] 2018-12-17 09:56
When we downgraded to version 1.2.6 - the memory consumption is quite low and completely stable. Please advise.

**Comment by grisharav** [comment] 2019-01-20 09:41
Any updates on this?

**Comment by koblaymerve** [comment] 2019-01-31 08:08
We have the same issue also. We use 2.0.5 version of StackExhangeRedis with multiple .net core app threads. Sometimes, we get timeouts from Redis and memory usage increase over 16K. Can you give us any advice to solve this?

**Comment by dbolin** [comment] 2019-01-31 19:58
We have run into what looks to be the same issue when switching Hangfire storage from SQL Server to Redis using the Hangfire.Redis.StackExchange package version 1.8.0, which uses StackExchange.Redis version 2.0.513.

Memory usage on the servers running Hangfire (which is the only thing using redis) increases over time, and while sometimes a large amount of memory is freed at once e.g. 5 GB, eventually the memory allocated by the .NET process exceeds the RAM size and brings the server down.  This happens regardless of how much RAM the machine has and can happen within a few hours if there are several users active.

A typical memory dump shows `RawResult[][]` taking up about 60-70% of the process memory, and 20-30% of the memory as free.

**Comment by Rosevlad** [comment] 2019-02-19 17:22
We are facing similar issue with RawResult eating up lot of memory when using Stackexchange.Redis 2.0.* (Not able to reproduce with 1.2.6). Is this the same issue, or should I create separate one?

I was able to reproduce the issue by creating a console application on .NET Framework 4.6.2 and imlpementing a simplified scenario. Program stops and fails on out of memory exception after eating up more than 3GB (32b console app). There's only 2MB of data in redis. When I lower down iterations and try to continue with some other code, program finishes, but big amount of memory is kept at least for hours during the time I was testing.

static void Main(string[] args)
        {
            MemoryLeakTest().Wait();
        }

        static private async Task MemoryLeakTest()
        {
            var cm = ConnectionMultiplexer.Connect("localhost:6379,allowAdmin=true,abortConnect=false,configCheckSeconds=1");
            var redisDatabase = cm.GetDatabase(9);
            var value = "qwertryuypiuasdfghjjklzxcvbvmnpoiuytreqweasdfghjlkjmnvxcvasdfweqrfhjyuopiukljmnvcfgdswertiuyhgfa";

            // Create set with 20K strings of 100B size. 
            for (int i = 0; i < 20000; i++)
            {
                await redisDatabase.SetAddAsync("set", $"{value}{i}");
            }

            for (int i = 0; i < 20000; i++)
            {
                // Get 2MB set
                RedisValue[] values = await redisDatabase.SetMembersAsync("set");
                // Remove 1 random value
                await redisDatabase.SetRemoveAsync("set", values.FirstOrDefault());
                Console.WriteLine(i);
            }
        }

**Comment by mgravell** [comment] 2019-02-19 20:58
Ok, that's useful - I'll see what I can find

**Comment by mgravell** [comment] 2019-02-25 12:44
k; I've come up with an arena allocation strategy for RawResult buffers; will try integrating it

**Comment by NickCraver** [comment] 2019-03-02 14:09
For anyone who wants to follow along, see #1075 - it's pretty fun

**Comment by mgravell** [comment] 2019-04-02 15:21
The `RawResult[]` changes are deployed in r571, although we will be making an additional deploy in the next few days to address an unrelated performance problem. Since the memory issue is now resolved (I think!): closing this one down.

**Closed by mgravell** 2019-04-02 15:21 UTC

**Comment by yedidyas** [comment] 2020-05-02 21:44
@mgravell  I upgraded to 571.
Before the upgrade, the profiler showed 93% of thread runtime spent on the library worker loop. After the upgrade, things look pretty much the same (87%~). I’m using new relic Real time profiler. 
My problem from the begging was random slow requests on my server. 
Don’t know yet if the upgrade helped  with that since it’s wasn’t deployed to production yet.
Am I missing something with the profiling results interpreting?
Thanks

**Comment by mgravell** [comment] 2020-05-02 22:35
it is indeed a little hard to meaningfully profile the thread pool usage
here, and that isn't a simple thing to comment on. However, long term I
suspect the planned connection pool mode (which doesn't use a thread pool
at all) may resolve any concerns you have here. Prototype worked well -
just need to integrate it.

**Comment by yedidyas** [comment] 2020-05-03 10:20
Thanks for the quick answer,
Is there an estimate for connection pool mode release date?
