### ISSUE TITLE
System.BadImageFormatException after adding NuGet to .NET 4.7.2 project

### ISSUE THREAD

**Issue by max-modesto-visma** [StackExchange/StackExchange.Redis#1638] opened 2020-12-08 15:57 UTC
I have a .NET 4.7.2 project, when I add StackExchange.Redis NuGet I get an error when trying to debug the application, note that build succeeds.

Exception Details:
```
System.BadImageFormatException: Cannot load a reference assembly for execution.
```

Stack Trace:
```
[BadImageFormatException: Cannot load a reference assembly for execution.]

[BadImageFormatException: Could not load file or assembly 'System.IO.Compression' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)]
   System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0
   System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +37
   System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +159
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +80
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +22
   System.Reflection.Assembly.Load(String assemblyString) +29
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +38

[ConfigurationErrorsException: Could not load file or assembly 'System.IO.Compression' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)]
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +726
   System.Web.Configuration.CompilationSection.LoadAllAssembliesFromAppDomainBinDirectory() +196
   System.Web.Configuration.CompilationSection.LoadAssembly(AssemblyInfo ai) +45
   System.Web.Compilation.BuildManager.GetReferencedAssemblies(CompilationSection compConfig) +172
   System.Web.Compilation.BuildManager.GetPreStartInitMethodsFromReferencedAssemblies() +91
   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +111
   System.Web.Compilation.BuildManager.ExecutePreAppStart() +156
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +695

[HttpException (0x80004005): Could not load file or assembly 'System.IO.Compression' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058)]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +660
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +89
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +190
```

I've tried to uninstall, reinstall, manually add different versions of `System.IO.Compression`, but to no avail.

**Comment by mgravell** [comment] 2020-12-08 18:13
Sigh, netfx y u hate me?

What library version are you using?

**Comment by max-modesto-visma** [comment] 2020-12-10 13:32
The problem has come and gone, and is introduced when adding StackExchange.Redis.
If i delete source code for the solution, clone it again, then the problem goes away, but comes back after a while.

Which library do you refer to?

**Comment by mgravell** [comment] 2020-12-10 13:35
This one. Ultimately, we aren't shipping any unmanaged binaries, and I'm pretty sure we're in "any CPU" mode, so I have no clue what you're seeing here. Very odd, so any context that lets me decipher it would be good.

**Comment by max-modesto-visma** [comment] 2020-12-10 15:40
Ok, here's some specifications.

Redis
- NuGet version: 2.2.4
- Runtime version: 4.0.30319
- Version: 2.0.0.0

System.IO.Compression
- NuGet version: 4.3.0
- Runtime version: 4.0.30319
- Version: 4.2.0.0

Let me know what more I can assist with.

**Comment by NickCraver** [comment] 2021-05-20 22:30
Please be sure you're using the latest build tooling, earlier tooling will unfortunately try to use the `netstandard2.0` build instead of the `net461` build as it should here, resulting in the version mismatch you're seeing. Some references to this in #1637 as well.

**Comment by NickCraver** [comment] 2022-01-08 13:32
Can't help here without more info about the environment but the root cause is going to be the combination of libraries as discussed above - hope all is well not, and closing this out to tidy up.

**Closed by NickCraver** 2022-01-08 13:32 UTC
Labels: needs-info
