### ISSUE TITLE
How to configure the cluster？

### ISSUE THREAD

**Issue by 18098924759** [StackExchange/StackExchange.Redis#324] opened 2015-12-26 14:50 UTC

**Comment by mgravell** [comment] 2015-12-26 19:21
Define "configure the cluster", in this context. If you mean server configuration: usually via r`edis-trib.rb`.

**Comment by 18098924759** [comment] 2016-01-13 02:24
How to Connect My cluster server use StackExchange.Redis?
I want to know the StackExchange.Redis connect cluster server medthod.

**Comment by 18098924759** [comment] 2016-01-13 02:27
There is no problem with the configuration of the cluster server.

**Comment by 18098924759** [comment] 2016-01-13 02:29
I Want to know how to access the cluster environment use the StackEchange.Redis.

**Comment by mgravell** [comment] 2016-01-13 07:51
You *should* just need to specify *at least one* (more is fine) of the
nodes in the configuration string, in the usual way. The library *should*
identify redis-cluster, and automatically resolve the remaining nodes, and
initialize the cluster-specific pieces (like key-based sharding).

On 13 January 2016 at 02:30, 18098924759 <notifications@github.com> wrote:

> I Want to know how to access the cluster environment use the
> StackEchange.Redis.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/StackExchange.Redis/issues/324#issuecomment-171137121>
> .
>



-- 
Regards,

Marc

**Comment by NickCraver** [comment] 2016-01-27 11:12
@18098924759 does the above answer your question?

**Comment by MichaCo** [comment] 2016-01-27 11:46
I can confirm what mark said (if that helps closing the issue)
I have a test cluster @home and the client configures itself just fine. Even if I specify only one node, it finds all 12 master and slave nodes automagically :sparkles:

**Comment by NickCraver** [comment] 2016-01-28 02:51
Closing this out since it appears answered - shout and we can reopen if not.

**Closed by NickCraver** 2016-01-28 02:51 UTC
Labels: cluster
