### ISSUE TITLE
Question: Is it possible to specify SendPipeOptions via configuration or code?

### ISSUE THREAD

**Issue by kristianjaeger** [StackExchange/StackExchange.Redis#1043] opened 2019-01-16 23:15 UTC
Question: Is it possible to specify SendPipeOptions via configuration or code?  Should this be done via the ConfigurationOptions?  It looks like SendPipeOptions is private??  Thanks.

**Comment by kristianjaeger** [comment] 2019-01-20 03:49
Thanks @mgravell !  Sorry about the duplicate question.  Appreciate your input.  Cheers.

**Comment by NickCraver** [comment] 2019-03-02 14:30
Closing as a dupe of #1033 :) Please continue discussion there!

**Closed by NickCraver** 2019-03-02 14:30 UTC
