### ISSUE TITLE
Redis Timeout errors with the StackExchange Redis Client

### ISSUE THREAD

**Issue by jadhavsp** [StackExchange/StackExchange.Redis#916] opened 2018-08-14 11:16 UTC
When writing large values to Redis I had a customer observe the following timeout error, Using the StackExchange client:

{"Timeout performing SET MyName, inst: 0, mgr: Inactive, queue: 2, qu=1, qs=1, qc=0, wr=1/1, in=0/0"}

**Comment by jadhavsp** [comment] 2018-08-14 11:27
The error thrown looks something like this: System.TimeoutException: Timeout performing MGET 2728cc84-58ae-406b-8ec8-3f962419f641, inst: 1,mgr: Inactive, queue: 73, qu=6, qs=67, qc=0, wr=1/1, in=0/0
IOCP: (Busy=6, Free=999, Min=2,Max=1000), WORKER (Busy=7,Free=8184,Min=2,Max=8191)

**Comment by jadhavsp** [comment] 2018-08-14 11:28
slowlog get

 1)    1)   "9"
  2)   "1534241188"
  3)   "10372"
  4)      1)    "DEL"
   2)    "5013~ALL_FORMS_ELEMENTS"


 2)    1)   "8"
  2)   "1534241082"
  3)   "10491"
  4)      1)    "DEL"
   2)    "5013~ALL_FORMS_ELEMENTS"


 3)    1)   "7"
  2)   "1534236980"
  3)   "10284"
  4)      1)    "DEL"
   2)    "5013~ALL_FORMS_ELEMENTS"


 4)    1)   "6"
  2)   "1534230855"
  3)   "41346"
  4)      1)    "SET"
   2)    "1001~PATIENT_LIST"
   3)    "[{"CustomerId":51802,"PatientNo":"143440","FullName":"Mohini Patil","Gender":"","RaceEthnicity":"","FirstName":"","MiddleName":"... (10426812 more bytes)"


 5)    1)   "5"
  2)   "1534228523"
  3)   "10088"
  4)      1)    "SET"
   2)    "360~5013~ASDictionary"
   3)    "{"360~5013~PE_23bb61d2~S~EncounterFormID":5288,"360~5013~PE_23bb61d2~S~F_F~Pupils.DARK_OS":"3 mm","360~5013~PE_23bb61d2~S~F_F~Co... (62469 more bytes)"


 6)    1)   "4"
  2)   "1534227164"
  3)   "28896"
  4)      1)    "SET"
   2)    "1001~ALL_USER_MODULE_RIGHTS"
   3)    "{"1":{"ARRA":{"VIEW":[-1]},"AUDITTR":{"VIEW":[-1]},"EFILES":{"ADD":[-1],"DELETE":[-1],"MODIFY":[-1],"VIEW":[-1]},"EA":{"ADD":[3,... (3257357 more bytes)"


 7)    1)   "3"
  2)   "1534227163"
  3)   "19430"
  4)      1)    "SET"
   2)    "1001~ALL_FORMS_ELEMENTS"
   3)    "[{"EncTypeId":3088,"EncFormId":5317,"ElementPageRelId":4681,"ElementId":7196,"ElementName":"Add for Presbyope","ElementInternalN... (31138063 more bytes)"


 8)    1)   "2"
  2)   "1534227142"
  3)   "23511"
  4)      1)    "SET"
   2)    "1001~ENCOUNTER_ELEMENTS_AND_CONTROLS"
   3)    "[{"ElementId":6195,"RecordId":0,"ElementName":"Accommodative Facility","ElementInternalName":"Accommodative_Facility","ElementTy... (1577726 more bytes)"


 9)    1)   "1"
  2)   "1534224658"
  3)   "10433"
  4)      1)    "DEL"
   2)    "5013~ALL_FORMS_ELEMENTS"


 10)    1)   "0"
  2)   "1534178962"
  3)   "20055"
  4)      1)    "ManagementCommand"
   2)    "?"
   3)    "-1"

**Comment by mgravell** [comment] 2018-08-14 18:28
K; those slowlog values aren't terrible (the 5 digit number is microseconds), so: I'm assuming you're simply stuck behind the bandwidth of the large blob. As I say: either multiple connections, or increase the timeout to suit the scenario.

**Comment by mgravell** [comment] 2018-08-20 14:04
It seems unlikely that most blogs would have any data large enough to cause any blockages here.

Frankly, I'd advise "try it on 2.*" (currently in alpha). Even if it doesn't fix it, we have more useful error logging that might do a better job of pointing at the problem. If the issue is sheer bandwidth, then ... I'd be curious to know how big the thing is that you're storing as a single chunk. It may be there are better ways of handling it.

**Comment by jadhavsp** [comment] 2018-08-20 14:11
There is list of object having more than 1000 records. So I'm going to store this list object in redis cache. But while adding or fetching records from cache throws an error like **"The operation has timed out."**. I'm trying to avoid to store large amount of data in cache.  

Thanks for your response. I will try to investigate to resolve this issue.

**Comment by mgravell** [comment] 2018-09-12 09:54
I'm assuming the advice offered addressed this issue; closing out

**Closed by mgravell** 2018-09-12 09:54 UTC
