### ISSUE TITLE
Why is SE.Redis min support for .NET Standard at 1.5 instead of .NET Standard 1.4 or lower?

### ISSUE THREAD

**Issue by PureKrome** [StackExchange/StackExchange.Redis#666] opened 2017-07-21 05:02 UTC
Hi team,

I just noticed today that the min .NET Standard level is 1.5. Any reason why this is ... instead of going to 1.4 or 1.3 ?

I noticed that it also supports older frameworks like 4.5. (out of support so .. meh .. ) and 4.6 ... so if it could support/target 4.6 .. couldn't it then target .NS 1.3 as listed in the [uber matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard)?)

_disclaimer: my .NET Standard knowledge is pitiful_

cheers!

ref:

![image](https://user-images.githubusercontent.com/899878/28449709-6423856c-6e25-11e7-9559-c854e036eec3.png)

**Comment by mgravell** [comment] 2017-07-21 06:38
BufferedStream, basically.

there's a PR to fix this - will look this weekend.

**Comment by PureKrome** [comment] 2017-07-21 12:32
Thank you sir! If you need some (newbie) help, just shout out and I'll try and help/support/etc.

**Comment by jamesmus** [comment] 2017-07-21 16:12
I'll second that!  I've just hit a problem whereby I've had to downgrade an app to NetFx 4.6.1 which is dependent on a NetStandard 1.5 library that's dependent on StackExchange.Redis and I can't downgrade that so that it can  used from the app :-(

**Comment by PureKrome** [comment] 2017-07-30 12:30
Any new info on this @mgravell ?

**Comment by mgravell** [comment] 2017-07-30 13:34
I'll review the existing PR this evening. I had given initial feedback - it
may have changed since - it either didnt ping me (not sure it does,
automatically), or I missed it (which: happens; I'm human)

**Comment by PureKrome** [comment] 2017-07-30 14:47
Thanks Marc - the internets love you!

![](https://media.giphy.com/media/iiS84hOJXh1Pq/giphy.gif)

**Comment by NickCraver** [comment] 2017-09-01 13:19
FYI: That PR has been closed, since `netcoreapp` accepts up to `netstandard1.6`, and I'll get to a `netstandard2.0` release here soon as we can work out testing and Sentinel (getting things testing in a CI way was a substantial time investment).

The workaround was a severe performance detractor that people can easily *mistakenly* install by NuGet resolution rules, so I'm also not a fan of merging it in for a target used forever less going forward. If there's use case for these, can we please see some examples? I'm trying to ascertain if the issue is which `netstandard` implementations map, or an actual gap scenario. That's unclear to me from the comments thus far.

**Comment by NickCraver** [comment] 2018-05-28 01:28
Closing this out to cleanup, `netstandard1.x` is kinda something everyone wants to forget at this point, so not adding any more support for it :)

**Closed by NickCraver** 2018-05-28 01:28 UTC
Labels: platform:NET Core

**Comment by PureKrome** [comment] 2018-05-28 01:38
Np at all @NickCraver 

I should have also noticed the number this issue was given -> 666. Issue was cursed, from the beginning 😈 

![](https://media.giphy.com/media/K2ShlbUvGgD2E/giphy.gif)
