### ISSUE TITLE
Timeout not working as expected - elapsed time way higher than timeout

### ISSUE THREAD

**Issue by zRosenthal** [StackExchange/StackExchange.Redis#1693] opened 2021-02-19 18:53 UTC
I have sifted through a ton of the timeout issues and im not sure any mention the issue im seeing.

I am testing some fallback logic in my application by setting a low timeout and purposefully adding network latency.

This is resulting in exceptions like the following 
`StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 991ms elapsed, timeout is 50ms), command=GET, next: GET XXX, inst: 0, qu: 0, qs: 5, aw: False, rs: ReadAsync, ws: Idle, in: 0, in-pipe: 0, out-pipe: 0, serverEndpoint: 127.0.0.1:6379, mc: 1/1/0, mgr: 10 of 10 available, clientName: XXX, IOCP: (Busy=0,Free=1000,Min=16,Max=1000), WORKER: (Busy=5,Free=32762,Min=16,Max=32767), v: 2.2.4.27433 (Please take a look at this article for some common client-side issues that can cause timeouts: https://stackexchange.github.io/StackExchange.Redis/Timeouts)`

which is expected

however I am confused by `991ms elapsed, timeout is 50ms`, even though the timeout is 50ms it is still waiting until the operation completes to throw the exception

Is there something I am missing? How do I get the exception to be thrown immediately on timeout?

Simplified code I am using
```c#
try {
  var value = await _redis.GetDatabase()
    .StringGetAsync(key);
  return value;
} catch (Exception e) {
  Logger.LogError(e);
}
return await GoGetValueFromOtherPlace()
```

This is resulting in my fallback code not getting triggered until after the redis operation finishes (even though it takes longer than the configured timeout)

Thank you!

**Comment by zRosenthal** [comment] 2021-02-19 19:02
experimenting a bit more - introducing 4000ms of network latency and setting timeout to 1500ms results in exceptions w/ elapsed time < 2000ms

this leads me to believe the exception/timeout handling is realllllllly slow or I have something configured improperly 

Thoughts?

**Comment by xaclincoln** [comment] 2021-03-01 07:57
The default heartbeat period is 1000ms, which is defined in ConnectionMultiplexer.cs by MillisecondsPerHeartbeat constant. It's not possible to config heatbeat check period yet, but should be trivial to implement.

**Comment by zRosenthal** [comment] 2021-04-30 11:51
Is this something we can expose to be configured or maybe choose a more reasonable default

**Comment by NickCraver** [comment] 2021-05-20 01:36
We intentionally only check the timeout on 1000ms intervals (because it's expensive to do so at scale), so the timeouts your seeing are only going to have that level of fidelity (e.g. what you're seeing is expected behavior). Changing the heartbeat which would also ping the server far more often is not a change we'd want to make here.

**Comment by ShaneCourtrille** [comment] 2021-06-16 16:11
We are seeing MUCH higher elapsed compared to timeout so is the system just too busy to run the heartbeat?

StackExchange.Redis.RedisTimeoutException: Timeout awaiting response (outbound=0KiB, inbound=0KiB, 27049ms elapsed, timeout is 7000ms),

**Comment by NickCraver** [comment] 2021-06-23 02:41
@ShaneCourtrille how many busy threads are there when this happens? If your CPU is absolutely slammed, or the timer queue specifically gets slammed, we'll be behind a long train of things the machine is trying to run. Almost always when you see _huge_ delays like that, the thread pool and timer queues are at some insane values of demand.

**Comment by NickCraver** [comment] 2022-01-08 14:40
Closing this out to tidy up - explanations are above around the 1 sec enforcement.

**Closed by NickCraver** 2022-01-08 14:40 UTC
Labels: needs-info, timeout
