### ISSUE TITLE
.Net Client Http Request over api Not Found MapRequestHandler State

### ISSUE THREAD

**Issue by flowdopip** [StackExchange/StackExchange.Redis#265] opened 2015-08-19 08:22 UTC
Hi,

I´m using .Net Client Redis on my Web Api and for any request we check this step over redis:

Redis IsConnected?
KeyExists? if true we return the value from Redis if false we get the data and add the data to the redis!

Now I'm on tests add if call and endpoint over 5000 with the same values and on the middle of the process we have request on MapRequestHandler State that results on 404!

If we remove the Redis the same process works?

Do you have any idea?

**Comment by NickCraver** [comment] 2016-01-28 11:21
How are you using the StackExchange.Redis client? Can you post code? 

The most common thing we see here is *not* reusing the same ConnectionMultiplexer as intended, and instead spinning up one for every request - that creates a lot of overhead and introduces issues with contention.

**Comment by NickCraver** [comment] 2016-11-21 02:01
Closing this out due to no new info to debug with.

**Closed by NickCraver** 2016-11-21 02:01 UTC
