### ISSUE TITLE
StringSet last digit of uint64 value is wrong

### ISSUE THREAD

**Issue by indriApollo** [StackExchange/StackExchange.Redis#1103] opened 2019-03-29 09:59 UTC
I have an issue where StringSet messes up the last digit of my uint64 value.
I want to store 14220525521023800**5** but redis-cli > get key1 returns me 14220525521023800**0**.

See here an example :
```
using System;
using StackExchange.Redis;

namespace redisUint64
{
    class Program
    {
        static void Main(string[] args)
        {
            ulong value = 142205255210238005;
            var conn = ConnectionMultiplexer.Connect("127.0.0.1");
            var db = conn.GetDatabase();
            db.StringSet("key1", value);
            var retVal = db.StringGet("key1");
            Console.WriteLine(retVal);
        }
    }
}
```

Stackexchange.Redis version 2.0.571
Redis server version 5.0.4
.Net Core 2.2
Arch linux 64bit

**Comment by mgravell** [comment] 2019-03-29 10:38
Confirmed; the problem here is that the compiler is actually going `ulong` => `double`, in the lack of `ulong` operators. It is this `double` conversion that loses the precision. It then (internally) does a check to see whether the `double` is actually an integer (`long`) i.e. has no decimal digits, which it is - so it changes back from `double` => `long`.

So what we really need here is a way to recognize `ulong` internally.

**Comment by mgravell** [comment] 2019-03-29 14:16
Specifically, this will impact anything over 53 bits due to the implicit `double` conversion; working on `ulong` implementation

**Comment by mgravell** [comment] 2019-04-08 08:27
merged into master; should be available next public drop

**Closed** 2019-04-08 08:27 UTC

**Comment by mgravell** [comment] 2019-04-09 08:38
r600 is now on nuget; any problems, let me know

**Comment by indriApollo** [comment] 2019-04-09 09:20
Nice, thanks !
