### ISSUE TITLE
Nuget package 1.0.333 installs 1.0.316

### ISSUE THREAD

**Issue by hydrojumbo** [StackExchange/StackExchange.Redis#105] opened 2014-10-13 16:10 UTC
When I use Nuget to install StackExchange.Redis into a VisualStudio 2013 solution, the Version of the dependency referenced by my project is set to 1.0.316.0, not 1.0.333 as Nuget advertises as the latest. The same behavior occurs when acquiring the StackExchange.Redis.StrongName package. 

We are having an issue related to the TimeoutException issues described at https://social.msdn.microsoft.com/Forums/en-US/e4056ea6-11c9-42ac-b486-808d49d380cd/azure-redis-cache-timeouts?forum=azurecache and were hoping to upgrade to 1.0.333 as the forum recommends to see if it addresses our problem.

Is there an issue with the Nuget publication process? I am going ahead with building the latest from the Git repo to see if it solves our actual issue but I wanted to make you aware that it appears something is amiss in the build/publish-to-Nuget pipeline you've got set up.

Thanks,
Alex

**Comment by oatsoda** [comment] 2015-10-22 14:39
I can confirm this is still an issue on the latest version.  Installing the NuGet package for 1.0.481 yields this fantastic entry in my project file :S

    <Reference Include="StackExchange.Redis, Version=1.0.316.0, Culture=neutral, processorArchitecture=MSIL">
      <HintPath>..\packages\StackExchange.Redis.1.0.481\lib\net45\StackExchange.Redis.dll</HintPath>
      <Private>True</Private>
    </Reference>

**Comment by Davidsual** [comment] 2015-11-02 11:56
Still an issue.
NuGet package 1.0.481 
give exception because contains version 1.0.316.0

is there any workaround?

**Comment by NickCraver** [comment] 2016-01-28 03:21
This was an issue with those builds that we can't (due to the nature of NuGet) go back and fix. Using a current version has the correct number. We're sorry the build was botched for a while and didn't notice, unfortunately we can't do much about it other than suggest moving to a newer package.

Closing this out to cleanup because there are a few dupes of the same.

**Closed by NickCraver** 2016-01-28 03:21 UTC
