### ISSUE TITLE
How to build Core rtm for netcoreapp 1.0

### ISSUE THREAD

**Issue by seriouz** [StackExchange/StackExchange.Redis#446] opened 2016-07-12 12:19 UTC
Is it possible to build a netcoreapp 1.0 nuget package of the rtm branch?

**Comment by michaellandi** [comment] 2016-07-14 13:42
I am also interested to know what the plans are to introduce core support.  Is it on the timeline?

Thanks.

**Comment by mgravell** [comment] 2016-07-14 14:08
Paging @NickCraver - did you have a release plan? What more do we need to
do here?

**Comment by NickCraver** [comment] 2016-07-14 14:28
I have a core-rtm branch which AFAIK is ready to go (I've just been busy selling a house here). I've gotten a few reports of timeouts specific to core, so I'd recommend we do another alpha release, and see if people can reproduce the glitches on the RTM packages underneath - thoughts?

**Comment by michaellandi** [comment] 2016-07-14 15:25
Congrats on the new house :).  I have some high volume applications I can test on w/ if you have a release.

**Comment by DamianEdwards** [comment] 2016-07-14 21:16
@NickCraver we'd love to synchronize the shipping of an update to the Redis cache provider for ASP.NET Core with the shipping of your .NET Core support (given we depend on you). If you guys do another preview release to nuget.org, we'll ship a 1.0.1-preview of our package that depends on yours, when we can sync up for a non-preview release after that based on how it lands.

Thoughts?

@muratg

**Comment by NickCraver** [comment] 2016-07-14 22:20
@DamianEdwards I'm still waiting to hear anything on this: https://github.com/dotnet/corefx/issues/4544#issuecomment-230272419 Is there any update? As it stands I'd have to go move all of the core-rtm solution projects around to get .csproj buildable again.

**Comment by muratg** [comment] 2016-07-19 16:22
@NickCraver Are you guys still planning to do another alpha release, and if so, do you have a timeline?

**Comment by NickCraver** [comment] 2016-07-20 00:10
@muratg I'm waiting to hear anything at all from anyone on the .NET Core team on any of the numerous blockers we have currently. https://github.com/dotnet/cli/issues/1342 is another issue that is extremely annoying right now. But it looks like some of these are just closed and never getting fixed. I am admittedly extremely frustrated with .NET Core tooling.

To be blunt: from my view, Microsoft wants us to ship .NET Core packages while simultaneously ignoring the blockers we're hitting with the tooling. I can't spend a large amount of time endlessly fighting tooling here. https://github.com/dotnet/corefx/issues/4544 was last updated 4 months ago. https://github.com/dotnet/cli/issues/1342 was just closed 4 months ago without being fixed.

I'm happy to help, but when about 95-98% of my time (this is really not an exaggeration) spent shipping a .NET Core package is fighting the tooling...yeah, that's just not going to happen. Especially when we're seeing no progress on any issues we're hitting with StackExchange.Redis.

**Comment by gzpbx** [comment] 2016-08-10 14:34
@NickCraver , any update for the new alpha or beta plan ? I know there is 1.1.604-alpha on nuget but it still dependence on rc2 .

**Comment by PMExtra** [comment] 2016-08-15 11:44
@NickCraver Is there any progress?

**Comment by jeremymeng** [comment] 2016-08-23 20:51
Hi @NickCraver, I've submitted a PR https://github.com/StackExchange/StackExchange.Redis/pull/465 to workaround the build issue for existing csproj's.  Please let me know what you think.

**Comment by NickCraver** [comment] 2016-08-24 01:56
@jeremymeng The workaround is different, we were awaiting tooling in 3.5 (not sure if it's in RC). See this comment: https://github.com/dotnet/corefx/issues/4544#issuecomment-233823913 Apologies for the delay here, I'm packing & moving houses and OSS unfortuantely takes a back seat for a while during that process. I hope to be back up and running by the end of next week.

**Comment by jeremymeng** [comment] 2016-08-24 05:00
@NickCraver Got it. I submit another PR instead.

**Comment by shanselman** [comment] 2016-08-30 23:57
Awesome. Looking forward to this. @NickCraver hope the move went well.

**Comment by agoretsky** [comment] 2016-09-09 12:55
Ship it, please)

**Comment by NickCraver** [comment] 2016-09-10 12:08
StackExchange.Redis `1.1.605` based on RTM .NET Core libraries is on NuGet, just unlisted until we can do a bit more testing next week. If you're on .NET Core especially and want to give it a go, it'd be appreciated.

Direct link: https://www.nuget.org/packages/StackExchange.Redis/1.1.605

**Comment by seriouz** [comment] 2016-09-10 12:27
@NickCraver Thank you very much! :smile:  I'll test it right away on monday.

**Comment by NickCraver** [comment] 2016-09-10 12:28
This one was all @mgravell as I'm still working on the new house with all available hours - just trying to pitch in some GitHub help when I can :)

**Comment by seriouz** [comment] 2016-09-10 12:31
Ah okay: @mgravell Thanks for the work! But by the way: You guys are awesome :tada:

**Comment by agoretsky** [comment] 2016-09-10 20:34
@NickCraver, Thank you! Will test it on monday too

**Comment by NickCraver** [comment] 2016-11-20 15:06
Closing this out as we're live on this now :)

**Closed by NickCraver** 2016-11-20 15:06 UTC

**Comment by muratg** [comment] 2016-11-20 18:37
Thanks a lot, Nick!
