### ISSUE TITLE
StackExchange.Redis.RedisTimeoutException

### ISSUE THREAD

**Issue by AminSojoudi** [StackExchange/StackExchange.Redis#1309] opened 2019-12-18 14:26 UTC
Hi, 
I'm using dotnet core 2.2 on Linux using docker with StackExchange.redis 2.0.601 and getting time out exception for a burst of work.

```
StackExchange.Redis.RedisTimeoutException: 
Timeout awaiting response (outbound=1KiB, inbound=0KiB, 20873ms elapsed, timeout is 5000ms),
command=EXISTS,
next: EXISTS BurnedGameTickets~tYNbv7,
inst: 0,
qu: 0,
qs: 5,
aw: False,
rs: ReadAsync,
ws: Idle,
in: 20,
in-pipe: 0,
out-pipe: 0,
serverEndpoint: Unspecified/cacheRedis:6380,
mgr: 9 of 10 available,
clientName: game-server,
IOCP: (Busy=0,Free=1000,Min=2,Max=1000),
WORKER: (Busy=6,Free=32761,Min=2,Max=32767),
```
Using `ThreadPool.SetMinThreads` will fix the issue, but should I use it? 
As I'm using version 2.* I think it's a bug.

> https://stackexchange.github.io/StackExchange.Redis/Timeouts

**Comment by KamranShahid** [comment] 2019-12-24 08:59
Yes. It is due to minthread. you can set it your code or .csproj file
One more advice is to update your project from 2.2 to 3.1

**Comment by AminSojoudi** [comment] 2019-12-26 03:54
@KamranShahid  What happened in 3.1 that fixes this issue? Is it a bug from StackExchange.Redis or it is a bug from dotnet?

**Comment by KamranShahid** [comment] 2019-12-26 07:58
> @KamranShahid What happened in 3.1 that fixes this issue? Is it a bug from StackExchange.Redis or it is a bug from dotnet?

I am not saying that something fixed in 3.1 version. I have recently upgraded my .net 2.x version application to 3.1 and faced lots of things which eventually i were able to fixed. As .net 2.2 was not a LTS release so my advice is to upgrade to 3.1 to get what ever performance benefit of latest version and avoid your future work of up-gradation.

**Comment by wjdavis5** [comment] 2019-12-27 22:12
Another way to solve the problem is to Pool multiple IConnectionMultiplexors. This was the route that we use in our production apps where we push redis to around 80k tps

https://github.com/wjdavis5/RedisPooler

**Comment by KamranShahid** [comment] 2019-12-28 07:25
> Another way to solve the problem is to Pool multiple IConnectionMultiplexors. This was the route that we use in our production apps where we push redis to around 80k tps
> 
> https://github.com/wjdavis5/RedisPooler

Interesting.
I use the lazy  connection multilexer solution like
[(https://stackoverflow.com/questions/28792196/how-does-connectionmultiplexer-deal-with-disconnects)]
will try your solution as well

**Comment by NickCraver** [comment] 2020-03-15 15:06
Is it possible this container is starved for CPU when the burst happens? We can see 20 bytes in the inbound wire with 5 commands waiting to be processed, but 6 threads also isn't that high. Does `SLOWLOG` on the Redis instance indicate a stall on that side?

**Comment by AminSojoudi** [comment] 2020-03-15 15:40
@NickCraver , Nope the `SLOWLOG` returns an empty set. But I think I have to mention that I'm getting these timeouts on my development machine, which not only serving my services but also running the burst of work which is using `System.Threading.Tasks `library.

**Comment by NickCraver** [comment] 2020-03-20 01:33
@AminSojoudi ah gotcha - what kind of load are we talking about, and on what kind of machine? And on which version of .NET/.NET Core?

**Comment by NickCraver** [comment] 2021-05-20 01:56
Without more info here - closing this out to cleanup.

**Closed by NickCraver** 2021-05-20 01:56 UTC
Labels: needs-info
