### ISSUE TITLE
Error:UnableToResolvePhysicalConnection with version StackExchange.REdis 1.1.603

### ISSUE THREAD

**Issue by SachinNetweb** [StackExchange/StackExchange.Redis#457] opened 2016-07-29 12:38 UTC
Hi  @Marc & @NickCraver

Getting below exception. I am using latest stackExchange.Redis assembly 1.1.603 using .Net framework 4.6.1 (VS 2015).

```
An exception of type StackExchange.Redis.RedisConnectionException occurred and was caught.
Source:StackExchange.Redis;
Message:UnableToResolvePhysicalConnection on EXISTS;
Target:T ExecuteSyncImpl[T](StackExchange.Redis.Message, StackExchange.Redis.ResultProcessor`1[T], StackExchange.Redis.ServerEndPoint);

StackTrace:  
 at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server)  
 at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) 
 at StackExchange.Redis.RedisDatabase.KeyExists(RedisKey key, CommandFlags flags)
 at ePlus.OneSource.StackExchangeRedis.StackExchangeRedisCache.RedisSetString(String key, String stringValue)

Error in RedisSetString(key=System.String key, stringValue=System.String stringValue, );
StackExchange Redis Cache Library
```

**Comment by NickCraver** [comment] 2016-11-20 15:01
Likely duplicate of #469

**Closed** 2018-05-28 12:31 UTC
Labels: area:connection, duplicate
