### ISSUE TITLE
Diagnosing timeout exceptions where "qu = 2" but "qs = 0" and "qc = 0"

### ISSUE THREAD

**Issue by TheCloudlessSky** [StackExchange/StackExchange.Redis#351] opened 2016-02-01 17:26 UTC
We are periodically getting exceptions similar to the following:

```
Timeout performing EXEC, inst: 1, mgr: ExecuteSelect, err: never, queue: 2, qu: 2, qs: 0, qc: 0,
wr: 0, wq: 0, in: 0, ar: 0, clientName: <our_host_name>, IOCP:(Busy=0,Free=1000,Min=1,
Max=1000),WORKER: (Busy=2,Free=32765,Min=1,Max=32767)
```

The **qu is always > 0** and **qs and qc are always 0**. The `mgr` is usually `ExecuteSelect` (it was `CheckForStaleConnections` for one exception).

Our investigation leads us to believe that this is a bug in StackExchange.Redis.

---
## Background

Our app is a MVC 5.2.3 (.NET 4.5.2) app running on Server 2008 R2 (IIS 7.5) on Amazon EC2.

We only use **synchronous commands** because we use Redis behind a lot of interfaces that we don't own (and are themselves synchronous). For example:
- an MVC [`ITempDataProvider`](https://github.com/TheCloudlessSky/Harbour.RedisTempData)
- an NHibernate [Cache](https://github.com/TheCloudlessSky/NHibernate.Caches.Redis)

Here's how the `ConnectionMultiplexer` is created for our app as a singleton (Ninject is used for DI):

``` csharp
public ConnectionMultiplexer BuildConnectionMultiplexer()
{
    var config = new ConfigurationOptions();
    config.EndPoints.Add(masterHostAndPort);
    config.SyncTimeout = 2000;
    config.AbortOnConnectFail = false;
    config.ResolveDns = false;

    var connectionMultiplexer = ConnectionMultiplexer.Connect(config, connectionMultiplexerLogWriter);
    connectionMultiplexer.PreserveAsyncOrder = false;

    return connectionMultiplexer;
}
```

More info:
- The exceptions always occur at low usage (almost 0 users) period of the day.
- Our Redis instance is a cache.m3.medium ElastiCache on Amazon.
- Our Redis instance uses Amazon's Multi-AZ (replication).
- The latency between our web servers and Redis is _always_ < 40ms (worst case).
- Redis AOF and RDB are _not enabled_.
- The `SLOWLOG` always has entries <= 50ms.
- We have a load balancer (HAProxy) that does round-robin between two web servers (web01 and web02). HAProxy does a health check to `GET /health` which does `IDatabase.Ping()` (this is where our exceptions occur).
- When the timeout occurs, other incoming requests throw more Redis exceptions because the `ConnectionMultiplexer` hasn't reconnected until about 3-4 seconds later (obviously, this makes sense).
## Analysis

Since we've started tracking this, we've received the exception on the following dates:
- December:
  - 10 (web01 _and_ web02)
  - 13 (web01)
  - 15 (web01 _and_ web02)
  - 20 (web02)
  - 29 (web02)
  - 30 (web02)
- January:
  - 14 (web02 _and_ web02)
  - 18 (web02)
  - 22 (3 times for web02)
  - 30 (web02)

Sometimes, 2 weeks will go by where an exception doesn't occur. During this time we may have deployed our app and recycled our IIS instances.

If we test Redis timeouts with something like `DEBUG SLEEP 5`, we get totally different exceptions with `qs > 0`. This makes sense because the commands are network bound (or at least they've left SE.Redis) and the server is hung for 5 seconds.

Graphing CPU/memory/network for web servers and our Redis instance does not show any weird spikes or anomalies. We know, for example, that the network isn't saturated. The CPU for web servers is 2 - 3% and for Redis it's ~1.5 - 2%.

We also used the `TextWriter` parameter of the `ConnectionMultiplexer`, but there is nothing out of the ordinary in the created log. [Here's an example](https://gist.github.com/TheCloudlessSky/42e44d885f5f93a0b633) since our last deployment on January 25. An exception occurred on January 30, but there isn't anything useful.

We have _not_ tried recompiling StackExchange.Redis with VERBOSE enabled because it could degrade the performance of our app in production.

When an exception occurs, we get roughly the same data for each exception:
- `ConnectionMultiplexer.GetStatus()`. For example:
  
  ```
  <our_redis_host>:6379: Standalone v2.8.23, master; keep-alive: 00:01:00; int: Connecting; sub: ConnectedEstablished, 1 active
  <our_redis_host>:6379: int ops=6876693, qu=2, qs=0, qc=0, wr=0, sync=8731846, async=2, socks=2; sub ops=7363, qu=0, qs=0, qc=0, wr=0, subs=1, sync=7363, socks=1
  Circular op-count snapshot; int: 6876607+19+10+10+10+10+10+10+5+1+1=6876693 (8.60 ops/s; spans 10s); sub: 7362+1=7363 (0.10 ops/s; spans 10s)
  Sync timeouts: 1; fire and forget: 1041130; last heartbeat: 0s ago
  ```
- `ConnectionMultiplexer.GetStormLog()`. For example:
  
  ```
  0:GET __Booksleeve_TieBreak
  PING
  Circular op-count snapshot: 6876607+19+10+10+10+10+10+10+5+1+1=6876693 (8.60 ops/s; spans 10s)
  ```
- The `exception.Data`. For example:
  
  ```
  redis-command = EXEC
  redis-server = <our_redis_host>:6379
  Redis-Message = EXEC
  Redis-Instantaneous = 1
  Redis-Manager-State = ExecuteSelect
  Redis-Last-Error = never
  Redis-Queue-Length = 2
  Redis-Queue-Outstanding = 2
  Redis-Queue-Awaiting-Response = 0
  Redis-Queue-Completion-Outstanding = 0
  Redis-Active-Writers = 0
  Redis-Write-Queue = 0
  Redis-Inbound-Bytes = 0
  Redis-Active-Readers = 0
  Redis-Client-Name = WEB02
  Redis-ThreadPool-IO-Completion = (Busy=0,Free=1000,Min=1,Max=1000)
  Redis-ThreadPool-Workers = (Busy=2,Free=32765,Min=1,Max=32767)
  Redis-Busy-Workers = 2
  ```

However, these logs don't point to anything out of the ordinary (other than outstanding > 0 and awaiting response/completion outstanding = 0).

---

In the past few weeks we've been starting to suspect that StackExchange.Redis has a bug. A few years ago, we switched away from [ServiceStack.Redis](https://github.com/ServiceStack/ServiceStack.Redis/tree/v3/). We decided to add it back to the health check of our web app (that's called from HAProxy `GET /heath`):

``` csharp
public class HealthController
{
    public ActionResult Index()
    {
        // ...snip... other health checks

        try
        {
            serviceStackRedis.Client.Ping();
        }
        catch (Exception e)
        {
            // Getting an error here *and* via StackExchange.Redis will mean
            // the timeouts are caused by *Redis* and not any of our libraries.
            // So, it's important to swallow here and let StackExchange.Redis
            // attempt a ping.
            log.Error(e, "Failed to Ping Redis with ServiceStack.Redis.");
        }

        stackExchangeRedisClient.Ping();

        return new HttpStatusCodeResult((int)HttpStatusCode.OK);
    }
}
```

When the StackExchange.Redis timeout occurs, there are _no logs for ServiceStack.Redis_. This leads us to believe:
- there doesn't seem to be a problem with ServiceStack.Redis since it doesn't throw any exceptions.
- our Redis instance isn't experiencing any problems at the time.
- StackExchange.Redis is the only piece to fail.

---

I was originally hoping #279 would fix this if the `ResultBox` was somehow still locked, but we updated to 1.1.553 and the exception still occurred (January 30). Also, it seems it was only a fix for async commands.

I've dug into the source of StackExchange.Redis but I can't see an obvious problem. Everything inside of `ConnectionMultiplexer.ExecuteSyncImpl<T>()` makes sense:
1. Locking the `ResultBox`.
2. Pushing the message to the bridge.
3. Waiting on the `ResultBox` to be unlocked by `ResultBox.TryComplete()`.

My guess is that there is some sort of race condition where a lock is held on a shared `ResultBox` and the `Monitor.Wait()` causes the timeout to occur. But, I don't understand enough of the code to keep digging.

Thankfully, because this always occurs in a low-usage period of our app, no users have been directly affected. I'm willing to provide as much information/diagnostics as possible to help get this fixed.

**Comment by GoodMirek** [comment] 2016-05-05 15:31
Our StackExchange.Redis is 1.0.488.
I see the similar behavior, just in our case it is GET instead of EXEC:
Timeout performing GET global_store_shop.testdomain.com, inst: 1, mgr: ExecuteSelect, err: never, queue: 2, qu: 2, qs: 0, qc: 0, wr: 0, wq: 0, in: 0, ar: 0, IOCP: (Busy=3,Free=997,Min=1,Max=1000), WORKER: (Busy=1,Free=2046,Min=1,Max=2047), clientName: WIN-TEST

It is very often accompanied / followed by bunch of exceptions:
SocketFailure on GET

Have you found any root cause / solution / workaround?

**Comment by TheCloudlessSky** [comment] 2016-05-05 16:43
@GoodMirek According to Amazon, the root cause for us was a bad host. We were instructed to re-create our ElastiCache nodes. However, we're still seeing timeouts about once a week even after re-creating the ElastiCache nodes on new hosts. No workaround yet.

**Comment by NickCraver** [comment] 2016-11-20 19:47
Related: #450

**Comment by NickCraver** [comment] 2018-05-28 02:29
Closing this out since the root cause was not library related here.

**Closed by NickCraver** 2018-05-28 02:29 UTC
Labels: area:connection, area:failover, timeout
