### ISSUE TITLE
Add logging support via Common.Logging 

### ISSUE THREAD

**Issue by shatl** [StackExchange/StackExchange.Redis#164] opened 2015-02-17 00:08 UTC
Replace TextWriter with Common.Logging.

This will add more flexibility for managing internal logging.

**Comment by NickCraver** [comment] 2016-01-25 14:46
I'm not sure we'd want to do this since for 2 reasons:
a) it adds a dependency
b) the logging approaches (providers) are changing in .Net Core...and unfortuantely are specific to ASP.Net Core at the moment. I'm not sure if they'll move to being more general or not.

**Comment by MichaCo** [comment] 2016-01-25 14:59
@NickCraver I have a similar problem for my caching library and I'm currently working on implementing it: 
I ended up writing a very thin logging layer in my core stack which has no dependencies at all. And now I have another project implementing the cache using the new ASP.NET Core implementation. 
But you don't have to use it and you could write other LogFactories if needed.
Works pretty awesome so far. I can show you more details if you want

**Comment by NickCraver** [comment] 2016-01-25 15:06
@MichaCo the issue is without the Assembly Neutral Interfaces proposal (or something similar) is you just can't share without a common dependency. We *really* wish ANIs would have landed in .Net Core, but it's too late now since that requires CLR support.

I'm all for seeing details on yours, but I don't see a way around the reference dependency unless you're lowering to duck typing and making your own anyway...which defeats the point.

**Comment by MichaCo** [comment] 2016-01-25 20:40
@NickCraver My goal was that I don't have logging library deps everywhere in all packages.
I tried to keep it really simple and created [just the interfaces](https://github.com/MichaCo/CacheManager/tree/master/src/CacheManager.Core/Logging) I need in my base package, together with an empty implementation which does nothing (which is used if no other LoggerFactory gets defined through configuration). This way I can implement logging where I want without having any dependencies to Microsoft.Extensions...

Then I have [a concrete implementation which uses Microsoft.Extensions.Logging](https://github.com/MichaCo/CacheManager/blob/master/src/CacheManager.AspNetCore.Logging/AspNetLoggerFactory.cs).
That's just a wrapper around the external logger...
I kept my interface pretty much exactly like the Microsoft one, but that's up to you.
Works pretty nice. So if someone wants e.g. NLog logging, they just install the additional AspNetCore package and configure it -> in my case this [looks like this...](https://github.com/MichaCo/CacheManager/blob/master/test/CacheManager.Config.Tests/Program.cs#L21)
I guess you could do pretty much the same

**Comment by chester89** [comment] 2016-01-26 07:29
+1 for this

**Comment by shatl** [comment] 2016-01-27 20:46
@MichaCo Common.Logging doing pretty much the same https://github.com/net-commons/common-logging/blob/master/src/Common.Logging.Core/Logging/ILog.cs.

Basically even a logger interface mentioned by you would be a good improvement since it provides message severity.

**Comment by NickCraver** [comment] 2016-01-28 02:48
What I think is a more likely direction here is using `Microsoft.Extensions.Logging`. I've asked for formal clarification of scope here: https://github.com/aspnet/Logging/issues/349

Using a *very* common interface like that which should gain much wider adoption will be a better direction to support. The thing Common.Logging has going for it is adoption - I think the core libraries by Microsoft can easily beat that and improve the situation. Absent Assembly Neutral Interfaces, being universally available with with as few dependencies as possible is the next best thing.

**Comment by ejsmith** [comment] 2016-02-21 16:29
I am trying to figure out a plan for my library as well.  So if we add Microsoft.Extensions.Logging to our library, it seems like the users of our library would be flooded with a bunch of messages that they probably don't want unless they were to explicitly change the logging level for my libs logging categories. That seems like a PITA for normal users. I wish we could set default logging levels in the lib and they would have to override those levels to see our libs messages.

**Comment by NickCraver** [comment] 2016-11-20 21:52
In the .NET Core world of a bajillion dependencies (and the movement towards fewer packages), I think utilizint `Microsoft.Extensions.Logging` in v2 may be a good move. Hmmmm, I should make a Version 2 planning issue and link this. So doing that: #528

**Comment by NickCraver** [comment] 2018-05-28 02:37
Closing this out to cleanup, tracked in #528.

**Closed by NickCraver** 2018-05-28 02:37 UTC
Labels: enhancement

**Comment by vit-svoboda** [comment] 2020-10-19 15:34
I can't find anything related to logging in #528. Am I missing something or it fell through the cracks? Version 2.1.* still seems to be leveraging the original `TextWriter` for logging.

**Comment by NickCraver** [comment] 2020-10-19 23:55
@vit-svoboda We had this, but decided to not go in that direction and so did not include it in the final 2.x overhaul. There remain no plans to take a dependency here, though if you want to use a `TextWriter` adapter, you can do so!
