### ISSUE TITLE
Remove Keys by Pattern or Regex

### ISSUE THREAD

**Issue by nreddipalle** [StackExchange/StackExchange.Redis#1526] opened 2020-07-08 20:39 UTC
We currently using 1.2.6 version and using the below code to remove keys by pattern or regex expression and noticing performance issues during these operations.

```
public void RemoveByPattern(string pattern)
        {
            try
            {
                database.ScriptEvaluate(@"for _,k in ipairs(redis.call('keys', ARGV[1])) do 
                    redis.call('del', k) 
                end", null, new RedisValue[] { pattern }, CommandFlags.FireAndForget);
            }
            catch (Exception ex) { RedisCacheFactory.LogRedisException(ex); }
        }
public void RemoveByRegex(string regex)
        {           
            try
            {
                var ep = client.GetEndPoints();
                var server = client.GetServer(ep.First());
                var keys = server.Keys(0, "*", 100).Select(k => (string)k); 
            var targetKeys = keys.Where(k => Regex.IsMatch(k, regex)).ToList();
            if (targetKeys.Any())
            {
                database.KeyDelete(targetKeys.Select(k => (RedisKey)k).ToArray(), CommandFlags.FireAndForget);
            }
        }
            catch (Exception ex) { RedisCacheFactory.LogRedisException(ex); }
        }
```

Now we are planning to upgrade our version to 2.1.58, wondering if there is a better way to perform these operations without affecting performance.

Thanks.

**Comment by mgravell** [comment] 2020-07-08 21:04
There's no way of beating about the bush: what you're doing is fundamentally harmful to the server. The library won't matter - the problem is the Lua itself. There simply isn't a good way to do what you want right now. In the future, threaded modules might be an option, but that's a "C++ on the server itself" thing. You can use scan from the client, but that involves a lot of round trips, etc

**Comment by nreddipalle** [comment] 2020-07-08 22:14
@mgravell any example on how to do the above operations using scan.

**Comment by mgravell** [comment] 2020-07-08 23:11
Short answer: IServer => Keys => batchify => KeyDelete. I can give a longer answer tomorrow.

**Comment by nreddipalle** [comment] 2020-07-09 01:31
Thank you @mgravell

**Comment by mgravell** [comment] 2020-07-09 06:46
Here's a longer version - completely untested, but should give an idea:

``` c#
public static async ValueTask KeyDeleteByPatternAsync(
    this ConnectionMultiplexer multiplexer,
    RedisValue serverGlob, Regex clientRegex = null,
    int database = -1, int batchSize = 128)
{
    // there may be multiple endpoints behind a multiplexer
    var endpoints = multiplexer.GetEndPoints();
    var db = multiplexer.GetDatabase(database);
    var batch = new List<RedisKey>(batchSize);

    foreach (var ep in endpoints)
    {
        // SCAN is on the server API per endpoint
        var server = multiplexer.GetServer(ep);

        // it would be *better* to try and find a single replica per
        // primary and run the SCAN on the replica, but... let's
        // keep it relatively simple
        if (server.IsConnected && !server.IsReplica)
        {
            await foreach (var key in server.KeysAsync(database, serverGlob).ConfigureAwait(false))
            {
                if (clientRegex is null || clientRegex.IsMatch(key))
                {
                    // have match; flush if we've hit the batch size
                    batch.Add(key);
                    if (batch.Count == batchSize) await FlushBatch().ConfigureAwait(false);
                }
            }
            // make sure we flush per-server so we don't cross shards
            await FlushBatch().ConfigureAwait(false);
        }
    }

    Task FlushBatch()
    {
        if (batch.Count == 0) return Task.CompletedTask;
        var keys = batch.ToArray();
        batch.Clear();
        return db.KeyDeleteAsync(keys);
    }
}
```

**Comment by nreddipalle** [comment] 2020-07-09 22:36
Thank you @mgravell . 
When I am upgrading from Stackexchange.Redis.StrongName 1.2.6 to StackExchange.Redis 2.1.58, its complaining that IProfiler interface doesn't exist with new version. Is it deprecated in newer version..

```
public class RedisProfiler : IProfiler
    {
```

**Comment by mgravell** [comment] 2020-07-10 05:45
Yes, this API changes in V2:
https://stackexchange.github.io/StackExchange.Redis/Profiling_v2.html

**Comment by nreddipalle** [comment] 2020-08-07 16:10
@mgravell I am getting errors at these lines after upgrading.. what are the equivalents to these in V2??

```
public class RedisProfiler : **IProfiler**
var prof = HostContext.TryResolve<**IProfiler**>() as RedisProfiler;
fact.client.**BeginProfiling**(ctx);
fact.client.**FinishProfiling**(ctx).ToList();
public IEnumerable<**IProfiledCommand**> Timings
RedisCacheFactory(**IProfiler** profiler, AppSettings settings)
```

**Comment by mgravell** [comment] 2020-08-07 17:22
https://stackexchange.github.io/StackExchange.Redis/Profiling_v2.html

**Comment by nreddipalle** [comment] 2020-08-09 10:44
Thanks @mgravell , one more question. Is float datatype removed from RedisResult Class. I am seeing the following error after upgrade

![image](https://user-images.githubusercontent.com/28302399/89730331-a8d13600-da0b-11ea-9755-83d61d02a27b.png)

Error	CS0457	Ambiguous user defined conversions 'RedisResult.explicit operator double(RedisResult)' and 'RedisResult.explicit operator long(RedisResult)' when converting from 'RedisResult' to 'float'

**Comment by mgravell** [comment] 2020-08-09 11:51
This is probably a case of something having been added, not something
having been removed - probably the "long" operator. To resolve this
locally, try "(float)(double)value". Long term, we can add a float
conversion operator that does the same.

**Comment by nreddipalle** [comment] 2020-08-10 15:42
Thanks

**Comment by nreddipalle** [comment] 2020-11-03 07:14
@mgravell we successfully upgraded the redis version from 1.2.6 to 2.1.58 but unfortunately noticed massive performance drop in our app. Our app response time(s) almost tripled compared to prev version and reverting it definitely brought it back to normal. We are using Azure Redis Cache as our Caching instance. Anyone reported similar performance issues and any work in progress around the same. We would really like to revisit this if the next version fixes our performance issues.

**Comment by ericsampson** [comment] 2020-12-12 01:06
@nreddipalle is there any more information that you can provide (timing of various operations on 1.x vs 2.x) ?

**Comment by NickCraver** [comment] 2022-02-20 23:19
Tracking performance issues elsewhere, so closing this issue itself out to tidy up.

**Closed by NickCraver** 2022-02-20 23:19 UTC
