### ISSUE TITLE
Occasaional Timeout on EXPIRE after adding (Server very low load)

### ISSUE THREAD

**Issue by andsee** [StackExchange/StackExchange.Redis#1037] opened 2019-01-08 12:21 UTC
Around 4 times a day I will get a timeout caused by the expire in the following code:

        public static async Task Add(string id)
        {
            int time = Redis.DateTimeToTimestamp(DateTime.UtcNow);
            string key = GetKey(time); // Returns a key based on roiunded time such as 'Stories:599961600'
            var db = MyCode.Redis.GetDatabase();
            await db.SortedSetAddAsync(key, id, time);
            await db.KeyExpireAsync(key, TimeSpan.FromDays(30));
        }

I was having this issue with version 1.2.6 of StackExchange.Redis and 3 of Redis but have since upgraded to 2.0.519 of StackExchange.Redis and 4.0.10 of Redis with default configuration from AWS Elasticache.

The timeout is always redis_command: EXPIRE Stories:xxxxxxxx where xxxxxxxx is the current rounded time.

I've set the Redis server's slowlog to list anything taking longer than 2500ms and it is not reporting anything to do with this.

The server (AWS Elasticache cache.t2.micro) is at 1% CPU and goes up to 200k bytes

The server is processing 1000's of other commands throughout the day without issue.

The following shows the server metrics for the last 24 hours:
![image](https://user-images.githubusercontent.com/1597978/50829599-eb68f300-133c-11e9-977a-ddd3775af816.png)

And the foillowing the same 24 hour period showing the 5 occurances of this exception:
![image](https://user-images.githubusercontent.com/1597978/50829868-caed6880-133d-11e9-964c-994861895fb8.png)

# Timeout at 08:46:16
Redis_Busy_Workers:7
Redis_Client_Name:ip-10-134-195-90
Redis_Inbound_Bytes:25
Redis_Instantaneous:0
Redis_Manager:10 of 10 available
Redis_Message:EXPIRE Stories:600220800
Redis_Queue_Awaiting_Response:10
Redis_Server_Endpoint:Unspecified/ec2-xx-xxx-xxx-215.compute-1.amazonaws.com:6379
Redis_ThreadPool_IO_Completion:(Busy=0,Free=1000,Min=2,Max=1000)
Redis_ThreadPool_Workers:(Busy=7,Free=32760,Min=2,Max=32767)
Redis_Version:2.0.519.65453
redis_command:EXPIRE Stories:600220800
redis_server:ec2-xx-xxx-xxx-215.compute-1.amazonaws.com:6379
request_sent_status:Sent

# Timeout at 06:26:26
Redis_Busy_Workers:9
Redis_Client_Name:ip-10-134-195-90
Redis_Inbound_Bytes:45
Redis_Instantaneous:0
Redis_Manager:10 of 10 available
Redis_Message:EXPIRE Stories:600220800
Redis_Queue_Awaiting_Response:12
Redis_Server_Endpoint:Unspecified/ec2-xx-xxx-xxx-215.compute-1.amazonaws.com:6379
Redis_ThreadPool_IO_Completion:(Busy=0,Free=1000,Min=2,Max=1000)
Redis_ThreadPool_Workers:(Busy=9,Free=32758,Min=2,Max=32767)
Redis_Version:2.0.519.65453
redis_command:EXPIRE Stories:600220800
redis_server:ec2-xx-xxx-xxx-215.compute-1.amazonaws.com:6379
request_sent_status:Sent

# Timeout at 16:16:25
Redis_Busy_Workers:9
Redis_Client_Name:ip-10-134-206-26
Redis_Inbound_Bytes:35
Redis_Instantaneous:0
Redis_Manager:10 of 10 available
Redis_Message:EXPIRE Stories:600134400
Redis_Queue_Awaiting_Response:11
Redis_Server_Endpoint:Unspecified/ec2-xx-xxx-xxx-215.compute-1.amazonaws.com:6379
Redis_ThreadPool_IO_Completion:(Busy=0,Free=1000,Min=2,Max=1000)
Redis_ThreadPool_Workers:(Busy=9,Free=32758,Min=2,Max=32767)
Redis_Version:2.0.519.65453
redis_command:EXPIRE Stories:600134400
redis_server:ec2-xx-xxx-xxx-215.compute-1.amazonaws.com:6379
request_sent_status:Sent

# Timeout at 15:56:25
Redis_Busy_Workers:8
Redis_Client_Name:ip-10-134-206-26
Redis_Inbound_Bytes:40
Redis_Instantaneous:0
Redis_Manager:10 of 10 available
Redis_Message:EXPIRE Stories:600134400
Redis_Queue_Awaiting_Response:9
Redis_Server_Endpoint:Unspecified/ec2-xx-xxx-xxx-215.compute-1.amazonaws.com:6379
Redis_ThreadPool_IO_Completion:(Busy=0,Free=1000,Min=2,Max=1000)
Redis_ThreadPool_Workers:(Busy=8,Free=32759,Min=2,Max=32767)
Redis_Version:2.0.519.65453
redis_command:EXPIRE Stories:600134400
redis_server:ec2-xx-xxx-xxx-215.compute-1.amazonaws.com:6379
request_sent_status:Sent

# Timeout at 15:36:25
Redis_Busy_Workers:8
Redis_Client_Name:ip-10-134-206-26
Redis_Inbound_Bytes:35
Redis_Instantaneous:0
Redis_Manager:10 of 10 available
Redis_Message:EXPIRE Stories:600134400
Redis_Queue_Awaiting_Response:11
Redis_Server_Endpoint:Unspecified/ec2-xx-xxx-xxx-215.compute-1.amazonaws.com:6379
Redis_ThreadPool_IO_Completion:(Busy=0,Free=1000,Min=2,Max=1000)
Redis_ThreadPool_Workers:(Busy=8,Free=32759,Min=2,Max=32767)
Redis_Version:2.0.519.65453
redis_command:EXPIRE Stories:600134400
redis_server:ec2-xx-xxx-xxx-215.compute-1.amazonaws.com:6379
request_sent_status:Sent

I do not know what could be causing this timeout. It's strange that it's allways the same command.

**Comment by NickCraver** [comment] 2019-01-09 11:37
Can you see a `SLOWLOG` output from the Redis instance? A common thing we see here is while it appears to always be the same command getting the timeout (and that's often true), the cause is almost always the one right before it in a slow-server scenario...and that's the one we need to find. A `SLOWLOG` output will let us know if the a server stall is a thing here.

**Comment by andsee** [comment] 2019-01-14 17:36
Hi Nick.
Yes I can access the slowlog which I've modified to list anything longer than 2500ms and got nothing reported during the above errors. If I run some slower commands they appear in the log though so the slowlog is working.

**Comment by andsee** [comment] 2019-03-14 23:26
Still seeing a few of these timeouts every day :-(

**Comment by mgravell** [comment] 2019-04-02 15:05
We are aware of a problem here (relating to a race condition in the write-lock); we're dogfooding a fix locally, and hope to deploy an update in the next day or two.

**Comment by mgravell** [comment] 2019-04-04 09:09
The combined improvements in 2.0.588 and 2.0.571 should, we believe, address a wide range of timeout and performance problems. I'm closing all timeout issues as "believed fixed in 2.0.588"; if you still see problems, please report them as new issues so we can start investigation with fresh eyes.

**Closed by mgravell** 2019-04-04 09:09 UTC
