### ISSUE TITLE
ConfigurationOptions last Change afected in: .Ssl and CommandMap.Create

### ISSUE THREAD

**Issue by chimpinano** [StackExchange/StackExchange.Redis#165] opened 2015-02-20 21:57 UTC
sorry, it was my mistake..

**Comment by mgravell** [comment] 2015-02-20 22:03
I'm sorry, I can't parse that. Can you clarify what the issue is please?

**Comment by NickCraver** [comment] 2016-01-26 01:58
Closing this out, no info after the edit.

**Closed by NickCraver** 2016-01-26 01:58 UTC
